function phase5b_final_reports(out,T,P,A,meta)
% Generate final narrative from the same live tables written to CSV.
root=ashuganj_root();
if isfield(meta,'reportRoot'), root=meta.reportRoot; end % isolated artifact tests
docs=fullfile(root,'docs');
if ~isfolder(fullfile(docs,'manual')), mkdir(fullfile(docs,'manual')); end
M=T.coordMatrix; D=T.duty; E=T.effectiveness; S=T.sensitivity;
np=sum(strcmp(M.scope,'PRIMARY')&strcmp(M.verdict,'PASS'));
nc=sum(strcmp(M.verdict,'CONDITIONAL-PASS')); nf=sum(strcmp(M.verdict,'FAIL'));
nt=sum(strcmp(M.verdict,'NO-TRIP')); nx=sum(strcmp(M.verdict,'NO-PAIR'));
q=strcmp(D.breaker_ref,'Q0')&~strcmp(D.verdict,'NOTE'); g=strcmp(D.breaker_ref,'52G')&~strcmp(D.verdict,'NOTE');
qmax=max(D.I_sym_kA(q)); gmax=max(D.I_sym_kA(g));
ep=~strcmp(E.scope,'SENSITIVITY');
detect=sum(ep&contains(E.detection,'DETECTABILITY')); en=sum(ep&strcmp(E.detection,'NO-TRIP'));
eo=sum(ep&contains(E.detection,'OUT-OF-ZONE'));
cmd='matlab -batch "addpath(genpath(''matlab'')); run_phase5b_production(''final-engineering'',''overwrite'',true);"';
test=sprintf('run_phase5b_tests() PASS = %d; FAIL = %d',meta.testCounts.NP,meta.testCounts.NF);
summary=sprintf('%d PRIMARY PASS; %d CONDITIONAL-PASS; %d FAIL; %d NO-TRIP; %d NO-PAIR (%d total matrix rows).',np,nc,nf,nt,nx,height(M));
duty=sprintf('Q0: maximum %.6f kA / 50 kA = %.6f. 52G: maximum %.6f kA / 100 kA = %.6f. %d duty exceedances.',qmax,qmax/50,gmax,gmax/100,sum(strcmp(D.verdict,'FAIL')));
eff=sprintf('%d central rows: %d CONDITIONAL-DETECTABILITY, %d NO-TRIP, %d NO-PAIR/OUT-OF-ZONE; %d separate DT sensitivity rows.',sum(ep),detect,en,eo,sum(~ep));
families=unique(S.family,'stable'); fl=cell(numel(families),1);
for i=1:numel(families)
 k=strcmp(S.family,families{i}); vals=unique(S.scenario_value(k));
 fl{i}=sprintf('| %s | %s | %d |',families{i},strtrim(sprintf('%.6g ',vals)),sum(k));
end
conflicts={ ...
 'GSUT CT: manufacturer protection schedule indicates 1500/1; as-built SLD and later nameplate indicate 1600/1. Central study uses 1600/1 as ENGINEERING_ASSUMPTION. The installed function-to-core assignment remains unverified. 1500/1 is a calculated documentary sensitivity.', ...
 'GSUT impedance/loss: workbook study data give 16.63% and copper loss 912.2 kW (1067.5 minus 155.3 kW); manufacturer design sheet gives 16% and 1095 kW. The workbook-derived profile is the requested local Phase-5 study profile, not a claim that the OEM design sheet states those numbers.', ...
 'Grid: the secondary historical 45.01 kA, X/R 10.99 result implies |Z| about 2.9502 ohm at voltage factor c=1. Its reported 3.25 ohm uses an unverified convention; an implied c about 1.102 could explain the discrepancy. The requested c=1 derivation is central and 3.25 ohm is a numerical sensitivity. Neither is an official current PGCB equivalent.', ...
 'Grounding: the report marks 60 ohm as HV-winding DC resistance with a question mark and 2.62 ohm as the LV loading resistor with qualification. The frozen effective neutral resistance is 60 + n^2*2.62 ohm, where n=(22000/sqrt(3))/500. Treating 60 ohm alone as the effective neutral resistance would contradict the approximately 7.27 A central stator-earth fault.', ...
 'Regional line identity: the original 52 km Ashuganj-Kishoreganj row is in the 132-kV table. North-Bhulta is 400 kV. Regional values are reference/screening records and are not injected into the frozen South network.', ...
 'Breaker identity: Q0 is a repeated device label, not a globally unique breaker name. The central conditional mapping is the GSUT GIS bay 10ADA10/D07, 52-1(Q0). Q1/Q2 are bus-selector disconnectors, Q9 a line-side disconnector; none is invented as a circuit breaker. Line protection trips functional local/remote line-end breaker equivalents; a direct trip of the transformer-bay Q0 is not assigned without an established intertrip route.'};
verification={ ...
 'Installed relay setting files, CT protection core/tap schedule, excitation curves and actual burdens.', ...
 'Current PGCB positive/negative/zero-sequence equivalent, fault-level date and operating topology.', ...
 'Q0 exact installed transformer-bay breaker/nameplate mapping, contact-parting time, DC capability and TRV.', ...
 'GEN neutral CT ratio and commissioning test, NGT/loading-resistor interpretation and measured resistance.', ...
 '87T/87B/7SD bias, vector compensation, communication and remote-end settings; actual 86/50BF wiring.', ...
 '7UM62 64G manual/settings pages and primary injection adjustment; the supplied default values are study values.', ...
 'South route/conductor geometry and individual motor test data. The numerical study already contains practical substitutes.'};
limitations={ ...
 'The 40-row coordination input is the locked Phase-4 Ikpp backbone. Grid, motor and GSUT alternatives have separate PHASE-5 ANALYTICAL SCREENING SENSITIVITY calculations. South line impedance also determines backup distance reaches. Updated generator sequence values and regional line totals are reference profile data; they have not regenerated the full Phase-4 network or its prefault solution.', ...
 'The Phase-4 contribution CSV stores |Ia| on the fault voltage base. Phase-5 recovers faulted B/C phasors, verifies their |Ia| identity against that archive, and converts physical current by Vfault/Vdevice. No upstream fault current is edited.', ...
 'The legacy matrix columns I_down_A and I_up_A contain CT-secondary amperes. Their ct_down/ct_up columns give the ratios. phase5_relay_currents.csv explicitly provides both primary and secondary amperes and branch-specific zero-sequence current.', ...
 'Breaker duty uses maxABC physical branch Ikpp as a screening comparison. It is not an interrupting-time Ib, asymmetric DC, making-current, short-time thermal or TRV compliance study.', ...
 '87G/87T/87B/7SD results establish study observability only. CT matching, vector-group compensation, differential/restraint current, through-fault stability and CT saturation are not a manufacturer relay algorithm. Timing values are explicit proxies.', ...
 'F1 and F2 LG map to the same 22-kV fault node. Their raw terminal branches contain circulating/load current, not differential current. The earth-fault proxy uses the approximately 7.27-A neutral residual; 87G remains below its 2403.8-A start, and the HV-referred 87T proxy is about 0.696 A versus 387.84 A. Both are NO-TRIP. Dedicated 51N/64G provide the study earth-protection representation.', ...
 'NO-TRIP times are infinity: a resolved non-operation, not an unresolved parameter. NOT_APPLICABLE_TO_ROW marks structurally irrelevant heterogeneous columns, such as TMS for a differential pickup or an upstream time when no relay pair exists. Installed-value verification is separate from the fully specified study value.'};
L={'# PHASE 5 FINAL ENGINEERING REPORT','', 'Status: READY_FOR_REVIEW','', ...
 'This package is a numerically closed preliminary engineering study. Assumed settings are not claimed as commissioned plant settings.','', ...
 '## Reproduction and verification','',['`' cmd '`'],'',test,'', ...
 sprintf('Validation: %d/%d implementation legs pass. All protected Phase-2/3/4 baseline hashes are checked before and after production.',sum(T.validation.pass),height(T.validation)), ...
 '', '## Coordination result','',summary,'', ...
 'The final TMS values remain GEN-51 0.10, GSUT-51 0.55, Q0-51 0.80 and GEN-51N 0.15. No tuning adjustment was required after correcting current bases and faulted-phase selection. Conditional passes are not counted as unconditional primary passes.', ...
 '', '## Central relay settings','', ...
 '| Function | Primary pickup | CT | Secondary pickup | Characteristic / timer | Classification |', ...
 '|---|---:|---:|---:|---|---|', ...
 '| GEN-51 | 17170.8 A | 15000/1 | 1.14472 A | IEC SI, TMS 0.10 | DERIVED pickup; assumed TMS |', ...
 '| GEN-51N | 4 A | 20/1 | 0.20 A | IEC SI, TMS 0.15 | ENGINEERING_ASSUMPTION |', ...
 '| GSUT-51 | 1380 A | 1600/1 | 0.8625 A | IEC SI, TMS 0.55 | DERIVED pickup; assumed CT/TMS |', ...
 '| Q0-51 | 1500 A | 1600/1 | 0.9375 A | IEC SI, TMS 0.80 | CONDITIONAL_ASSUMPTION |', ...
 '| 87G | 2403.8 A (0.20 pu of 12019 A) | 15000/1 | 0.160253 A | 0.045 s detection proxy; high-set OFF | ENGINEERING_STUDY_PROXY timing |', ...
 '| 87T | 387.84 A (0.30 pu of 1292.8 A) | 1600/1 study | 0.2424 A | slopes 30/60%; 0.045 s proxy | ENGINEERING_STUDY_PROXY |', ...
 '| 87B | 320 A (0.20 pu on 1600 A CT base) | 1600/1 | 0.20 A | slope 30%; 0.035 s proxy | ENGINEERING_STUDY_PROXY |', ...
 '| 7SD5221 | 320 A (0.20 In on 1600 A CT base) | 1600/1 | 0.20 A | 0.035 s detection; 0.050 s scheme clearing | ENGINEERING_STUDY_PROXY |', ...
 '', 'The actual installed value could not be obtained, so the practical engineering values above were adopted for the study. In particular, the 20/1 dedicated neutral CT is a study selection consistent with sensitive stator-ground protection.', ...
 '', '## Derivations and numerical closure','', ...
 sprintf('GEN-51: 1.20 x 14309 = %.1f A. GSUT maximum-load anchor: 458e6/(sqrt(3)*230e3) = %.6f A. GSUT exact rated current: 515e6/(sqrt(3)*230e3) = %.6f A, rounded to 1292.8 A.',P.GEN_51_pickup_A,P.GSUT_maximum_load_anchor_A,P.GSUT_rated_exact_A), ...
 '', 'The GSUT load-based pickup is 1.20 times the 458-MVA through-load anchor, rounded to 1380 A. The 515-MVA nameplate current is used for the 87T base. These two currents have distinct fields and purposes.', ...
 '',sprintf('Grid derivation: |Zth| = 230000/(sqrt(3)*45010) = %.9f ohm; Rth = |Zth|/sqrt(1+10.99^2) = %.9f ohm; Xth = 10.99 Rth = %.9f ohm. Z2=Z1 and Z0=3Z1 are preliminary screening assumptions.',P.GRID_Zth_ohm,P.GRID_Rth_ohm,P.GRID_Xth_ohm), ...
 '', 'South line per circuit: 0.7(0.080+j0.350)=0.056+j0.245 ohm; zero sequence 0.7(0.250+j1.20)=0.175+j0.840 ohm. Two circuits are recorded; per-circuit and parallel-equivalent quantities are explicitly distinguished.', ...
 '', 'Distance backup: Zone 1=0.0448+j0.196 ohm (0 s proxy), Zone 2=0.0672+j0.294 ohm (0.30 s), Zone 3=0.112+j0.490 ohm (0.80 s). These are system-study backup reaches, not installed settings.', ...
 '', '50BF timers: 230 kV 0.15 s; 22 kV 0.12 s. Functional 86/trip actions are in phase5_trip_logic.csv, with adjacent affected-bus breaker sets represented without invented physical names.', ...
 '', sprintf('Grounding study: NGT 22 kV/sqrt(3) to 500 V, rated 135 kVA for 20 s. The qualified 60-ohm HV-winding component plus the reflected 2.62-ohm loading resistor gives %.6f ohm effective neutral resistance. Sensitivities vary the HV-winding component to 57/60/63 ohm; commissioning measurement remains unavailable.',60+(22000/sqrt(3)/500)^2*2.62), ...
 '', '64G study defaults: U20 MIN 1.0 V, I20 MIN 10 mA, trip resistance 20 ohm, alarm resistance 100 ohm, trip delay 1 s, alarm delay 10 s and correction angle 0 degrees. Primary-test adjustment is required before commissioning. No local manual page was found proving a commissioned setting.', ...
 '', 'Generator sequence resistance is derived from 0.00089 ohm on the 458-MVA/22-kV base; R2=R1 and R0=1.5R1 are assumptions. GSUT R=0.9122/515 and X=sqrt(0.1663^2-R^2). YNd1 zero-sequence blocking is preserved. See the parameter ledger for exact values and source qualifications.', ...
 '', sprintf('The master ledger contains %d finite numerical parameters, each with unit, status, basis, source file/section, derivation, engineering reason, sensitivity and verification requirement. See [PHASE5_ASSUMPTIONS.csv](PHASE5_ASSUMPTIONS.csv) and [PHASE5_SOURCE_AUDIT.md](PHASE5_SOURCE_AUDIT.md).',height(A)), ...
 '', '## Sensitivities actually executed','', ...
 '| Family | Scenario values | Numerical metric rows |','|---|---|---:|'};
L=[L,fl',{'', ...
 'Neutral CT cases keep the 0.20-A secondary dial fixed, giving 2/4/5-A primary thresholds at 10/20/25 ratios. The separate 4/5-A pickup comparison keeps the 20/1 CT fixed. GSUT documentary CT cases show both a retained 1380-A primary pickup and a fixed-secondary-dial sensitivity.', ...
 '', 'CT saturation cases are injected screening currents: ideal, the 32-kA 5P20 boundary, and an explicitly assumed high-current transfer reduction. A nominal 5P20 limit is not proof of CT failure; excitation and burden data are absent. Motor screening uses 12 MW + 5 MVAr divided into 9-MW MV and 3-MW LV equivalent groups, with ILR/Ir 4/5/6.', ...
 '', '## Breaker-duty result','',duty,'', ...
 'All non-exceedance verdicts remain conditional Ikpp screenings. The approximately 72-kA source number for a 22-kV fault is on the fault reference base; it cannot be compared directly to a 230-kV Q0 rating. The duty CSV retains raw_branch_kA, source_voltage_kV and breaker_voltage_kV alongside the physical conversion. No fault current or equipment rating was changed to obtain a favorable verdict.', ...
 '', '## Protection effectiveness','',eff,'', ...
 'Each detectability result is conditional on the stated simplified protection model. The 3-s DT historical comparator is SENSITIVITY only. It is not an asserted commissioned Siemens setting.', ...
 '', '## Documentary conflicts'}, bullets(conflicts), {'','## Limits of this study'}, bullets(limitations), ...
 {'','## Remaining verification-only items'}, bullets(verification), ...
 {'','## Files and integrity','', ...
 'All ten requested CSVs, both TCC PNGs, the parameter ledger, trip matrix and TCC metadata are generated under results/phase5_protection_v2. Final manifest.json and sha256.txt are created after these reports and plots; the workflow then verifies every recorded digest, including both PNGs.', ...
 '', 'Superseded final-report copies are replaced by synchronized root/docs reports. The v1 results directory remains historical regression evidence and is not a current Phase-5b result.'}];
write('PHASE5_FINAL_REPORT.md',L);
write('PHASE5_VALIDATION_REPORT.md',{'# PHASE 5 VALIDATION REPORT','',test,'',summary,'',duty,'',eff,'', ...
 'The suite validates numerical calculations, current bases, scope segregation, provenance and artifact integrity. Passing tests do not certify installed relay performance.', ...
 '',sprintf('Live implementation validation: %d/%d legs.',sum(T.validation.pass),height(T.validation)), ...
 '', 'Independent direct-formula checks, including every finite matrix operating time: PHASE5_INDEPENDENT_ARITHMETIC.csv.', ...
 '', 'Final production verifies the protected baseline and every manifest/sha256 entry after output generation.','',['Reproduce: `' cmd '`']});
write('PHASE5_DECISION_LOG.md',[{'# PHASE 5 FINAL DECISION LOG','', ...
 '1. Preserve the original Phase-2/3/4 bytes and frozen 40-row fault backbone.', ...
 '2. Resolve required numerical study parameters; retain installed-document verification as a separate obligation.', ...
 '3. Correct fault-base to physical CT/breaker-base conversion and LL/LLG faulted-phase selection. This changes the coordination counts for a physical reason.', ...
 '4. Keep starting TMS values 0.10/0.55/0.80/0.15; no adjustment was needed.', ...
 '5. Q0 uses the conditional GSUT transformer-bay path, 50-kA rating; 63 kA is equipment sensitivity only.', ...
 '6. Use analytical screening for new grid/line/motor/sequence inputs; do not label it a regenerated Phase-4 network.', ...
 '7. Use a 20/1 neutral CT and 4-A central pickup; all alternatives are fenced as SENSITIVITY.', ...
 '8. Replace stale report constants with live generated values; finalize hashes after plots/docs.', ...
 '',summary,'',test,'','Documentary decisions:'},bullets(conflicts)]);
write('NOT_DETERMINABLE_REGISTER.md',[{'# CENTRAL STUDY VALUES AND INSTALLED-DOCUMENT VERIFICATION','', ...
 'No required central numerical parameter is left unresolved. The complete numeric value/status/source/derivation register is PHASE5_ASSUMPTIONS.csv. Actual installed settings remain unverified where indicated; this does not leave the study model numerically open.', ...
 '', '7UM622 I>/time: GEN-51 17170.8 A, IEC SI, TMS 0.10 central; historical DT 17171 A / 3 s numerical sensitivity. 7UT6331 87T: 387.84 A / 0.045 s proxy; 7SS523: 320 A / 0.035 s; 7SD5221: 320 A / 0.035 s and 0.050 s scheme. Distance 21, 50BF, 64G, NER, grid and motors all have numerical ledger entries.', ...
 '', 'Other inventory functions (for example rotor-earth, reverse-power or turbine mechanical trips) are outside the short-circuit coordination calculations and are not assigned fabricated commissioning settings.', ...
 '', 'Verification-only items:'},bullets(verification)]);
write('PHASE5_PROGRESS.md',{'# PHASE 5 FINAL PROGRESS','', 'Status: READY_FOR_REVIEW','', ...
 'Source audit, central numerical closure, physical current correction, sensitivities, coordination, duty, proxies, TCCs, production tests, documentation and integrity verification are integrated in the production command.','',summary,'',duty,'',test});
write('PHASE5_BASELINE_CHECKPOINT.md',{'# PHASE 5 BASELINE CHECKPOINT','', ...
 'Protected byte ledger: docs/PHASE5_PROTECTED_BASELINE.csv (created before corrections). Phase-2 data, Phase-3 results and Phase-4 code/production outputs remain unchanged.', ...
 '', 'Phase-5 numerical consumers: phase4_fault_currents.csv provides the first stable Ikpp,m=0.5 row for each case/location/type (40 rows); phase4_contributions.csv provides the archived branch |Ia| identities. phase4_ct_data.csv supplies the historical load anchors in the project context; the final pickup philosophy uses documented maximum through-load. The Phase-4 manifest and hash ledger remain input provenance.', ...
 '', 'Phase-4 branch phasors are recomputed read-only and identity-gated against the archive. Cache keys include the input bytes and source files; a clean cache can be regenerated. No Phase-4 production workflow is invoked and no upstream file is written.', ...
 '', 'Phase-3 locked line R/X differs from the new local Phase-5 line screening. The new grid 45.01 kA scenario does not overwrite the existing frozen grid model.'});
runlog={['Final production command: ' cmd],test,summary,duty,eff, ...
 'All outputs and plots generated before final manifest/sha256; final workflow verifies hashes and protected baseline.'};
write('PHASE5_RUN_LOG.txt',runlog); put(fullfile(out,'run_log.txt'),runlog);
write('PHASE5_AI_HANDOFF.md',[{'# PHASE 5 FINAL HANDOFF','', ...
 'Status: READY_FOR_REVIEW','',['Final production command: `' cmd '`'],'',['Final test result: ' test],'', ...
 'Files modified: matlab/phase5 Phase-5b registry, pickup, coordination, duty, effectiveness, sensitivity, validation, TCC, writer and runner; updated Phase-5b regression suites. No Phase-2/3/4 files modified.', ...
 '', 'Exact code/test change inventory: docs/PHASE5_CHANGE_INVENTORY.csv, compared against tmp/phase5_final_audit/pre_final_correction.zip. Generated reports and output CSVs/plots are enumerated in the final manifest.', ...
 '', 'Files created: numerical parameter, physical-current, independent-arithmetic, cache, baseline/hash, artifact-finalization and final-report helpers; source audit/evidence; parameter/trip/TCC metadata outputs and final documentation.', ...
 '', 'Central engineering assumptions: GEN/GSUT/Q0/neutral TMS 0.10/0.55/0.80/0.15; CTs 15000/1600/1600/20; pickups 17170.8/1380/1500/4 A. Q0 remains conditional at 50 kA. Differential timing is a study proxy; no installed-setting claim.', ...
 '', sprintf('Derived values: GSUT %.1f A nameplate and %.6f A through-load anchor; 87G %.1f A; 87T %.2f A; grid %.6f ohm from 45.01 kA; %d numerical parameters generated from phase5b_parameters.',P.GSUT_rated_A,P.GSUT_maximum_load_anchor_A,P.GEN_87G_pickup_A,P.GSUT_87T_pickup_A,P.GRID_Zth_ohm,height(A)), ...
 '',sprintf('Sensitivity cases executed: %s; %d numerical metric rows.',strjoin(families,', '),height(S)), ...
 '', 'Important documentary conflicts:'},bullets(conflicts),{ ...
 '',sprintf('Primary coordination result: %d PRIMARY PASS; %d total FAIL across all scopes.',np,nf), ...
 '',sprintf('Conditional coordination result: %d CONDITIONAL-PASS. Complete matrix: %s',nc,summary), ...
 '',['Breaker-duty result: ' duty],'',['Effectiveness result: ' eff], ...
 '', 'Remaining actual-document verification items:'},bullets(verification),{ ...
 '', 'Current study limitation:'},bullets(limitations),{ ...
 '', 'Closeout evidence: docs/PHASE5_CLOSEOUT_CHECKLIST.md records the final acceptance review and resumed verification. The student manual Phase-5 section is synchronized with the final results; both manuals and the completed engineering plan are included in the artifact hashes.', ...
 '', 'Exact next action: review PHASE5_FINAL_REPORT.md, PHASE5_SOURCE_AUDIT.md and the closeout checklist. For a fresh reproduction, run the final command above. Replace study assumptions only when actual setting/CT/grid documents are obtained. Commissioning requires a separate validated relay and breaker-duty study. Phase 6 is a separate task and is not part of this handoff.'}]);
% Replace the generated manual with the final, live report rather than old values.
report=fileread(fullfile(docs,'PHASE5_FINAL_REPORT.md'));
report=strrep(strrep(strrep(report,'&','&amp;'),'<','&lt;'),'>','&gt;');
put(fullfile(docs,'manual','phase5_protection_manual.html'),{['<!doctype html><meta charset="utf-8"><title>Phase 5 final engineering study</title><style>body{max-width:1100px;margin:2em auto;font:15px/1.5 system-ui}pre{white-space:pre-wrap}</style><pre>' report '</pre>']});
 function write(name,lines)
  put(fullfile(docs,name),lines); copyfile(fullfile(docs,name),fullfile(root,name));
 end
end
function b=bullets(c)
b=cellfun(@(x)['- ' x],reshape(c,1,[]),'UniformOutput',false);
end
function put(path,lines)
fid=fopen(path,'w','n','UTF-8'); assert(fid>=0,'phase5b_reports:write','Cannot write %s',path);
cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
for i=1:numel(lines), fprintf(fid,'%s\n',lines{i}); end
end
