function S = run_phase3_load_flow(varargin)
%RUN_PHASE3_LOAD_FLOW Solves and verifies Phase-3 load-flow cases (locked 0.7 km L_LINE).
%   S = RUN_PHASE3_LOAD_FLOW() solves LF360_GAT_OUT / LF360_GAT_IN and writes
%   results/phase3_loadflow/phase3_system_summary.csv + phase3_loadflow_results.mat.
%
%   S = RUN_PHASE3_LOAD_FLOW('Cases', {'LF360_GAT_OUT'})
%   S = RUN_PHASE3_LOAD_FLOW('Cases', 'all')
%   S = RUN_PHASE3_LOAD_FLOW('Write', false)  % solve without disk writes
%
%   Field schema follows validate_phase3_network (Task 5) and the Phase-2
%   runner writer pattern (explicit fprintf writers, no fault code).
%   Reviewer-mandated hardening (Task 5 review): if ~val.converged, fill the
%   record with NaNs + Verdict DID_NOT_CONVERGE instead of throwing on the
%   validator's undefined early-return fields.

p = inputParser;
addParameter(p,'Cases',{'LF360_GAT_OUT','LF360_GAT_IN'});
addParameter(p,'Write',true,@islogical);
addParameter(p,'OutputDir','',@ischar);
parse(p,varargin{:}); opt = p.Results;
root = ashuganj_root();
if isempty(opt.OutputDir), outDir = fullfile(root,'results','phase3_loadflow');
else, outDir = opt.OutputDir; end
D = ashuganj_master_data();
if ischar(opt.Cases) && strcmp(opt.Cases,'all'), case_ids = {D.operating_profiles.ID};
elseif ischar(opt.Cases), case_ids = {opt.Cases};
else, case_ids = opt.Cases; end
if opt.Write && ~exist(outDir,'dir'), mkdir(outDir); end
S = []; all_bus_results = {};
for i = 1:numel(case_ids)
  cid = case_ids{i};
  info = build_ashuganj_main(cid,'Quiet',true,'Backup',false,'Save',false);
  C = info.case; t0 = tic;
  LF = power_loadflow(info.model,'solve'); elapsed = toc(t0);
  val = validate_phase3_network(LF,D,C,info);
  if bdIsLoaded(info.model), bdclose(info.model); end
  if ~val.converged
    % Guard: validator early-returns with only converged/iterations/verdict/
    % status defined — never touch the undefined physics fields.
    s = struct('ID',cid,'Name',C.Name,'GAT_in',C.GAT_in,'Converged',val.converged,...
      'Iterations',val.iterations,'Solve_time_s',elapsed,'Gen_P_MW',NaN,...
      'Gen_Q_MVAr',NaN,'Gen_S_MVA',NaN,'Gen_PF',NaN,...
      'Gen_PF_type','Unknown','Gen_V_pu',NaN,'Gen_V_kV',NaN,...
      'V230_1_kV',NaN,'V230_2_kV',NaN,'V6_6_kV',NaN,...
      'V_REMOTE_kV',NaN,'Paux_MW',NaN,'Qaux_MVAr',NaN,...
      'Export_P_MW',NaN,'Export_Q_MVAr',NaN,...
      'Loss_P_MW',NaN,'Loss_Q_MVAr',NaN,...
      'Line_P_loss_MW',NaN,'Line_Q_loss_MVAr',NaN,...
      'Worst_KCL_MVA',NaN,'P_balance_err_MW',NaN,...
      'Q_balance_err_MVAr',NaN,'Capability_status','UNKNOWN',...
      'Q_upper_margin_MVAr',NaN,'Q_lower_margin_MVAr',NaN,...
      'MVA_margin',NaN,'Verdict',val.verdict);
    S = [S;s]; all_bus_results{end+1} = struct('case_id',cid,'table',[]);
    continue;
  end
  s = struct('ID',cid,'Name',C.Name,'GAT_in',C.GAT_in,'Converged',val.converged,...
    'Iterations',val.iterations,'Solve_time_s',elapsed,'Gen_P_MW',val.Pgen_MW,...
    'Gen_Q_MVAr',val.Qgen_MVAr,'Gen_S_MVA',val.Sgen_MVA,'Gen_PF',val.PFgen,...
    'Gen_PF_type',val.PF_type,'Gen_V_pu',val.Vgen_pu,'Gen_V_kV',val.Vgen_kV,...
    'V230_1_kV',val.V230_1_kV,'V230_2_kV',val.V230_2_kV,'V6_6_kV',val.V6_6_kV,...
    'V_REMOTE_kV',val.V_REMOTE_kV,'Paux_MW',val.Paux_MW,'Qaux_MVAr',val.Qaux_MVAr,...
    'Export_P_MW',val.Pgrid_export_MW,'Export_Q_MVAr',val.Qgrid_export_MVAr,...
    'Loss_P_MW',val.branch_losses_P_MW,'Loss_Q_MVAr',val.branch_losses_Q_MVAr,...
    'Line_P_loss_MW',val.line_P_loss_MW,'Line_Q_loss_MVAr',val.line_Q_loss_MVAr,...
    'Worst_KCL_MVA',val.worst_KCL_MVA,'P_balance_err_MW',val.P_balance_err_MW,...
    'Q_balance_err_MVAr',val.Q_balance_err_MVAr,'Capability_status',val.capability_status,...
    'Q_upper_margin_MVAr',val.Q_upper_margin_MVAr,'Q_lower_margin_MVAr',val.Q_lower_margin_MVAr,...
    'MVA_margin',val.MVA_margin,'Verdict',val.verdict);
  S = [S;s]; all_bus_results{end+1} = struct('case_id',cid,'table',val.bus_results);
end
if opt.Write && ~isempty(S)
  write_phase3_summary_csv(fullfile(outDir,'phase3_system_summary.csv'),S);
  write_phase3_bus_results_csv(fullfile(outDir,'phase3_bus_results.csv'),all_bus_results);
  save(fullfile(outDir,'phase3_loadflow_results.mat'),'S','all_bus_results');
end
end

function write_phase3_summary_csv(filepath, S)
fid = fopen(filepath, 'w');
if fid < 0, return; end
fprintf(fid, ['Case_ID,Case_Name,GAT_in,Converged,Iterations,Solve_time_s,' ...
  'Gen_P_MW,Gen_Q_MVAr,Gen_S_MVA,Gen_PF,Gen_PF_type,Gen_V_pu,Gen_V_kV,' ...
  'V230_1_kV,V230_2_kV,V6_6_kV,V_REMOTE_kV,Paux_MW,Qaux_MVAr,' ...
  'Export_P_MW,Export_Q_MVAr,Loss_P_MW,Loss_Q_MVAr,' ...
  'Line_P_loss_MW,Line_Q_loss_MVAr,Worst_KCL_MVA,' ...
  'P_balance_err_MW,Q_balance_err_MVAr,Capability_status,' ...
  'Q_upper_margin_MVAr,Q_lower_margin_MVAr,MVA_margin,Verdict\n']);
for i = 1:numel(S)
  fprintf(fid, '%s,"%s",%d,%d,%d,%.3f,%.6f,%.6f,%.6f,%.6f,"%s",%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6e,%.6e,%.6e,%.6e,"%s",%.6f,%.6f,%.6f,"%s"\n', ...
    S(i).ID, S(i).Name, S(i).GAT_in, S(i).Converged, ...
    S(i).Iterations, S(i).Solve_time_s, ...
    S(i).Gen_P_MW, S(i).Gen_Q_MVAr, S(i).Gen_S_MVA, S(i).Gen_PF, ...
    S(i).Gen_PF_type, S(i).Gen_V_pu, S(i).Gen_V_kV, ...
    S(i).V230_1_kV, S(i).V230_2_kV, S(i).V6_6_kV, S(i).V_REMOTE_kV, ...
    S(i).Paux_MW, S(i).Qaux_MVAr, ...
    S(i).Export_P_MW, S(i).Export_Q_MVAr, ...
    S(i).Loss_P_MW, S(i).Loss_Q_MVAr, ...
    S(i).Line_P_loss_MW, S(i).Line_Q_loss_MVAr, S(i).Worst_KCL_MVA, ...
    S(i).P_balance_err_MW, S(i).Q_balance_err_MVAr, ...
    S(i).Capability_status, S(i).Q_upper_margin_MVAr, S(i).Q_lower_margin_MVAr, ...
    S(i).MVA_margin, S(i).Verdict);
end
fclose(fid);
end

function write_phase3_bus_results_csv(filepath, all_res)
fid = fopen(filepath, 'w');
if fid < 0, return; end
fprintf(fid, 'Case_ID,Bus_Name,Vnom_kV,V_pu,V_kV,Angle_deg,P_inj_MW,Q_inj_MVAr\n');
for c = 1:numel(all_res)
  cid = all_res{c}.case_id;
  tbl = all_res{c}.table;
  if isempty(tbl), continue; end
  for b = 1:numel(tbl)
    vpu = tbl(b).V_pu; % default solver-base pu: bit-identical when Vbase==Vnom
    if isfield(tbl,'V_pu_nom') && ~isnan(tbl(b).V_pu_nom) && tbl(b).Vbase_V ~= tbl(b).Vnom_V
      vpu = tbl(b).V_pu_nom; % V_kV/Vnom: B230_REMOTE solves on 100 kV block base (Vpu~2.3); reporting only
    end
    fprintf(fid, '%s,%s,%.2f,%.6f,%.6f,%.4f,%.6f,%.6f\n', ...
      cid, tbl(b).Name, tbl(b).Vnom_V/1000, vpu, tbl(b).V_kV, ...
      tbl(b).Ang_deg, tbl(b).P_inj_MW, tbl(b).Q_inj_MVAr);
  end
end
fclose(fid);
end
