function P = phase5b_pickup(device, Iload_A, Imin_fault_A)
if nargin ~= 3
    error('phase5b_pickup:args', 'usage: P = phase5b_pickup(device, Iload_A, Imin_fault_A).');
end
if ~isstruct(device) || ~isscalar(device) || ~isfield(device, 'device_id')
    error('phase5b_pickup:device', 'device must be a scalar struct with device_id (registry row).');
end
idraw = device.device_id;
if isstring(idraw) && isscalar(idraw)
    idraw = char(idraw);
end
if ~ischar(idraw) || isempty(strtrim(idraw))
    error('phase5b_pickup:device', 'device.device_id must be non-empty char (registry row).');
end
id = strtrim(idraw);
if ~isnumeric(Iload_A) || ~isscalar(Iload_A) || ~isreal(Iload_A) ...
        || ~isfinite(Iload_A) || Iload_A < 0
    error('phase5b_pickup:load', 'Iload_A must be a real finite scalar >= 0 (PRIMARY A anchor).');
end
if ~isnumeric(Imin_fault_A) || ~isscalar(Imin_fault_A) || ~isreal(Imin_fault_A) ...
        || ~isfinite(Imin_fault_A) || Imin_fault_A <= 0
    error('phase5b_pickup:fault', 'Imin_fault_A must be a real finite scalar > 0 (PRIMARY A).');
end
Iload_A = double(Iload_A);
Imin_fault_A = double(Imin_fault_A);
[Pstudy,~]=phase5b_parameters();
isBaseline = strcmp(id, 'GEN-51-SIEMENS-BL');
isGenStudy = strcmp(id, 'GEN-51') || strcmp(id, 'GEN-51-SI');
isGsut = strcmp(id, 'GSUT-HV-51');
isGis = strcmp(id, 'GIS-Q0-51');
isEfStudy = strcmp(id, 'GEN-51N') || strcmp(id, 'GEN-51N-SI-STUDY');
isGsut1500Sens = strcmp(id, 'GSUT-HV-51-1500-SENS');
isEf5Sens = strcmp(id, 'GEN-51N-5A-SENS');
isEfCt10Sens = strcmp(id, 'GEN-51N-CT10-SENS');
isEfCt20Sens = strcmp(id, 'GEN-51N-CT20-SENS');
isEfCt25Sens = strcmp(id, 'GEN-51N-CT25-SENS');
isSensHelper = isGsut1500Sens || isEf5Sens || isEfCt10Sens || isEfCt20Sens || isEfCt25Sens;
if strcmp(id, 'GIS-Q0-50')
    error('phase5b_pickup:disabled', ['phase5b_pickup: GIS-Q0-50 high-set DISABLED-unless-justified ' ...
        '(NOT DETERMINABLE FROM AVAILABLE DATA; no high-set invented; ' ...
        'high-set stays disabled).']);
end
if strcmp(id, 'LINE-21-note') || strcmp(id, 'REMOTE-GRID-boundary')
    error('phase5b_pickup:unsupported', ['phase5b_pickup: %s has no settings ' ...
        '(Use separate numerical distance/grid parameter model).'], id);
end
if ~isBaseline && ~isGenStudy && ~isGsut && ~isGis && ~isEfStudy && ~isSensHelper
    error('phase5b_pickup:unimplemented', ['phase5b_pickup: %s is not a served device ' ...
        '(served: GEN-51-SIEMENS-BL, GEN-51/GEN-51-SI, GSUT-HV-51, GIS-Q0-51, ' ...
        'GEN-51N/GEN-51N-SI-STUDY + SENSITIVITY-only GSUT-HV-51-1500-SENS/GEN-51N-5A-SENS/' ...
        'GEN-51N-CT10-SENS/GEN-51N-CT20-SENS/GEN-51N-CT25-SENS; GIS-Q0-50 DISABLED; notes/boundary unsupported). ' ...
        'No stub behavior by design (never invent settings).'], id);
end
if ~isBaseline
    TMS_GEN = Pstudy.GEN_51_TMS;
    TMS_GSUT = Pstudy.GSUT_51_TMS;
    TMS_Q0 = Pstudy.Q0_51_TMS;
    TMS_EF = Pstudy.GEN_51N_TMS;     % ledger EF-TMS-0.15, ENGINEERING_ASSUMPTION, master §21
    if isSensHelper
        if isGsut1500Sens
            CTR = 1500; IS = 1380; TMSX = TMS_GSUT;
            tag = 'GSUT-HV-51-1500-SENS-1380A-via-1500/1-0.92Asec-TMS-0.55-SENSITIVITY-only';
        elseif isEf5Sens
            CTR = 20; IS = 5; TMSX = TMS_EF;
            tag = 'GEN-51N-5A-SENS-5A-via-20/1-0.25Asec-TMS-0.15-SENSITIVITY-only';
        elseif isEfCt10Sens
            CTR = 10; IS = 4; TMSX = TMS_EF;
            tag = 'GEN-51N-CT10-SENS-4A-via-10/1-0.40Asec-TMS-0.15-SENSITIVITY-only-5A-variant-0.50Asec';
        elseif isEfCt20Sens
            CTR = 20; IS = 4; TMSX = TMS_EF;
            tag = 'GEN-51N-CT20-SENS-4A-via-20/1-0.20Asec-TMS-0.15-SENSITIVITY-only-5A-variant-0.25Asec';
        else
            CTR = 25; IS = 4; TMSX = TMS_EF;
            tag = 'GEN-51N-CT25-SENS-4A-via-25/1-0.16Asec-TMS-0.15-SENSITIVITY-only-5A-variant-0.20Asec';
        end
        IS_SEC = IS / CTR;
        P = struct('setting', IS, 'unit', 'A-primary', ...
            'basis', tag, ...
            'source', ['SENSITIVITY-only-numerical-case-never-PRIMARY-never-duty:' tag], ...
            'validation', sprintf('sensitivity-numerical-Is-%.4fA-Issec-%.4fA-via-%d/1', IS, IS_SEC, CTR), ...
            'device_id', id, 'assumption_class', 'SENSITIVITY', ...
            'tms', TMSX, 'curve', 'SI', ...
            'use_phase5_time', true, 'setting_sec_A', IS_SEC);
        if isEf5Sens || isEfCt10Sens || isEfCt20Sens || isEfCt25Sens
            P.ef_tms = TMSX;
        end
        return;
    end
    if isEfStudy
        CTR = Pstudy.GEN_51N_CT;   % dedicated neutral CT (ENGINEERING_ASSUMPTION)
        if isfield(device, 'ct_ratio') && isnumeric(device.ct_ratio) ...
                && isscalar(device.ct_ratio) && isreal(device.ct_ratio) ...
                && isfinite(device.ct_ratio) && device.ct_ratio ~= CTR
            error('phase5b_pickup:ct', 'phase5b_pickup: GEN-51N PRIMARY needs dedicated 20/1 neutral CT (got %.0f).', device.ct_ratio);
        end
        IS = Pstudy.GEN_51N_pickup_A;  % A primary, PRIMARY sensitive EF study pickup
        IS_SEC = IS / CTR;  % 0.20 A secondary
        unit = 'A-primary';
        basis = 'must-detect-F1-LG-7.27A-primary:4A-PRIMARY-via-20/1-0.20A-secondary-EF-TMS-0.15-study';
        source = ['ENGINEERING_ASSUMPTION-study-setting-PRIMARY:' ...
            '4A-primary-via-20/1-0.20A-secondary;' ...
            'ENGINEERING_ASSUMPTION-EF-TMS-0.15-ledger-EF-TMS-0.15-master-S21'];
        mFault = Imin_fault_A / IS;
        validation = sprintf(['detects-F1-LG-%.5fA-with-margin-%.3f;' ...
            'EF-TMS-0.15-per-master-S21;T7-converts-via-CT-20/1'], ...
            Imin_fault_A, mFault);
        P = struct('setting', IS, 'unit', unit, 'basis', basis, ...
            'source', source, 'validation', validation, ...
            'device_id', id, 'assumption_class', 'PRIMARY', ...
            'tms', TMS_EF, 'ef_tms', TMS_EF, 'curve', 'SI', ...
            'use_phase5_time', true, 'setting_sec_A', IS_SEC);
        return;
    end
    if isGenStudy
        CTR = 15000;   % generator T1/T2 CT (ledger GEN-T1T2-15000, VERIFIED)
        IMAX = 14309;  % A generator max operating current (ledger GEN-Imax-14309)
        if isfield(device, 'ct_ratio') && isnumeric(device.ct_ratio) ...
                && isscalar(device.ct_ratio) && isreal(device.ct_ratio) ...
                && isfinite(device.ct_ratio) && device.ct_ratio ~= CTR
            error('phase5b_pickup:ct', 'phase5b_pickup: GEN-51 study needs generator 15000/1 CT (got %.0f).', device.ct_ratio);
        end
        IS = 1.20 * IMAX;  % 17170.8 A primary
        IS_SEC = IS / CTR;  % 1.14472 A secondary
        unit = 'A-primary';
        basis = ['max-operating-current:1.20xImax-14309A=17170.8A-primary-' ...
            'SI-TMS-0.10-study;converges-with-Siemens-DT-baseline-17171A-' ...
            'characteristic-differs-SI-vs-DT'];
        source = ['DERIVED-study-setting:1.20xImax-GEN-Imax-14309A-VERIFIED;' ...
            'ENGINEERING_ASSUMPTION-OC-1.2xload-ledger-OC-1.2xload;' ...
            'ENGINEERING_ASSUMPTION-TMS-0.10-master-central-set;' ...
            'converges-with-USER_ASSERTED_PENDING_DOC-SIEMENS-Igt-1.14A-17171A-SI-vs-DT'];
        if Iload_A > 0
            mLoad = IS / Iload_A;
        else
            mLoad = Inf;
        end
        mFault = Imin_fault_A / IS;
        xerr = abs(IS - 17171) / 17171;
        validation = sprintf(['no-trip-on-load-vs-Iload-%.3fA(margin-%.3f);' ...
            'must-detect-vs-Imin-%.3fA(margin-%.3f);' ...
            'convergence-with-Siemens-DT-17171A(rel-err-%.6f)-characteristic-differs-SI-TMS-0.10-vs-DT;' ...
            'T7-converts-via-CT-15000/1'], ...
            Iload_A, mLoad, Imin_fault_A, mFault, xerr);
        P = struct('setting', IS, 'unit', unit, 'basis', basis, ...
            'source', source, 'validation', validation, ...
            'device_id', id, 'assumption_class', 'PRIMARY', ...
            'tms', TMS_GEN, 'curve', 'SI', ...
            'use_phase5_time', true, 'setting_sec_A', IS_SEC);
        return;
    end
    if isGsut
        if ~isfield(device, 'rated_A') || ~isnumeric(device.rated_A) ...
                || ~isscalar(device.rated_A) || ~isreal(device.rated_A) ...
                || ~isfinite(device.rated_A) || abs(device.rated_A - 1292.8) > 1
            error('phase5b_pickup:rated', 'phase5b_pickup: GSUT-HV-51 needs nameplate rated_A 1292.8 A (515MVA/230kV).');
        end
        CTR = 1600;    % GSUT-HV study CT (ENGINEERING_ASSUMPTION as-built SLD)
        if isfield(device, 'ct_ratio') && isnumeric(device.ct_ratio) ...
                && isscalar(device.ct_ratio) && isreal(device.ct_ratio) ...
                && isfinite(device.ct_ratio) && device.ct_ratio ~= CTR
            error('phase5b_pickup:ct', 'phase5b_pickup: GSUT-HV-51 needs study 1600/1 CT (got %.0f).', device.ct_ratio);
        end
        ANCHOR_458 = 458e6 / (sqrt(3) * 230e3);  % 1149.68 A DERIVED
        refA = max(ANCHOR_458, Iload_A);
        IS = Pstudy.GSUT_51_pickup_A;  % A nominal study pickup (1.20x1149.68=1379.62~1380; master central set)
        IS_SEC = IS / CTR;  % 0.8625 A secondary
        unit = 'A-primary';
        basis = sprintf(['above-full-load-below-min-fault:' ...
            '1.2xmax(anchor-1149.7A-458MVA,Iload-%.4fA)=%.4fA-primary-via-1600/1-rated-1292.8A-context-only'], ...
            Iload_A, IS);
        source = ['DERIVED-study-setting:1.2xmax-anchor-1149.7A-458MVA-Iload;' ...
            'ENGINEERING_ASSUMPTION-CT-1600/1-as-built-SLD-installed-unverified;' ...
            'ENGINEERING_ASSUMPTION-TMS-0.55-master-central-set'];
        if Iload_A > 0
            mLoad = IS / Iload_A;
        else
            mLoad = Inf;
        end
        mFault = Imin_fault_A / IS;
        validation = sprintf(['no-trip-on-load-vs-Iload-%.4fA(margin-%.3f);' ...
            'must-detect-vs-Imin-%.3fA(margin-%.3f);' ...
            'T7-converts-via-CT-1600/1'], ...
            Iload_A, mLoad, Imin_fault_A, mFault);
        P = struct('setting', IS, 'unit', unit, 'basis', basis, ...
            'source', source, 'validation', validation, ...
            'device_id', id, 'assumption_class', 'PRIMARY', ...
            'tms', TMS_GSUT, 'curve', 'SI', ...
            'use_phase5_time', true, 'setting_sec_A', IS_SEC);
        return;
    end
    CTR = 1600;        % GIS bay study CT (ENGINEERING_ASSUMPTION)
    if isfield(device, 'ct_ratio') && isnumeric(device.ct_ratio) ...
            && isscalar(device.ct_ratio) && isreal(device.ct_ratio) ...
            && isfinite(device.ct_ratio) && device.ct_ratio ~= CTR
        error('phase5b_pickup:ct', 'phase5b_pickup: GIS-Q0-51 needs study 1600/1 CT (got %.0f).', device.ct_ratio);
    end
    IS = Pstudy.Q0_51_pickup_A;  % A primary, CONDITIONAL provisional (never 1.2xFL here)
    IS_SEC = IS / CTR;  % 0.9375 A secondary
    unit = 'A-primary';
    basis = 'CONDITIONAL-provisional-1500A-primary-via-1600/1-above-1292.8-below-2000A-Q0-anchor-unresolved';
    source = ['CONDITIONAL:study-setting-1500A-provisional-pending-load-proof;' ...
        'ENGINEERING_ASSUMPTION-CT-1600/1;' ...
        'CONDITIONAL-TMS-0.80-master-central-set'];
    if Iload_A > 0
        mLoad = IS / Iload_A;
    else
        mLoad = Inf;
    end
    mFault = Imin_fault_A / IS;
    validation = sprintf(['conditional-vs-FL_anchor-%.6fA(margin-%.3f);' ...
        'must-detect-vs-Imin-%.3fA(margin-%.3f);' ...
        'T7-converts-via-CT-1600/1'], ...
        Iload_A, mLoad, Imin_fault_A, mFault);
    P = struct('setting', IS, 'unit', unit, 'basis', basis, ...
        'source', source, 'validation', validation, ...
        'device_id', id, 'assumption_class', 'CONDITIONAL', ...
        'tms', TMS_Q0, 'curve', 'SI', ...
        'use_phase5_time', true, 'setting_sec_A', IS_SEC);
    return;
end
IS = 17171;      % A primary (ledger SIEMENS-Igt-1.14A, USER_ASSERTED_PENDING_DOC)
TDEF = 3.00;     % s definite delay, ?? coordination-pending (ledger SIEMENS-tdef-3s-??)
CTR = 15000;     % generator T1/T2 CT (ledger GEN-T1T2-15000, VERIFIED)
IMAX = 14309;    % A generator max operating current (ledger GEN-Imax-14309)
if isfield(device, 'ct_ratio') && isnumeric(device.ct_ratio) ...
        && isscalar(device.ct_ratio) && isreal(device.ct_ratio) ...
        && isfinite(device.ct_ratio) && device.ct_ratio ~= CTR
    error('phase5b_pickup:ct', 'phase5b_pickup: GEN-51-SIEMENS-BL needs generator 15000/1 CT (got %.0f).', device.ct_ratio);
end
IS_SEC = IS / CTR;  % 1.1447333 A secondary
unit = 'A-primary';
basis = ['siemens-DT-baseline:I>-ON-inverse-disabled-1.14Asec-approx-17171Aprim-' ...
    'via-15000/1-tdef-3.00s-??-coordination-pending'];
source = ['USER_ASSERTED_PENDING_DOC:SIEMENS-Igt-1.14A+SIEMENS-tdef-3s-??-PENDING-DOC-INGEST;' ...
    'DERIVED-cross-check-1.2xImax-14309A=17170.8A-approx-17171A'];
xerr = abs(1.2 * IMAX - IS) / IS;
if Iload_A > 0
    mLoad = IS / Iload_A;
else
    mLoad = Inf;
end
mFault = Imin_fault_A / IS;
validation = sprintf(['cross-check-1.2xImax-14309A=17170.8A-vs-Is-17171A(rel-err-%.6f);' ...
    'secondary-%.4fA-via-15000/1-approx-1.14Asec;' ...
    'timing-study-comparator-STUDY-COMPARATOR;' ...
    'inverse-prohibited-use_phase5_time-false-DT-refused-by-phase5_time;' ...
    'factual-margins-vs-Iload-%.3fA(%.3f)-vs-Imin-%.3fA(%.3f)-no-verdict;T7-never-dispatched'], ...
    xerr, IS_SEC, Iload_A, mLoad, Imin_fault_A, mFault);
P = struct('setting', IS, 'unit', unit, 'basis', basis, ...
    'source', source, 'validation', validation, ...
    'device_id', id, 'assumption_class', 'SENSITIVITY', ...
    'tdef', TDEF, 'time_status', 'NUMERICAL-STUDY-COMPARATOR', ...
    'curve', 'DT', 'use_phase5_time', false, 'setting_sec_A', IS_SEC);
end

