function ctx = lr_part_theory(fid, ctx)
%LR_PART_THEORY  Sections 1-3: objectives, introduction, theory.

w = @(varargin) fprintf(fid, varargin{:});
D = ctx.D;

% ================================================================ 1 objectives
w('<section id="r1"><h2>1. Objectives</h2>\n');
w('<ol>\n');
obj = { ['To reconstruct the electrical single-line diagram of the Ashuganj ' ...
         '450&nbsp;MW combined cycle power plant (South) as an executable ' ...
         'model, from the plant''s own engineering drawings and equipment ' ...
         'data sheets rather than from typical values.']
        ['To represent every component &mdash; generator, generator step-up ' ...
         'transformer, unit auxiliary transformer, station auxiliary ' ...
         'transformer, 230&nbsp;kV gas-insulated switchgear and the external ' ...
         'grid &mdash; with parameters that each carry a source document and a ' ...
         'status, so that a reader can tell a measured number from a derived ' ...
         'one and from an assumed one.']
        ['To perform a <b>balanced steady-state load flow</b> and obtain the ' ...
         'voltage magnitude and angle at every bus, the active and reactive ' ...
         'flow in every branch, and the losses of the plant''s electrical ' ...
         'system.']
        ['To solve the study over more than one operating condition, so that ' ...
         'the effect of generator dispatch and the effect of the station ' ...
         'auxiliary transformer bay can be attributed separately instead of ' ...
         'being confounded in a single answer.']
        ['To check the solved answer independently &mdash; by rebuilding the ' ...
         'power balance at every bus outside the solver &mdash; rather than ' ...
         'accepting convergence as proof of correctness.']
        ['To state, explicitly, every parameter that is missing, uncertain, ' ...
         'assumed, derived or in conflict between source documents, and to ' ...
         'identify what must be collected before the short-circuit and ' ...
         'protection-coordination stages of the project can begin.'] };
for k = 1:numel(obj), w('<li>%s</li>\n', obj{k}); end
w('</ol>\n');
w(['<p class="note"><b>Scope of this report.</b> Short-circuit calculation, ' ...
   'unbalanced faults, relay modelling, protection grading and transient ' ...
   'stability are the later stages of the term project and are deliberately ' ...
   '<b>not</b> attempted here. The load flow is the stage that establishes the ' ...
   'pre-fault operating point every one of those later studies starts from, and ' ...
   'doing it first is not a delay &mdash; a fault study run on an unverified ' ...
   'operating point produces confident numbers that are wrong.</p>\n']);
w('</section>\n');

% ================================================================ 2 intro
w('<section id="r2"><h2>2. Introduction</h2>\n');
w('<h3>The plant</h3>\n');
w(['<p>Ashuganj Power Station Company Limited operates a %s at Ashuganj, ' ...
   'Brahmanbaria. The South block, project number %s, is a <b>single-shaft</b> ' ...
   'arrangement: one gas turbine and one steam turbine sit on a single shaft ' ...
   'driving <b>one</b> generator. This matters to the electrical model more ' ...
   'than it might appear &mdash; a multi-shaft plant of the same output would ' ...
   'present two or three generators to the 22&nbsp;kV bus, and this one ' ...
   'presents exactly one.</p>\n'], um_esc(D.meta.Train), um_esc(D.meta.Project_no));
w(['<p>The engineering was carried out by %s for the EPC contractor %s, with ' ...
   '%s equipment throughout, and the drawings use the KKS identification system ' ...
   '&mdash; every item in this report is named by its KKS tag ' ...
   '(<code>10BAT10</code>, <code>10BBT10</code>, <code>10BAY11</code>) so that ' ...
   'any figure here can be traced to an item on the plant''s own ' ...
   'drawings.</p>\n'], um_esc(D.meta.Engineering), um_esc(D.meta.EPC), ...
   um_esc(D.meta.Equipment));
w(['<p class="warn"><b>South only.</b> Ashuganj also has a North block, a ' ...
   'separate project with its own 400&nbsp;kV gas-insulated switchgear and its ' ...
   'own interbus transformers. It is excluded here, and there is <b>no ' ...
   '400&nbsp;kV node anywhere in this model</b>. Where a source document in the ' ...
   'set carries 400&nbsp;kV data, that data belongs to the North block and was ' ...
   'set aside rather than merged in.</p>\n']);

w('<h3>The electrical system to be modelled</h3>\n');
w(['<p>Power leaves the generator at 22&nbsp;kV and reaches the national grid ' ...
   'at 230&nbsp;kV through one step-up transformer. Between those two points ' ...
   'the plant taps off its own supply, and it is that tapping which makes the ' ...
   'network worth solving rather than a single series calculation:</p>\n']);
w('<ul>\n');
chain = { ['<b>G1</b>, a Siemens SGen5-2000H hydrogen-cooled generator, ' ...
           'delivering into the 22&nbsp;kV generator bus.']
          ['<b>GSUT 10BAT10</b>, the generator step-up transformer, ' ...
           '230/22&nbsp;kV, raising the whole output to transmission voltage ' ...
           'and delivering it into the 230&nbsp;kV busbars.']
          ['<b>UAT 10BBT10</b>, the unit auxiliary transformer, 22/6.9&nbsp;kV, ' ...
           'tapped off the <i>generator</i> side and feeding the plant''s own ' ...
           '6.6&nbsp;kV medium-voltage boards. While the unit runs, the plant ' ...
           'feeds itself from its own output.']
          ['<b>GAT 10BBT20</b>, the station auxiliary transformer, ' ...
           '230/6.9/3.32&nbsp;kV, fed from the <i>grid</i> side. Its purpose is ' ...
           'to supply the auxiliaries when the unit is not running &mdash; on ' ...
           'start-up, and after a trip.']
          ['The <b>230&nbsp;kV gas-insulated switchgear</b>, a Siemens 8DN9 ' ...
           'double-busbar single-breaker installation, through which the ' ...
           'step-up transformer, the station transformer and the outgoing ' ...
           'circuits are connected.'] };
for k = 1:numel(chain), w('<li>%s</li>\n', chain{k}); end
w('</ul>\n');
w(['<p>When the station transformer bay is closed while the unit is running, ' ...
   'the 6.6&nbsp;kV board has <b>two</b> sources &mdash; the UAT from the ' ...
   'generator side and the GAT from the grid side &mdash; and the network stops ' ...
   'being radial. A closed loop is formed: 230&nbsp;kV &rarr; GSUT &rarr; ' ...
   '22&nbsp;kV &rarr; UAT &rarr; 6.6&nbsp;kV &rarr; GAT &rarr; 230&nbsp;kV. ' ...
   'Power then divides between the two paths according to their impedances, not ' ...
   'according to anybody''s intention, and that division is one of the things ' ...
   'this study exists to quantify.</p>\n']);
w('</section>\n');

% ================================================================ 3 theory
w('<section id="r3"><h2>3. Theory</h2>\n');

w('<h3>3.1 What a load flow computes, and what it assumes</h3>\n');
w(['<p>A load flow finds the steady-state operating point of a network: the ' ...
   'voltage magnitude and phase angle at every bus, from which every branch ' ...
   'flow and every loss follows. It assumes the network is balanced across the ' ...
   'three phases, that it is in sinusoidal steady state at one frequency, and ' ...
   'that nothing is switching. Under those assumptions one phasor per bus ' ...
   'describes all three phases, and the whole network can be written in ' ...
   'positive-sequence form.</p>\n']);
w(['<p>At each bus the complex power injected is the product of the bus voltage ' ...
   'and the conjugate of the current entering the network:</p>\n']);
um_code(fid, sprintf([ ...
    'S_i  =  P_i + jQ_i  =  V_i . conj( sum_k ( Y_ik . V_k ) )\n\n' ...
    'and, separated into real and imaginary parts,\n\n' ...
    '  P_i = |V_i| . sum_k |V_k| . ( G_ik.cos(t_ik) + B_ik.sin(t_ik) )\n' ...
    '  Q_i = |V_i| . sum_k |V_k| . ( G_ik.sin(t_ik) - B_ik.cos(t_ik) )\n\n' ...
    'where  t_ik = angle(V_i) - angle(V_k)   and   Y_ik = G_ik + jB_ik\n' ...
    'is the element of the bus admittance matrix Y_bus.']));
w(['<p>These equations are non-linear in the voltages, so they are solved ' ...
   'iteratively. The Newton-Raphson method linearises them about the present ' ...
   'estimate using the Jacobian of the mismatch, corrects the estimate, and ' ...
   'repeats until the mismatch at every bus falls below a tolerance. Its ' ...
   'convergence is quadratic, which is why a well-posed network of this size ' ...
   'settles in a very small number of iterations &mdash; and why a solve that ' ...
   'needs many iterations is a symptom to investigate rather than a result to ' ...
   'report.</p>\n']);

w('<h3>3.2 Bus classification</h3>\n');
w(['<p>Each bus has four quantities &mdash; |V|, angle, P and Q &mdash; of ' ...
   'which two are specified and two are computed. Which two are specified is ' ...
   'what defines the bus type, and getting this wrong is the commonest way to ' ...
   'make a load flow answer a question nobody asked.</p>\n']);
ctx = lr_cap(fid, ctx, 'Bus types, and which of them appears in this network');
w(['<table><thead><tr><th>Type</th><th>Given</th><th>Computed</th>' ...
   '<th>In this model</th></tr></thead><tbody>\n']);
bt = { 'Slack (swing)', '|V|, angle', 'P, Q', ...
       'The 230&nbsp;kV grid connection. It takes up whatever the plant does not supply and absorbs whatever it exports, and it is the angle reference for the whole network.'
       'PV (generator)', 'P, |V|', 'Q, angle', ...
       'The 22&nbsp;kV generator bus. The dispatch is specified and the machine holds its terminal voltage; the reactive output that this requires is a result of the study.'
       'PQ (load)', 'P, Q', '|V|, angle', ...
       'The 6.6&nbsp;kV auxiliary board, and every bus that neither generates nor is the reference.' };
for k = 1:size(bt,1)
    w('<tr><td><b>%s</b></td><td>%s</td><td>%s</td><td>%s</td></tr>\n', bt{k,:});
end
w('</tbody></table>\n');
w(['<p>Exactly one slack bus exists, and there must be exactly one: without it ' ...
   'the losses have no supplier, because the losses are not known until after ' ...
   'the solution and so cannot be scheduled beforehand.</p>\n']);

w('<h3>3.3 The per-unit system</h3>\n');
w(['<p>Every quantity is normalised to a base, so that a transformer ratio ' ...
   'disappears from the arithmetic and a value can be compared across voltage ' ...
   'levels. The base power is chosen once for the whole system and the base ' ...
   'voltage changes with the transformer ratios:</p>\n']);
um_code(fid, sprintf([ ...
    'S_base = %g MVA        chosen once, for the whole system\n' ...
    'V_base                 the nominal voltage of each level: 230 kV, 22 kV, 6.6 kV\n\n' ...
    'Z_base = V_base^2 / S_base        I_base = S_base / ( sqrt(3) . V_base )\n\n' ...
    'A transformer impedance quoted on its OWN rating must be converted:\n\n' ...
    '  Z_new_pu = Z_old_pu . ( S_new / S_old ) . ( V_old / V_new )^2'], ...
    D.base.Sbase_MVA));
w(['<p class="note"><b>The base is a reporting convention, not plant data.</b> ' ...
   'A per-unit loading on a %g&nbsp;MVA system base says nothing about whether ' ...
   'a transformer is thermally overloaded, because the transformer''s own ' ...
   'rating is not %g&nbsp;MVA. In this report every transformer loading is ' ...
   'therefore reported a second time, as a percentage of the nameplate rating ' ...
   'of <i>each cooling stage</i>. That is the number with a physical ' ...
   'meaning.</p>\n'], D.base.Sbase_MVA, D.base.Sbase_MVA);

w('<h3>3.4 The two-winding transformer in a load flow</h3>\n');
w(['<p>For a balanced load flow the transformer reduces to a series leakage ' ...
   'impedance and an ideal ratio, with a shunt magnetising branch that ' ...
   'contributes the no-load loss. The short-circuit test gives the series ' ...
   'element and the open-circuit test gives the shunt one:</p>\n']);
um_code(fid, [ ...
    'Z_pu = z_percent / 100         on the transformer''s own rating\n' ...
    'R_pu = P_load_loss / S_rated   copper loss, from the short-circuit test\n' ...
    'X_pu = sqrt( Z_pu^2 - R_pu^2 ) leakage reactance\n\n' ...
    'X/R  is large for a power transformer, so almost all of the nameplate\n' ...
    'impedance is reactance and the transformer is very nearly a pure\n' ...
    'reactor at fundamental frequency.']);
w(['<p>The vector group matters. A delta-star transformer introduces a fixed ' ...
   'phase shift &mdash; 30&deg; per the group number &mdash; between its ' ...
   'windings. In a radial network the shift is a bookkeeping detail. In a ' ...
   '<i>looped</i> network it is not: two paths that meet again must agree about ' ...
   'the angle, and a phase shift entered wrongly appears as circulating power ' ...
   'that is entirely an artefact. This model carries the vector groups as they ' ...
   'are on the nameplates, and the loop cases are the reason for the care.</p>\n']);

w('<h3>3.5 The external grid equivalent</h3>\n');
w(['<p>The national grid cannot be modelled in detail from a plant''s own ' ...
   'documents, so it is reduced to a Th&eacute;venin equivalent: an ideal ' ...
   'voltage source behind a series impedance. The impedance follows from the ' ...
   'short-circuit level at the point of connection:</p>\n']);
um_code(fid, [ ...
    'S_k"  = sqrt(3) . V_nominal . I_k"        the short-circuit level\n' ...
    'Z_th  = V_nominal^2 / S_k"                the equivalent series impedance\n\n' ...
    'A LARGE S_k" means a SMALL Z_th, i.e. a stiff grid whose voltage barely\n' ...
    'moves with the plant''s export. A small S_k" means a weak grid.']);
w(['<p class="warn"><b>This is the weakest number in the model, and it is ' ...
   'labelled as such wherever it appears.</b> No short-circuit level for this ' ...
   'busbar was issued by the utility in the document set. The value used is ' ...
   'the ESTIMATED Siemens external-grid source quantity (§2.4: UNgrid 230 kV; ' ...
   'XN 2,66 estimated [=2.66]; Sk 19.919 [=19,919 MVA]; Ik 50 kA; executed ' ...
   '|Z| = 2.65581124 ohm via √3) &mdash; not a PGCB fault level. Equipment ' ...
   '50 kA/1 s+3 s, 125 kA peak, 50 kA making are separate EQUIPMENT RATINGS. ' ...
   'It is used because a load flow needs something ' ...
   'there, it is declared rather than presented as data, and its influence on ' ...
   'the answers was measured separately by sensitivity test.</p>\n']);
w('</section>\n');
end
