function ctx = lr_part_quest(fid, ctx)
%LR_PART_QUEST  Section 10: report questions, answered from this plant's numbers.
%
%   The EEE 306 labsheets end with report questions. These are written in that
%   form deliberately - they are the questions this particular set of results
%   provokes, and each answer is grounded in a figure from section 7 rather than
%   in a general statement that would be true of any plant.

w  = @(varargin) fprintf(fid, varargin{:});
D  = ctx.D;
c1 = ctx.SUM.Case{1};
S1 = ctx.SUM(strcmp(ctx.SUM.Case, c1), :);
T1 = ctx.TX(strcmp(ctx.TX.Case, c1), :);
B1 = ctx.BUS(strcmp(ctx.BUS.Case, c1), :);

% the same dispatch, solved radial and looped - the pair that isolates the loop
ids  = {D.cases.ID};
gin  = [D.cases.GAT_in];
pair = struct('rad', '', 'lup', '');
for k = 1:height(ctx.SUM)
    ic = find(strcmp(ids, ctx.SUM.Case{k}), 1);
    if isempty(ic), continue, end
    same = abs(ctx.SUM.P_dispatch_MW - ctx.SUM.P_dispatch_MW(k)) < 1e-6;
    for j = find(same)'
        jc = find(strcmp(ids, ctx.SUM.Case{j}), 1);
        if ~isempty(jc) && gin(ic) ~= gin(jc)
            if gin(ic), pair.lup = ctx.SUM.Case{k}; pair.rad = ctx.SUM.Case{j};
            else,       pair.rad = ctx.SUM.Case{k}; pair.lup = ctx.SUM.Case{j};
            end
        end
    end
    if ~isempty(pair.rad), break, end
end

w('<section id="r10"><h2>10. Report questions</h2>\n');
w('<ol class="steps">\n');

% ---------------------------------------------------------------------- Q1
v230 = B1.V_pu(strcmp(B1.Bus, 'B230_1'));
w(['<li><b>The plant exports %.1f&nbsp;MW, and yet the 230&nbsp;kV busbar solves ' ...
   'below nominal at %.5f&nbsp;pu. Reconcile those two statements.</b>\n'], ...
   S1.P_export_MW, v230(1));
w(['<p>Voltage magnitude along an inductive path is set by the <i>reactive</i> ' ...
   'flow, and real power transfer appears in the <i>angle</i>. This plant exports ' ...
   'real power while <b>absorbing</b> %.1f&nbsp;MVAr, so its end of the connection ' ...
   'sits below the grid end. The real export shows up instead as the %.4f&deg; ' ...
   'angle at the 230&nbsp;kV bus. Had the generator been dispatched to supply ' ...
   'reactive power rather than absorb it, the same real export would have raised ' ...
   'that bus above nominal.</p></li>\n'], -S1.Q_export_MVAr, ...
   B1.Angle_deg(strcmp(B1.Bus, 'B230_1')));

% ---------------------------------------------------------------------- Q2
if ~isempty(pair.rad)
    ur = ctx.TX.Loading_pct_lowest_stage(strcmp(ctx.TX.Case,pair.rad) & contains(ctx.TX.Transformer,'UAT'));
    ul = ctx.TX.Loading_pct_lowest_stage(strcmp(ctx.TX.Case,pair.lup) & contains(ctx.TX.Transformer,'UAT'));
    w(['<li><b>Cases %s and %s have identical dispatch and identical auxiliary ' ...
       'load. Closing the station auxiliary transformer bay adds nothing to the ' ...
       'plant, yet the unit auxiliary transformer''s loading rises from ' ...
       '%.2f&nbsp;%% to %.2f&nbsp;%%. Where does the extra loading come ' ...
       'from?</b>\n'], pair.rad, pair.lup, ur, ul);
    w(['<p>From circulating power, not from load. Closing the bay completes a loop ' ...
       '&mdash; 230&nbsp;kV &rarr; GSUT &rarr; 22&nbsp;kV &rarr; UAT &rarr; ' ...
       '6.6&nbsp;kV &rarr; GAT &rarr; 230&nbsp;kV. The two paths back to the ' ...
       '230&nbsp;kV bus have different impedances and different ratios, so power ' ...
       'divides between them by impedance rather than by intention. The unit ' ...
       'transformer ends up feeding the board <i>and</i> feeding the station ' ...
       'transformer, which returns that power to the busbar it came from. Both ' ...
       'transformers carry the circulating component, neither does useful work ' ...
       'with it, and both are heated by it. Section&nbsp;9.4 gives the ' ...
       'arithmetic.</p></li>\n']);
end

% ---------------------------------------------------------------------- Q3
gs  = T1(contains(T1.Transformer, 'GSUT'), :);
gsd = D.tx(strcmp({D.tx.Name}, 'GSUT'));
w(['<li><b>Table&nbsp;%d shows the step-up transformer at %.2f&nbsp;%% loading. ' ...
   'Is the transformer overloaded? What would you have to know to answer?</b>\n'], ...
   ctx.t_tx, gs.Loading_pct_lowest_stage(1));
w(['<p>The question cannot be answered from that figure alone, and this is the ' ...
   'commonest misreading of a load-flow result. %.2f&nbsp;%% is measured against ' ...
   'the <b>%s</b> rating of %g&nbsp;MVA &mdash; the rating with no pumps and no ' ...
   'fans running. Against the top stage, %s at %g&nbsp;MVA, the same flow is ' ...
   '%.2f&nbsp;%%. What must be known is which cooling stage is in service at ' ...
   'rated output, and that is a plant operating fact absent from the document ' ...
   'set. What the study <i>can</i> assert is the negative: at this output the ' ...
   'transformer cannot be running in its lowest cooling stage.</p></li>\n'], ...
   gs.Loading_pct_lowest_stage(1), um_esc(gsd.Cooling{1}), gsd.S_MVA(1), ...
   um_esc(gsd.Cooling{end}), gsd.S_MVA(end), gs.Loading_pct_highest_stage(1));

% ---------------------------------------------------------------------- Q4
w(['<li><b>Why is the 6.6&nbsp;kV bus voltage reported on two different bases, ' ...
   'and which of the two figures should the plant use?</b>\n']);
w(['<p>Because the documents disagree. The medium-voltage system is nominally ' ...
   '6.6&nbsp;kV, while the transformer windings feeding it are rated ' ...
   '6.9&nbsp;kV on their nameplates. Dividing the same solved voltage by the two ' ...
   'gives figures about 4.5&nbsp;%% apart &mdash; one above nominal and one below ' ...
   'it. Which to use is not a modelling question but a documentation question: ' ...
   'the correct base is whichever one the plant''s own operating limits and relay ' ...
   'settings are written against. Until that is established, choosing one would ' ...
   'be presenting a preference as a result, so both are reported. Note that no ' ...
   '<i>flow</i> in the study is affected &mdash; only the per-unit label on a ' ...
   'voltage.</p></li>\n']);

% ---------------------------------------------------------------------- Q5
w(['<li><b>Every case converges in %d iterations. What does that establish, and ' ...
   'what does it not?</b>\n'], max(ctx.SUM.Iterations));
w(['<p>It establishes that the Newton-Raphson iteration found a point where its ' ...
   'own mismatch was below its own tolerance, and that the network is ' ...
   'well-conditioned. It establishes nothing at all about whether the network is ' ...
   'the plant. A model with a transformer wired to the wrong busbar, or with an ' ...
   'impedance entered on the wrong base, converges just as fast and answers a ' ...
   'different question. That is why the solved voltages were used to rebuild the ' ...
   'power balance at every bus <i>outside</i> the solver (Table&nbsp;%d), and why ' ...
   'the vector groups were checked against the solved angles ' ...
   '(section&nbsp;9.7). Convergence is a precondition for reading the results, ' ...
   'not evidence that they are right.</p></li>\n'], ctx.t_res);

% ---------------------------------------------------------------------- Q6
if ~isempty(pair.rad)
    qr = ctx.SUM.Q_gen_MVAr(strcmp(ctx.SUM.Case, pair.rad));
    ql = ctx.SUM.Q_gen_MVAr(strcmp(ctx.SUM.Case, pair.lup));
    w(['<li><b>With identical real dispatch, the generator''s reactive output is ' ...
       '%.3f&nbsp;MVAr in case %s and %.3f&nbsp;MVAr in case %s. Which is the ' ...
       'machine''s true reactive output?</b>\n'], qr, pair.rad, ql, pair.lup);
    w(['<p>Neither, in the sense the question implies. Reactive output is not a ' ...
       'property of the machine; it is what the network requires of the machine to ' ...
       'hold the specified terminal voltage. Change the network &mdash; here, by ' ...
       'closing one bay &mdash; and the requirement changes. Both figures are ' ...
       'correct answers to different questions, which is the whole reason for ' ...
       'solving a case matrix instead of one case.</p>\n']);
    w(['<p class="warn">Two caveats travel with both numbers. The terminal voltage ' ...
       'they are computed from is an <b>assumption</b>, not an operating record, ' ...
       'so the reactive figures inherit that status. And no reactive limit was ' ...
       'imposed, because the machine''s capability curve is not in the document ' ...
       'set &mdash; the solver would happily report a reactive output the ' ...
       'generator could not actually sustain, and it must be checked against the ' ...
       'curve when the curve is obtained.</p></li>\n']);
end

% ---------------------------------------------------------------------- Q7
w(['<li><b>The external grid is represented by the ESTIMATED Siemens §2.4 source ' ...
   'quantity (50 kA). Suppose the true level is half that. ' ...
   'What in this report changes, and what does not?</b>\n']);
w(['<p>Very little of <i>this</i> report changes. Halving the assumed level ' ...
   'doubles the equivalent series impedance, which moves the 230&nbsp;kV bus ' ...
   'voltage and, through it, the reactive drawn from the grid. It barely touches ' ...
   'the plant-side answers: the dispatch is specified, the auxiliary load is ' ...
   'specified, and the transformer flows that follow from them are almost ' ...
   'unmoved. That insensitivity was measured rather than asserted &mdash; ' ...
   '<code>matlab/tests/test_grid_sensitivity.m</code> varies the impedance ' ...
   'deliberately and reports what moves.</p>\n']);
w(['<p>The <b>short-circuit study is a different matter entirely.</b> There the ' ...
   'grid impedance is one of the two dominant terms in every fault current at ' ...
   '230&nbsp;kV, and halving the level roughly halves the grid contribution. ' ...
   'Every breaker duty check and every 230&nbsp;kV relay setting would move with ' ...
   'it. So the tolerable weakness of this input in a load flow becomes ' ...
   'intolerable in the next stage, and a utility-issued fault level for this ' ...
   'busbar is the single most important item on the collection list in ' ...
   'section&nbsp;11.</p></li>\n']);

% ---------------------------------------------------------------------- Q8
g = D.gen(1);
w(['<li><b>The generator''s reactances are in the dataset &mdash; x_d = ' ...
   '%.2f&nbsp;%%, x_d&prime; = %.2f&nbsp;%%, x_d&Prime; = %.2f&nbsp;%% &mdash; ' ...
   'and none of them is used by the load flow. Why enter them, and when do they ' ...
   'come into play?</b>\n'], g.xd_pct, g.xdp_pct, g.xdpp_pct);
w(['<p>A balanced load flow sees the machine as a boundary condition: a specified ' ...
   'real power at a specified terminal voltage. What lies behind the terminals is ' ...
   'irrelevant, because nothing is changing and no fault is drawing on the ' ...
   'machine''s internal flux. They are entered because they are the parameters ' ...
   'the <i>next</i> stage runs on, and because they were on the nameplate in ' ...
   'front of us: the subtransient value sets the initial symmetrical fault ' ...
   'current, the transient value governs the first cycles that a relay must ' ...
   'coordinate within, and the synchronous value governs the sustained ' ...
   'condition. Capturing them during the data audit, with their source recorded, ' ...
   'means the fault study begins with verified machine data instead of a fresh ' ...
   'search.</p></li>\n']);

w('</ol>\n');
w('</section>\n');

ctx = lr_part_next(fid, ctx);
end
