function ctx = lr_part_next(fid, ctx)
%LR_PART_NEXT  Section 11, first half: what to collect, and everything assumed.

w = @(varargin) fprintf(fid, varargin{:});
D = ctx.D;

w('<section id="r11"><h2>11. What to perform next</h2>\n');
w(['<p>This report closes one stage of the term project and defines the next. It ' ...
   'does that in two parts: the data that has to be obtained before another study ' ...
   'can honestly be run, and the studies themselves in the order their inputs ' ...
   'become available.</p>\n']);

% ------------------------------------------------------------ 11.1 collect
w('<h3>11.1 Data still to be collected</h3>\n');
w(['<p>Listed in the order that unblocks the most work. The right-hand column is ' ...
   'the point of the table &mdash; each item is here because a specific study ' ...
   'cannot be run without it, not because the list looked short.</p>\n']);
ctx = lr_cap(fid, ctx, 'Outstanding data, who holds it, and what it unblocks');
w(['<table class="files"><thead><tr><th>#</th><th>What is needed</th>' ...
   '<th>Held by</th><th>What it unblocks</th></tr></thead><tbody>\n']);
need = { ...
 ['Three-phase and single-phase <b>short-circuit level</b> at the 230&nbsp;kV ' ...
  'Ashuganj busbar, with X/R'], 'PGCB (system planning)', ...
  ['The whole short-circuit stage. The value in use is the ESTIMATED Siemens §2.4 ' ...
  'source quantity, which is not a PGCB fault level. ' ...
  'Highest priority in the list.']
 ['Generator <b>capability curve</b> (P&ndash;Q diagram), and the reactive ' ...
  'limits actually applied'], 'Siemens / APSCL operations', ...
 ['Whether the reactive outputs this study reports are operating points the ' ...
  'machine can hold. No reactive limit is imposed at present.']
 ['Generator <b>terminal voltage set-point</b> in normal running, and a ' ...
  'dispatch record'], 'APSCL operations (log sheets)', ...
 ['Replaces the assumed 1.00&nbsp;pu set-point, which is the datum every ' ...
  'voltage in this report is measured against, and the assumed dispatch.']
 ['<b>Cooling stage</b> in service at rated output, and the <b>tap position</b> ' ...
  'in service on each transformer'], 'APSCL operations', ...
 ['Turns the loading figures from a range into a number, and settles whether ' ...
  'the step-up transformer reading above 100&nbsp;% means anything.']
 ['Normal running state of the <b>station transformer bay</b> and the ' ...
  '<b>230&nbsp;kV bus coupler</b>'], 'APSCL operations', ...
 ['Chooses between the case pairs in this report instead of carrying all of ' ...
  'them, and fixes which topology the protection settings must suit.']
 ['<b>6.6&nbsp;kV feeder and busduct impedances</b> &mdash; cable type, size, ' ...
  'length, or a cable schedule'], 'Plant cable schedule / EPC records', ...
 ['Real losses instead of a floor, feeder voltage drop, per-node voltages, and ' ...
  'the point at which the load allocation starts to matter.']
 ['<b>400&nbsp;V board</b> transformer ratings and impedances, and the LV load ' ...
  'breakdown'], 'Plant records', ...
 ['The low-voltage voltage profile. The LV demand is already inside the ' ...
  '6.6&nbsp;kV total, so the power balance is not affected.']
 ['Outgoing <b>230&nbsp;kV line</b> data: R&#8321;, X&#8321;, susceptance, ' ...
  'length, circuit count, remote end'], 'PGCB', ...
 ['Any study that extends past the plant boundary. The present model stops at ' ...
  'the busbar and represents everything beyond it as one equivalent.']
 ['<b>CT and VT ratios</b>, relay makes and models, and the settings currently ' ...
  'applied'], 'APSCL protection department', ...
 'Protection coordination &mdash; the stated objective of the term project.'
 ['Generator x_q, R_a, inertia constant H and the open-circuit time ' ...
  'constants'], 'Siemens', ...
 ['Transient stability, if that stage is attempted. None of them is needed for ' ...
  'a balanced load flow, which is why their absence has not blocked this ' ...
  'stage.']
 ['Confirmation of <b>zero-sequence</b> data and the neutral earthing resistor ' ...
  'value'], 'Siemens / APSCL', ...
 ['Unbalanced fault analysis &mdash; single line to ground and line to line. ' ...
  'Zero-sequence impedance is already in the dataset for the transformers but ' ...
  'is unused by a balanced study.'] };
for k = 1:size(need,1)
    w(['<tr><td class="tag">%d</td><td>%s</td><td>%s</td><td>%s</td></tr>\n'], ...
      k, need{k,1}, need{k,2}, need{k,3});
end
w('</tbody></table>\n');
w(['<p class="note">Items 1 to 5 are the ones that change conclusions already in ' ...
   'this report. Items 6 to 11 extend the study rather than correct it.</p>\n']);

% ------------------------------------------------------------ 11.2 assumed
w('<h3>11.2 Everything assumed, estimated or simplified in this model</h3>\n');
w(['<p>Nothing in the model is a typical value quietly substituted for a missing ' ...
   'one. Where a number could not be sourced, one of three things was done, and ' ...
   'the three are kept apart because they carry different weight.</p>\n']);

af = fieldnames(D.assumptions);
ctx = lr_cap(fid, ctx, sprintf(['Approved assumptions &mdash; values that enter ' ...
    'the model and are not plant data (%d)'], numel(af)));
w(['<table class="files"><thead><tr><th>Assumption</th><th>Value used</th>' ...
   '<th>Approved</th><th>What it is worth in the answers</th>' ...
   '</tr></thead><tbody>\n']);
for k = 1:numel(af)
    a = D.assumptions.(af{k});
    if isnumeric(a.Value), vs = mat2str(a.Value, 6); else, vs = um_esc(a.Value); end
    w('<tr><td>%s<br><span class="sl"><code>%s.m</code></span></td>', ...
      um_esc(a.Parameter), af{k});
    w('<td>%s</td><td>%s</td><td>%s</td></tr>\n', vs, a.Date, worth(af{k}));
end
w('</tbody></table>\n');
w(['<p>Each of those is a file in <code>matlab/data/assumptions/</code>, never in ' ...
   '<code>matlab/data/</code>, so an assumed number cannot be mistaken for a ' ...
   'measured one by anybody reading the dataset. Each file carries its own ' ...
   'reason, its approval date, and its quantified effect at greater length than ' ...
   'the table above.</p>\n']);

w(['<p><b>One further value is estimated rather than assumed.</b> The external ' ...
   'grid short-circuit current, %g&nbsp;kA, is the ESTIMATED Siemens §2.4 ' ...
   'external-grid source quantity (equipment 50 kA/1 s+3 s, 125 kA peak, 50 kA ' ...
   'making are separate ratings) because no utility figure exists in the ' ...
   'document set. It is marked <code>ESTIMATED</code> in the dataset, it is ' ...
   'item&nbsp;1 in the collection list above, and its influence was measured by ' ...
   'sensitivity test rather than assumed to be small.</p>\n'], D.grid.Isc_kA);

sf = fieldnames(D.superseded);
if ~isempty(sf)
    w(['<p><b>%d assumption has been retired</b> and is retained rather than ' ...
       'deleted, because a register that quietly drops its own mistakes is not an ' ...
       'audit trail: '], numel(sf));
    for k = 1:numel(sf)
        w('<code>%s.m</code> ', sf{k});
    end
    w(['&mdash; superseded once data was found that made the parameter ' ...
       'derivable. It enters nothing into the model.</p>\n']);
end

ctx = lr_cap(fid, ctx, sprintf(['Structural simplifications &mdash; treatments ' ...
    'that enter no number at all (%d)'], size(D.structural,1)));
w('<table class="files"><tbody>\n');
for k = 1:size(D.structural,1)
    w('<tr><td class="tag">%s</td><td>%s</td></tr>\n', ...
      D.structural{k,1}, um_esc(D.structural{k,2}));
end
w('</tbody></table>\n');
w(['<p>These are the third category, and the reason they are listed separately is ' ...
   'that none of them is a value. Each is a decision to represent something as ' ...
   'what it is electrically &mdash; a zero-sequence element carries no balanced ' ...
   'current, a closed breaker is an identity rather than a branch &mdash; or a ' ...
   'decision to leave something out and say so. They cannot be wrong in the way a ' ...
   'number can be wrong, but they bound what the model is entitled to be asked, ' ...
   'and section&nbsp;11.3 says which of them the next stage has to ' ...
   'undo.</p>\n']);

ctx = lr_part_next2(fid, ctx);
end

% =====================================================================
function s = worth(name)
%WORTH  One line on what each approved assumption changes in the results.
%   Written per assumption rather than pulled from the file's Impact text, which
%   runs to a paragraph. An unrecognised name is reported as unsummarised rather
%   than given a plausible-sounding line.
switch name
    case 'grid_series_resistance_zero'
        s = ['Negligible here. The equivalent is almost purely reactive at ' ...
             'X/R above 20, and the plant-side answers are set by the ' ...
             'specified dispatch and load. It matters for fault X/R, not for ' ...
             'this load flow.'];
    case 'aux_load_allocation_split'
        s = ['<b>Exactly nothing.</b> The three boards are joined by ' ...
             'zero-impedance feeders, so they solve as one node and every ' ...
             'result is identical to a single lumped load. Verified ' ...
             'numerically, not asserted. It begins to matter the moment ' ...
             'feeder impedances arrive.'];
    case 'gis_bus_coupler_closed'
        s = ['Decides whether the two 230&nbsp;kV busbars are one node or ' ...
             'two. With the station transformer bay closed it also decides ' ...
             'whether the loop of section&nbsp;9.4 exists, so it is not ' ...
             'cosmetic.'];
    otherwise
        s = ['<i>not summarised by this generator &mdash; read the file ' ...
             'before citing it</i>'];
end
end
