function ctx = lr_part_method(fid, ctx)
%LR_PART_METHOD  Sections 4-6: software and data used, procedure, connection diagram.

w = @(varargin) fprintf(fid, varargin{:});
D = ctx.D;
root = ctx.root;

% ================================================================ 4 apparatus
w('<section id="r4"><h2>4. Software and data used</h2>\n');

w('<h3>4.1 Software</h3>\n');
ctx = lr_cap(fid, ctx, 'Computational environment, read from the running installation');
w('<table class="files"><tbody>\n');
sw = { 'MATLAB',                              version
       'Platform',                            computer
       'Simulink',                            'block-diagram environment hosting the network'
       'Simscape Electrical &mdash; Specialized Power Systems', 'the positive-sequence electrical component library'
       'Load flow engine',                    '<code>power_loadflow</code>, reached from the <code>powergui</code> block'
       'System frequency solved at',           sprintf('%g Hz', D.base.f_Hz)
       'Reporting base',                       sprintf('%g MVA', D.base.Sbase_MVA) };
for k = 1:size(sw,1)
    w('<tr><td>%s</td><td>%s</td></tr>\n', sw{k,1}, um_esc_keep(sw{k,2}));
end
w('</tbody></table>\n');
w(['<p class="note"><b>50&nbsp;Hz, deliberately and repeatedly.</b> Bangladesh ' ...
   'operates at 50&nbsp;Hz. A previous study of this same plant, carried out in ' ...
   'CYME&nbsp;PSAF and supplied with the source material, was built at ' ...
   '60&nbsp;Hz. That frequency was rejected rather than reconciled: every ' ...
   'reactance in this model is at 50&nbsp;Hz, and the solved frequency is ' ...
   'written into every results table so it can be checked rather than ' ...
   'trusted.</p>\n']);

w('<h3>4.2 Source documents</h3>\n');
w(['<p>No parameter in this study was taken from a textbook table of typical ' ...
   'values. Every value traces to one of the documents below, and each value in ' ...
   'the dataset records which one, together with a status &mdash; verified from ' ...
   'the plant, verified from an engineering document, derived from verified ' ...
   'data, assumed, estimated, missing, or in conflict between two ' ...
   'documents.</p>\n']);
pdfs = dir(fullfile(root, 'fwdtechnicaldatasldrequestforbueteeetermproject', '*.pdf'));
ctx = lr_cap(fid, ctx, sprintf(['Engineering documents supplied by APSCL ' ...
    '(%d files, listed as found on disk)'], numel(pdfs)));
w('<table class="files"><tbody>\n');
for k = 1:numel(pdfs)
    w('<tr><td><code>%s</code></td><td>%s</td></tr>\n', ...
      um_esc(pdfs(k).name), doc_role(pdfs(k).name));
end
w('</tbody></table>\n');
w(['<p>Two further sources sit alongside those: the structured workbook ' ...
   '<code>Ashuganj_South_PSAF_Tabular_Engineer_Source.xlsx</code>, which ' ...
   'indexes the plant''s data into tables, and the project proposal ' ...
   '<code>grp3_eee306_jan26_project_proposal_v2.pdf</code>. The workbook is an ' ...
   'index, and it was treated as one: where it disagreed with an original ' ...
   'engineering document, the original document was preferred and the ' ...
   'disagreement was written down rather than resolved silently.</p>\n']);

w('<h3>4.3 How disagreements between documents were handled</h3>\n');
w(['<p>Sources were ranked before any of them was used: original engineer and ' ...
   'plant documents first, then manufacturer data sheets, then the official ' ...
   'single-line diagrams, then the engineer-completed data form, then the ' ...
   'structured workbook. Where two sources gave different values for the same ' ...
   'quantity, <b>both were kept</b>. Each such case is recorded in ' ...
   '<code>docs/validation/conflicting_parameters.md</code> with both values, ' ...
   'both sources, and an explanation of why they differ &mdash; different ' ...
   'cooling stage, different tap, different base, or a genuine ' ...
   'discrepancy.</p>\n']);
w(['<p>One of those conflicts reaches the results of this report directly and is ' ...
   'therefore flagged wherever it appears: the auxiliary transformer secondary ' ...
   'windings are rated <b>6.9&nbsp;kV</b> on their nameplates, while the ' ...
   'medium-voltage system they feed is nominally <b>6.6&nbsp;kV</b>. The ' ...
   'difference is worth about 4.5&nbsp;%% on any per-unit voltage reported at ' ...
   'that bus, so the bus voltage is reported <b>on both bases</b> rather than ' ...
   'on whichever one looks better.</p>\n']);
w('</section>\n');

% ================================================================ 5 procedure
w('<section id="r5"><h2>5. Procedure</h2>\n');
w(['<p>The model is not drawn by hand. It is generated from the dataset by ' ...
   'script, which is the reason a parameter can be changed in one place and the ' ...
   'diagram, the solution and every table follow. The sequence below is what a ' ...
   'run does, in order.</p>\n']);

w('<ol class="steps">\n');
w(['<li><b>Assemble the dataset.</b> Every parameter, with its source document, ' ...
   'page, status and note, is returned by one function. Nothing downstream ' ...
   'holds a number of its own.\n']);
um_code(fid, sprintf([ ...
    'D = ashuganj_master_data();   %% the whole dataset, from one entry point\n' ...
    '\n' ...
    'D.base.Sbase_MVA   ->  %g          reporting base\n' ...
    'D.base.f_Hz        ->  %g          system frequency\n' ...
    'D.buses            ->  %d bus records\n' ...
    'D.tx               ->  %d transformers\n' ...
    'D.lines            ->  %d branch records\n' ...
    'D.loads            ->  %d load records\n' ...
    'D.cases            ->  %d operating cases'], ...
    D.base.Sbase_MVA, D.base.f_Hz, numel(D.buses), numel(D.tx), ...
    numel(D.lines), numel(D.loads), numel(D.cases)));
w('</li>\n');

w(['<li><b>Check the dataset before it is used.</b> The validation suite ' ...
   'recomputes what can be recomputed &mdash; rated currents from ratings and ' ...
   'voltages, tap spans from tap voltages, impedance conversions between bases ' ...
   '&mdash; and fails if a value contradicts another value. It is run before ' ...
   'the model is built, not after the results look acceptable.\n']);
um_code(fid, 'run_all_tests');
w('</li>\n');

w(['<li><b>Build the network programmatically.</b> One builder per part of the ' ...
   'plant, so that each reads like the corresponding sheet of the single-line ' ...
   'diagram, and one assembler that places them and wires them together.\n']);
bl = dir(fullfile(root, 'matlab', 'build', '*.m'));
txt = '';
for k = 1:numel(bl)
    txt = [txt sprintf('matlab/build/%s\n', bl(k).name)];    %#ok<AGROW>
end
um_code(fid, strtrim(txt));
w('</li>\n');

w(['<li><b>Solve each operating case.</b> Each case is built from the dataset ' ...
   '<i>fresh</i> and then solved. This is not caution for its own sake: the ' ...
   'load flow writes its solution back into the blocks, so a model that has ' ...
   'already been solved is no longer in its as-built state and solving it again ' ...
   'would start from the previous answer.\n']);
um_code(fid, sprintf([ ...
    'run_load_flow_study      %% builds and solves all %d cases in turn\n' ...
    '\n' ...
    '%% inside, per case:\n' ...
    'LF = power_loadflow(sys, ''parameters'');   %% tolerance, iteration limit, base\n' ...
    'LF = power_loadflow(sys, ''solve'', LF);    %% Newton-Raphson solve\n' ...
    'power_loadflow(sys, ''report'');            %% the tool''s own report file'], ...
    numel(D.cases)));
w('</li>\n');

w(['<li><b>Check the solution independently.</b> Convergence is not proof. For ' ...
   'every bus, the injection the solver reports is compared against the sum of ' ...
   'the branch flows rebuilt from the solved voltages <i>outside</i> the ' ...
   'solver. The residual of that comparison is tabulated for every bus in every ' ...
   'case, and it is the column that decides whether the rest of the report is ' ...
   'worth reading.</li>\n']);

w(['<li><b>Extract, tabulate and draw.</b> Buses, branches, transformers and ' ...
   'the generator are written to CSV; the plots and the annotated single-line ' ...
   'diagrams are drawn from those CSVs, never by re-solving, so a figure and a ' ...
   'table cannot disagree.\n']);
um_code(fid, sprintf(['make_load_flow_plots\n' ...
                      'make_annotated_diagrams\n' ...
                      'build_lab_report        %% this document']));
w('</li>\n');
w('</ol>\n');

w(['<p class="note"><b>All of the above is one command.</b> <code>RUN_ME</code> ' ...
   'at the project root runs the whole sequence and needs no arguments and no ' ...
   'path setup. <code>RUN_ME check</code> reports the environment and changes ' ...
   'nothing. The click-by-click procedure for demonstrating the solve ' ...
   'interactively, in front of an audience, is section&nbsp;4 of ' ...
   '<a href="USER_MANUAL.html">USER_MANUAL.html</a>.</p>\n']);
w('</section>\n');

% ================================================================ 6 diagram
w('<section id="r6"><h2>6. Connection diagram</h2>\n');
w(['<p>The diagram below is the model, drawn in the arrangement of the plant''s ' ...
   'own single-line diagram (<code>Single Line Diagram_South.pdf</code>, ' ...
   'drawing <code>INEL-112070-00-ELC-DE-0023</code>) and annotated with the ' ...
   'solved result at every point. It is generated, not drawn: the numbers on it ' ...
   'come from the same CSVs as the tables in section&nbsp;7.</p>\n']);
um_img(fid, ctx.outDir, 'Load_Flow_LF1_Annotated.png', ...
    ['The model in single-line form with the solved case LF1 written onto it ' ...
     '&mdash; rated dispatch, station auxiliary transformer bay open, radial ' ...
     'network.']);
um_img(fid, ctx.outDir, 'Load_Flow_LF2_Annotated.png', ...
    ['The same network with the station auxiliary transformer bay closed (case ' ...
     'LF2). The loop 230 kV - GSUT - 22 kV - UAT - 6.6 kV - GAT - 230 kV is now ' ...
     'complete, and the auxiliary supply divides between the two paths.']);

w('<h3>6.1 The buses in the model</h3>\n');
c1 = ctx.SUM.Case{1};
B  = ctx.BUS(strcmp(ctx.BUS.Case, c1), :);
ctx = lr_cap(fid, ctx, 'Buses represented, with the plant name each one carries');
w(['<table><thead><tr><th>Bus</th><th>Plant designation</th><th>Nominal</th>' ...
   '<th>Type</th></tr></thead><tbody>\n']);
for k = 1:height(B)
    mg = strtrim(B.Merged_into{k});
    ty = B.Type{k};
    if ~isempty(mg)
        ty = sprintf('%s &mdash; solved as one node with <code>%s</code>', ty, mg);
    end
    w('<tr><td class="tag">%s</td><td>%s</td><td>%g kV</td><td>%s</td></tr>\n', ...
      um_esc(B.Bus{k}), um_esc(B.Label{k}), B.Vnom_V(k)/1000, ty);
end
w('</tbody></table>\n');
w(['<p>Where two buses are solved as one node, it is because what joins them ' ...
   'has no impedance to solve across &mdash; a closed breaker, or a connection ' ...
   'whose impedance is not in the document set. To a load flow that is an ' ...
   'identity, not a branch. All of the buses are kept in the table so that ' ...
   'nothing looks overlooked, and the merged ones name the node they belong ' ...
   'to.</p>\n']);

w('<h3>6.2 The branches in the model</h3>\n');
L = ctx.LN(strcmp(ctx.LN.Case, c1), :);
ctx = lr_cap(fid, ctx, 'Branches represented, and what each one is');
w(['<table><thead><tr><th>Branch</th><th>Kind</th><th>From</th><th>To</th>' ...
   '</tr></thead><tbody>\n']);
for k = 1:height(L)
    w('<tr><td>%s</td><td>%s</td><td class="tag">%s</td><td class="tag">%s</td></tr>\n', ...
      um_esc(L.Branch{k}), um_esc(L.Type{k}), um_esc(L.From_bus{k}), um_esc(L.To_bus{k}));
end
w('</tbody></table>\n');
w(['<p class="warn"><b>What is not in the model, and why.</b> The busducts, the ' ...
   'switchgear bays and the 6.6&nbsp;kV feeders carry <b>no impedance</b>, ' ...
   'because none is documented anywhere in the source set. The consequence is ' ...
   'stated rather than buried: this model produces no feeder voltage drop and ' ...
   'no cable loss at all, so the losses it reports are a floor and the real ' ...
   'plant loses slightly more.</p>\n']);
w('</section>\n');
end

% =====================================================================
function s = um_esc_keep(s)
%UM_ESC_KEEP  Escaping for cells that may already contain intended markup.
%   A few of the environment rows are written with <code> tags on purpose. Those
%   must survive; anything read from the installation must be escaped. The test
%   is whether the string already contains a tag this file put there.
if contains(s, '<code>'), return, end
s = um_esc(s);
end

% =====================================================================
function r = doc_role(name)
%DOC_ROLE  What each supplied document is the authority for.
%   Matched on the file name as found on disk, so a document that is renamed or
%   added shows up in the table unexplained rather than silently mislabelled.
switch true
    case contains(name, 'Single Line Diagram')
        r = ['The governing drawing. Network topology, switchgear ' ...
             'arrangement, KKS tags, and which bay connects to what.'];
    case contains(name, 'GENERATION AND TRANSFORMERS')
        r = 'Generation and transformation system description.';
    case contains(name, 'Generator Data')
        r = ['Generator electrical data, and the only origin in the whole ' ...
             'set of the external grid short-circuit figures.'];
    case contains(name, 'Generator Name Plate')
        r = 'Generator nameplate - ratings as built.';
    case contains(name, 'GSUT Data Sheet')
        r = 'Generator step-up transformer data sheet - impedance, losses, taps, cooling stages.';
    case contains(name, 'GSUT Nameplate')
        r = 'Generator step-up transformer nameplate.';
    case contains(name, 'UAT  Data Sheet') || contains(name, 'UAT Data Sheet')
        r = 'Unit auxiliary transformer data sheet.';
    case contains(name, 'UAT Nameplate')
        r = 'Unit auxiliary transformer nameplate.';
    case contains(name, 'Google Sheet Form')
        r = ['Data form completed by APSCL. Its 400 kV entries belong to the ' ...
             'North block and are outside the scope of this study.'];
    case contains(name, 'DE-0001')
        r = 'Drawing and device numbering convention - how every tag in the drawings is read.';
    otherwise
        r = '<i>role not classified by this generator - check before citing</i>';
end
end
