function ctx = lr_part_disc(fid, ctx)
%LR_PART_DISC  Section 9: what each result signifies. Delegates 10-11 to lr_part_next.
%
%   This is the section a reader learns from, so nothing in it is a restatement
%   of a table. Each part takes one number out of section 7, says what physical
%   fact produces it, and says what it would take to make it wrong. The numbers
%   are recomputed here from the CSVs, so the prose cannot drift away from the
%   tables it is discussing.

w  = @(varargin) fprintf(fid, varargin{:});
D  = ctx.D;
c1 = ctx.SUM.Case{1};
S1 = ctx.SUM(strcmp(ctx.SUM.Case, c1), :);

% find the first looped case, by the dataset rather than by name
iLoop = find([D.cases.GAT_in], 1);
if isempty(iLoop), cL = ''; else, cL = D.cases(iLoop).ID; end

w('<section id="r9"><h2>9. What each result signifies</h2>\n');

% ------------------------------------------------------------ 9.1 voltages
w('<h3>9.1 The bus voltages, and why the 230 kV bus sits below 1.0 pu</h3>\n');
B1 = ctx.BUS(strcmp(ctx.BUS.Case, c1), :);
v230 = B1.V_pu(strcmp(B1.Bus, 'B230_1'));
w(['<p>A per-unit voltage is the solved voltage divided by the nominal voltage of ' ...
   'that level, so 1.00&nbsp;pu is nominal and the interesting content of ' ...
   'Table&nbsp;%d is the departure from it. In case&nbsp;%s the 230&nbsp;kV plant ' ...
   'busbar solves at <b>%.5f&nbsp;pu</b> &mdash; below nominal, while the plant is ' ...
   'exporting %.1f&nbsp;MW into it. That reads like a sign error and is not ' ...
   'one.</p>\n'], ctx.t_bus, c1, v230(1), S1.P_export_MW);

Qgrid = -S1.Q_export_MVAr;
w(['<p>The reason is reactive, not active. The plant is <b>absorbing</b> about ' ...
   '%.1f&nbsp;MVAr from the grid at the point of connection at the same time as ' ...
   'it exports real power. Voltage magnitude along a predominantly inductive ' ...
   'path is governed by the reactive flow, and the reactive flow here runs ' ...
   '<i>into</i> the plant. So the plant end of that path sits below the source ' ...
   'end, and it would sit below it even if the real export were larger. Real ' ...
   'power transfer shows up as the angle difference, not as the magnitude ' ...
   'difference &mdash; which is exactly what the angle column of Table&nbsp;%d ' ...
   'shows.</p>\n'], Qgrid, ctx.t_bus);
w(['<p>Where the reactive power goes is the subject of section&nbsp;9.2, and it ' ...
   'is not consumed by the load: the auxiliary load takes only %.1f&nbsp;MVAr of ' ...
   'it.</p>\n'], S1.Q_aux_MVAr);

iU = strcmp(ctx.TX.Case, c1) & contains(ctx.TX.Transformer, 'UAT');
uatd = D.tx(strcmp({D.tx.Name}, 'UAT'));
w(['<p>At the other end of the plant the 6.6&nbsp;kV board solves slightly ' ...
   '<i>above</i> its nominal, at %.5f&nbsp;pu on the 6.6&nbsp;kV system base. ' ...
   'That is the step-up ratio of the auxiliary transformer arriving at a lightly ' ...
   'loaded bus: %.2f&nbsp;MVA flowing through a transformer whose lowest cooling ' ...
   'stage is %g&nbsp;MVA drops very little voltage across %g&nbsp;%% ' ...
   'impedance.</p>\n'], ...
   B1.V_pu(strcmp(B1.Bus, 'B6_6')), ...
   max(ctx.TX.S_LV_MVA(iU), ctx.TX.S_HV_MVA(iU)), ...
   min(uatd.S_MVA), uatd.Z_pct);
w(['<p class="warn"><b>That figure is base-dependent and the base is disputed.</b> ' ...
   'On the 6.9&nbsp;kV winding rating of the transformer that feeds it, the same ' ...
   'solved voltage reads about 4.5&nbsp;%% lower &mdash; below nominal rather ' ...
   'than above it. Nothing in the network changed; only the denominator did. ' ...
   'Until the plant states which figure its own operating limits are written ' ...
   'against, any statement of the form &ldquo;the board runs high&rdquo; or ' ...
   '&ldquo;the board runs low&rdquo; is a statement about the choice of base, ' ...
   'and this report declines to make it.</p>\n']);

% ------------------------------------------------------------ 9.2 reactive
w('<h3>9.2 The reactive balance &mdash; where 60 MVAr goes in a plant with a 8.7 MVAr load</h3>\n');
T1 = ctx.TX(strcmp(ctx.TX.Case, c1), :);
iG = strcmp(ctx.LN.Case, c1) & (strcmp(ctx.LN.From_bus, D.grid.Bus_internal) | ...
                               strcmp(ctx.LN.To_bus,   D.grid.Bus_internal));
Qge = sum(ctx.LN.Q_loss_MVAr(iG));
sup = S1.Q_gen_MVAr + Qgrid;
con = sum(T1.Q_loss_MVAr) + S1.Q_aux_MVAr + Qge;
txt = sprintf(['SUPPLIED\n' ...
               '  generator G1                       %8.4f MVAr\n' ...
               '  drawn from the grid                %8.4f MVAr\n' ...
               '                                     --------\n' ...
               '                                     %8.4f MVAr\n\n' ...
               'CONSUMED\n'], S1.Q_gen_MVAr, Qgrid, sup);
for k = 1:height(T1)
    txt = [txt sprintf('  %-32s %8.4f MVAr\n', T1.Transformer{k}, T1.Q_loss_MVAr(k))]; %#ok<AGROW>
end
txt = [txt sprintf(['  %-32s %8.4f MVAr\n' ...
                    '  %-32s %8.4f MVAr\n' ...
                    '                                     --------\n' ...
                    '                                     %8.4f MVAr\n\n' ...
                    'closure error                        %8.2e MVAr'], ...
       'auxiliary load at 6.6 kV', S1.Q_aux_MVAr, ...
       'grid equivalent series branch', Qge, con, sup - con)];
um_code(fid, txt);
Qgs = T1.Q_loss_MVAr(contains(T1.Transformer, 'GSUT'));
w(['<p>The identity closes. What it says is that the reactive demand of this ' ...
   'plant is overwhelmingly the <b>leakage reactance of the step-up ' ...
   'transformer</b> &mdash; %.1f&nbsp;MVAr of the %.1f&nbsp;MVAr consumed, ' ...
   'against %.1f&nbsp;MVAr for the whole auxiliary load. Pushing %.0f&nbsp;MW ' ...
   'through %g&nbsp;%% reactance costs reactive power in proportion to the ' ...
   '<i>square</i> of the current, and at full output that cost dominates ' ...
   'everything else in the plant.</p>\n'], ...
   Qgs(1), con, S1.Q_aux_MVAr, S1.P_gen_MW, ...
   D.tx(strcmp({D.tx.Name},'GSUT')).Z_pct);
w(['<p>This is why the plant absorbs from the grid rather than supplying. The ' ...
   'generator is dispatched at a fixed terminal voltage, and the reactive output ' ...
   'that this implies (%.1f&nbsp;MVAr) is less than the transformer chain ' ...
   'consumes. The shortfall is made up through the grid connection, and the ' ...
   '230&nbsp;kV bus voltage follows.</p>\n'], S1.Q_gen_MVAr);
w(['<p class="note">Two practical consequences. First, the generator''s reactive ' ...
   'output here is an <i>outcome of the assumed voltage set-point</i>, not an ' ...
   'operating record &mdash; change the set-point and this whole balance moves. ' ...
   'Second, no reactive limit was imposed, so the study cannot yet say whether ' ...
   'the machine is allowed to hold this point; that requires the capability ' ...
   'curve, which is not in the document set.</p>\n']);

% ------------------------------------------------------------ 9.3 loading
w('<h3>9.3 Transformer loading &mdash; and why &ldquo;over 100 %%&rdquo; is not yet an overload</h3>\n');
gs = T1(contains(T1.Transformer, 'GSUT'), :);
gsd = D.tx(strcmp({D.tx.Name}, 'GSUT'));
Sgs = max(gs.S_LV_MVA(1), gs.S_HV_MVA(1));
pcs = strjoin(arrayfun(@(s) sprintf('%.1f&nbsp;%%', 100*Sgs/s), ...
              gsd.S_MVA, 'UniformOutput', false), ', ');
w(['<p>In case&nbsp;%s the step-up transformer carries %.2f&nbsp;MVA. Against ' ...
   'its %d cooling stages that is %s &mdash; the same transformer, the same ' ...
   'flow, %d different answers. This is the reason Table&nbsp;%d reports loading ' ...
   'against every stage rather than one figure.</p>\n'], ...
   c1, Sgs, numel(gsd.S_MVA), pcs, numel(gsd.S_MVA), ctx.t_tx);
w(['<p>A cooling stage is not a rating the transformer has; it is a rating the ' ...
   'transformer has <i>while that cooling equipment is running</i>. %s means ' ...
   'natural convection with no pumps or fans; the higher stages bring oil pumps ' ...
   'and forced air into service. So the honest reading of the red figures in ' ...
   'Table&nbsp;%d is not &ldquo;the transformer is overloaded&rdquo; but ' ...
   '&ldquo;at this output the transformer <b>cannot</b> be in its lowest cooling ' ...
   'stage&rdquo;. Which stage is actually in service at rated output is a ' ...
   'question for the plant, and it is on the list in section&nbsp;11.</p>\n'], ...
   um_esc(gsd.Cooling{1}), ctx.t_tx);
w(['<p class="sl">Loading is measured on whichever of the two windings carries ' ...
   'more, which is always the <i>input</i> winding &mdash; the transformer''s own ' ...
   'losses have not been subtracted from it yet. For the step-up transformer that ' ...
   'is the 22&nbsp;kV side, because power flows upward; for the auxiliary ' ...
   'transformers it is the high-voltage side, because power flows downward into ' ...
   'the board. Taking the output winding instead would understate every loading ' ...
   'figure in the table, and the rule is stated here so that a reader comparing ' ...
   'against another study knows which winding the percentage refers ' ...
   'to.</p>\n']);

% ------------------------------------------------------------ 9.4 circulation
if ~isempty(cL)
    w('<h3>9.4 The principal finding: closing the station transformer bay overloads the unit transformer</h3>\n');
    SL   = ctx.SUM(strcmp(ctx.SUM.Case, cL), :);
    TL   = ctx.TX(strcmp(ctx.TX.Case, cL), :);
    uatd = D.tx(strcmp({D.tx.Name}, 'UAT'));
    bBoard = uatd.Bus_LV;                 % the board, named by the dataset
    rU1  = T1(contains(T1.Transformer, 'UAT'), :);
    rUL  = TL(contains(TL.Transformer, 'UAT'), :);
    rGL  = TL(contains(TL.Transformer, 'GAT'), :);
    [Pu1, ~ ] = board_inject(rU1, bBoard);
    [Pu,  Qu] = board_inject(rUL, bBoard);
    [Pg,  Qg] = board_inject(rGL, bBoard);
    w(['<p>Compare case&nbsp;%s with case&nbsp;%s. The dispatch is identical, the ' ...
       'auxiliary load is identical, and <b>nothing was added to the plant</b> ' ...
       '&mdash; the only difference is that the station auxiliary transformer bay ' ...
       'is closed. The unit auxiliary transformer''s loading rises from ' ...
       '%.2f&nbsp;%% to <b>%.2f&nbsp;%%</b> of its %g&nbsp;MVA natural-cooling ' ...
       'stage. Where the extra loading comes from is worth following ' ...
       'carefully, because it is not load.</p>\n'], c1, cL, ...
       rU1.Loading_pct_lowest_stage, rUL.Loading_pct_lowest_stage, min(uatd.S_MVA));
    um_code(fid, sprintf([ ...
        'case %s  -  station transformer bay CLOSED\n' ...
        'sign convention: POSITIVE = delivered INTO the 6.6 kV board\n\n' ...
        '                                     P (MW)     Q (MVAr)\n' ...
        '  from the UAT   (generator side)  %9.3f    %9.3f\n' ...
        '  from the GAT   (grid side)       %9.3f    %9.3f\n' ...
        '                                   ---------    ---------\n' ...
        '  net into the board               %9.3f    %9.3f\n' ...
        '  consumed by the board            %9.3f    %9.3f\n' ...
        '  closure                          %9.1e    %9.1e\n\n' ...
        'so the UAT carries %.3f MW in order to serve a %.3f MW load,\n' ...
        'and %.3f MW goes straight back out again through the GAT.'], ...
        cL, Pu, Qu, Pg, Qg, Pu+Pg, Qu+Qg, SL.P_aux_MW, SL.Q_aux_MVAr, ...
        Pu+Pg-SL.P_aux_MW, Qu+Qg-SL.Q_aux_MVAr, Pu, SL.P_aux_MW, -Pg));
    w(['<p>Read the second row again: the station transformer''s contribution to ' ...
       'the board is <b>negative in real power</b>. It is not helping to feed the ' ...
       'board at all &mdash; it is taking %.3f&nbsp;MW <i>out</i> of the board and ' ...
       'returning it to the 230&nbsp;kV busbar. The same %.3f&nbsp;MW had to be ' ...
       'pushed into the board by the unit transformer first, so it makes two ' ...
       'transformer crossings and does no work at either end.</p>\n'], -Pg, -Pg);
    w(['<p>This is what closing the bay does. The network now contains a loop ' ...
       '&mdash; 230&nbsp;kV &rarr; GSUT &rarr; 22&nbsp;kV &rarr; UAT &rarr; ' ...
       '6.6&nbsp;kV &rarr; GAT &rarr; 230&nbsp;kV &mdash; and the two paths ' ...
       'around it have different impedances and different transformation ratios. ' ...
       'A closed loop of unequal branches circulates power whether or not anybody ' ...
       'intends it to, and the division follows the impedances rather than the ' ...
       'load. The unit transformer''s real throughput rises from %.3f&nbsp;MW to ' ...
       '%.3f&nbsp;MW &mdash; %.0f&nbsp;%% more &mdash; while the load it is ' ...
       'serving does not change at all.</p>\n'], Pu1, Pu, 100*(Pu-Pu1)/Pu1);
    w(['<p class="warn"><b>Why this matters beyond the loading figure.</b> A ' ...
       'circulating current is real current. It heats both transformers, it ' ...
       'consumes reactive power in both, and it is seen by every relay measuring ' ...
       'either branch. An overcurrent setting graded on the radial case would see ' ...
       'the unit transformer carrying %.0f&nbsp;%% more real power than it was ' ...
       'graded for, in a configuration involving no fault and no extra load. This ' ...
       'is the one result of the load flow with a direct consequence for the ' ...
       'protection stage, and it is the reason both topologies were carried ' ...
       'through the study rather than one being chosen.</p>\n'], ...
       100*(Pu-Pu1)/Pu1);
    w(['<p class="note">The report does <b>not</b> claim the plant runs this way. ' ...
       'Whether the bay is closed during normal running is not stated in the ' ...
       'document set; that is precisely why it is a case rather than a setting. ' ...
       'What the study establishes is that the answer matters, and by how ' ...
       'much.</p>\n']);
end

ctx = lr_part_disc2(fid, ctx);
end

% =====================================================================
function [P, Q] = board_inject(r, bus)
%BOARD_INJECT  Real and reactive power delivered INTO a named bus by a branch.
%   Every P/Q column of transformer_results.csv is measured in the From_bus to
%   To_bus direction, so the sign depends on which end the bus of interest is.
%   At the From end a positive column value means power leaving the bus, so the
%   injection is the negative of it; at the To end the column value is already
%   the power arriving. Reading the side from the record rather than assuming it
%   keeps the arithmetic correct if a From/To pair is ever swapped upstream.
P = NaN; Q = NaN;
if isempty(r), return, end
fb = pick(r.From_bus);
tb = pick(r.To_bus);
if strcmp(fb, bus)
    P = -r.P_LV_MW(1);   Q = -r.Q_LV_MVAr(1);
elseif strcmp(tb, bus)
    P =  r.P_HV_MW(1);   Q =  r.Q_HV_MVAr(1);
end
end

% ---------------------------------------------------------------------
function s = pick(c)
%PICK  First entry of a table text column, whether cellstr, string or char.
if iscell(c),    s = c{1};
elseif isstring(c), s = char(c(1));
else,            s = char(c);
end
end
