function ctx = lr_part_next2(fid, ctx)
%LR_PART_NEXT2  Section 11, second half: the study sequence, and what is ready.

w = @(varargin) fprintf(fid, varargin{:});
D = ctx.D;
g = D.gen(1);

% ------------------------------------------------------------ 11.3 sequence
w('<h3>11.3 The studies that follow, in order</h3>\n');
w(['<p>The order is not a preference. Each stage needs the operating point the ' ...
   'previous one establishes, and each needs inputs that the collection list ' ...
   'above has to supply first.</p>\n']);

w('<ol class="steps">\n');

w(['<li><b>Three-phase short-circuit study.</b> Fault levels at the ' ...
   '230&nbsp;kV busbar, the 22&nbsp;kV generator bus and the 6.6&nbsp;kV boards, ' ...
   'and a breaker duty check against the ratings already in the dataset &mdash; ' ...
   '50&nbsp;kA for one second and 125&nbsp;kA peak on the 230&nbsp;kV ' ...
   'switchgear.\n']);
w(['<p><i>Needs:</i> item&nbsp;1, the utility fault level. That is the only ' ...
   'genuinely missing input; the generator subtransient reactance ' ...
   '(%.2f&nbsp;%%) and every transformer impedance are already in the dataset ' ...
   'with their sources recorded. <i>Undoes:</i> nothing structural &mdash; a ' ...
   'balanced three-phase fault uses the same positive-sequence network this ' ...
   'study already contains.</p></li>\n'], g.xdpp_pct);

w(['<li><b>Unbalanced fault analysis</b> &mdash; single line to ground, line to ' ...
   'line, and double line to ground.\n']);
w(['<p><i>Needs:</i> item&nbsp;11, confirmation of the zero-sequence data and the ' ...
   'neutral earthing resistor. <i>Undoes:</i> three of the structural ' ...
   'simplifications listed in&nbsp;11.2, and this is where they stop being ' ...
   'harmless. The neutral earthing resistor carries no balanced current and was ' ...
   'omitted &mdash; in an earth fault it is the element that <i>limits the fault ' ...
   'current</i>, so it must be modelled. The delta tertiary of the station ' ...
   'transformer was omitted for the same reason and becomes a zero-sequence path ' ...
   'that has to be represented. The transformer zero-sequence impedances are ' ...
   'already carried in the dataset, unused, for exactly this ' ...
   'stage.</p></li>\n']);

w(['<li><b>Protection coordination.</b> The stated objective of the project: ' ...
   'grading the overcurrent and earth-fault elements, differential protection of ' ...
   'the generator and the transformers, and time-current curves that clear a ' ...
   'fault without tripping on load.\n']);
w(['<p><i>Needs:</i> item&nbsp;9, the current transformer ratios and the relay ' ...
   'data, and the fault currents from the two stages above. <i>Uses this report ' ...
   'directly:</i> the load currents in Table&nbsp;%d are the currents the ' ...
   'settings must <b>not</b> operate on, and they are the reason a load flow ' ...
   'comes first. The finding in section&nbsp;9.4 belongs here too &mdash; a ' ...
   'setting graded on the radial case would see materially more current in the ' ...
   'unit auxiliary transformer as soon as the station transformer bay is ' ...
   'closed, with no fault present.</p></li>\n'], ctx.t_tx);

w(['<li><b>Transient stability</b>, if the project extends that far.\n']);
w(['<p><i>Needs:</i> item&nbsp;10 &mdash; the inertia constant, the quadrature ' ...
   'reactance, the open-circuit time constants, and governor and exciter models, ' ...
   'none of which is in the document set. The single-shaft arrangement matters ' ...
   'here in a way it does not in a load flow: one shaft carries both turbines and ' ...
   'the generator, so there is one inertia and one swing equation rather than ' ...
   'two machines to synchronise.</p></li>\n']);
w('</ol>\n');

w(['<p class="warn"><b>Each of those stages must be run on a solved operating ' ...
   'point, not on nameplate ratings.</b> Fault current depends on the pre-fault ' ...
   'voltage profile; relay grading depends on the load current the relay sees in ' ...
   'normal running. Both come from a load flow. Running the fault study first ' ...
   'would produce numbers to four figures that were wrong in the first, and ' ...
   'nothing in the output would say so &mdash; which is why this stage was ' ...
   'completed and documented before any of the rest was attempted.</p>\n']);

% ------------------------------------------------------------ 11.4 in place
w('<h3>11.4 What the next stage inherits</h3>\n');
w(['<p>The work already done is not only this report. What carries forward to ' ...
   'the stages above:</p>\n']);
w('<ul>\n');
have = { ...
 sprintf(['A <b>dataset</b> in which every parameter carries its source ' ...
          'document, page, status and confidence &mdash; %d bus records, ' ...
          '%d transformers, %d branches, %d loads. A fault study starts from ' ...
          'verified machine and transformer data instead of a fresh search.'], ...
          numel(D.buses), numel(D.tx), numel(D.lines), numel(D.loads))
 ['A network that is <b>generated from that dataset by script</b>. A parameter ' ...
  'changes in one place and the diagram, the solution, every table and every ' ...
  'figure follow. Nothing has to be re-drawn by hand for the next study.']
 sprintf(['A <b>case matrix</b> and the machinery to solve it &mdash; %d cases ' ...
          'built fresh and solved in sequence. Adding a fault case is adding a ' ...
          'row, not writing a new study.'], numel(D.cases))
 ['An <b>independent check</b> that does not trust the solver: the power balance ' ...
  'at every bus rebuilt from the solved voltages outside it. The same harness ' ...
  'checks a fault study.']
 ['A <b>validation suite</b> that recomputes what can be recomputed from the ' ...
  'nameplates and fails on a contradiction, run before the model is built rather ' ...
  'than after the results look acceptable.']
 sprintf(['Machine reactances (x_d %.2f&nbsp;%%, x_d&prime; %.2f&nbsp;%%, ' ...
          'x_d&Prime; %.2f&nbsp;%%) and transformer zero-sequence impedances ' ...
          'already captured with their sources, unused by this study and ' ...
          'required by the next two.'], g.xd_pct, g.xdp_pct, g.xdpp_pct)
 ['A <b>written record of every gap</b>: what is missing, what is assumed, what ' ...
  'is estimated, what two documents disagree about, and what was simplified. ' ...
  'None of it has to be rediscovered, and none of it is hidden in order to make a ' ...
  'result look finished.'] };
for k = 1:numel(have), w('<li>%s</li>\n', have{k}); end
w('</ul>\n');

w(['<p class="note"><b>The single next action</b> is item&nbsp;1 of&nbsp;11.1: ' ...
   'obtain the three-phase and single-phase short-circuit level at the ' ...
   '230&nbsp;kV Ashuganj busbar from PGCB, with X/R. It is the only input the ' ...
   'short-circuit stage lacks, it is the weakest number in the present model, and ' ...
   'it is the parameter every 230&nbsp;kV protection setting will ultimately rest ' ...
   'on.</p>\n']);
w('</section>\n');
end
