function s = ashuganj_html_css()
%ASHUGANJ_HTML_CSS  The stylesheet shared by every generated HTML deliverable.
%
%   Kept in one place so the project update and the user manual cannot drift
%   apart visually. Both pages are meant to be handed over as one set, and two
%   documents in the same folder that look like they came from different projects
%   is a presentation defect.
%
%   A NOTE ON PERCENT SIGNS
%   -----------------------
%   This function RETURNS a string; the caller prints it through a '%s'. An
%   argument substituted through %s is never rescanned for format escapes, so
%   every '%' below is a single '%'. Doubling them would put a doubled percent on
%   the page - which is exactly the bug that reached the rendered CSS once
%   already.

s = [ ...
'*{box-sizing:border-box}' newline ...
'body{margin:0;font:15px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;' newline ...
'  color:#1a1a1a;background:#fff;-webkit-font-smoothing:antialiased}' newline ...
'header,nav,section,footer{max-width:1000px;margin:0 auto;padding:0 32px}' newline ...
'header{padding-top:56px;padding-bottom:32px;border-bottom:3px solid #1a1a1a}' newline ...
'.course{font-size:12px;letter-spacing:.09em;text-transform:uppercase;color:#666;font-weight:600}' newline ...
'h1{font-size:31px;line-height:1.25;margin:14px 0 12px;font-weight:700;letter-spacing:-.015em}' newline ...
'.sub{font-size:17px;color:#333}' newline ...
'.meta{font-size:12.5px;color:#777;margin-top:10px;font-variant-numeric:tabular-nums}' newline ...
'nav{margin:32px auto;padding:20px 32px;background:#f7f7f5;border-radius:6px}' newline ...
'nav b{font-size:12px;letter-spacing:.09em;text-transform:uppercase;color:#666}' newline ...
'nav ol{margin:10px 0 0;padding-left:22px;columns:2;column-gap:36px}' newline ...
'nav li{margin:3px 0}' newline ...
'nav a{color:#1a1a1a;text-decoration:none;border-bottom:1px solid #ccc}' newline ...
'nav a:hover{border-bottom-color:#1a1a1a}' newline ...
'section{padding-top:40px;padding-bottom:8px}' newline ...
'h2{font-size:23px;margin:0 0 18px;padding-bottom:9px;border-bottom:2px solid #e0e0dc;font-weight:700;letter-spacing:-.01em}' newline ...
'h3{font-size:16.5px;margin:30px 0 9px;font-weight:650}' newline ...
'h4{font-size:14.5px;margin:22px 0 6px;font-weight:650}' newline ...
'p{margin:11px 0}' newline ...
'.why{color:#666;font-size:14px;margin:4px 0 12px}' newline ...
'code{font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:#f2f2ef;' newline ...
'  padding:1.5px 5px;border-radius:3px}' newline ...
'pre.code{background:#1c1c1a;color:#e8e8e3;padding:16px 20px;border-radius:6px;overflow-x:auto;' newline ...
'  font:13px/1.7 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;margin:12px 0}' newline ...
'table{width:100%;border-collapse:collapse;margin:14px 0;font-size:13.5px}' newline ...
'th{text-align:left;font-weight:650;padding:8px 11px;background:#f2f2ef;border-bottom:2px solid #d8d8d3;' newline ...
'  font-size:12px;letter-spacing:.03em}' newline ...
'td{padding:8px 11px;border-bottom:1px solid #ecece8;vertical-align:top}' newline ...
'tr:last-child td{border-bottom:none}' newline ...
'table.num td,table.num th{text-align:right;font-variant-numeric:tabular-nums}' newline ...
'table.num td:first-child,table.num th:first-child,' newline ...
'table.num td:nth-child(2),table.num th:nth-child(2){text-align:left}' newline ...
'table.files td:first-child{width:38%;white-space:nowrap}' newline ...
'td.tag{font:12.5px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;white-space:nowrap}' newline ...
'td.bad{color:#a81b1b;font-weight:700}' newline ...
'.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}' newline ...
'.card{background:#f7f7f5;border-radius:6px;padding:15px 16px}' newline ...
'.cl{font-size:11px;letter-spacing:.07em;text-transform:uppercase;color:#777;font-weight:650}' newline ...
'.cv{font-size:22px;font-weight:700;margin:5px 0 3px;letter-spacing:-.02em;font-variant-numeric:tabular-nums}' newline ...
'.cn{font-size:12px;color:#666;line-height:1.45}' newline ...
'p.note{background:#f7f7f5;border-left:3px solid #b8b8b0;padding:12px 16px;border-radius:0 4px 4px 0;font-size:13.5px}' newline ...
'p.warn{background:#fdf6ec;border-left:3px solid #d99b3d;padding:12px 16px;border-radius:0 4px 4px 0;font-size:13.5px}' newline ...
'ol,ul{margin:11px 0;padding-left:24px}' newline ...
'li{margin:5px 0}' newline ...
'figure{margin:20px 0}' newline ...
'figure img{width:100%;display:block;border:1px solid #e0e0dc;border-radius:5px;background:#fff}' newline ...
'figcaption{font-size:12.5px;color:#666;margin-top:8px;line-height:1.5}' newline ...
'.grid2{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin:18px 0}' newline ...
'.grid2 figure{margin:0}' newline ...
'.snip{margin:20px 0}' newline ...
'.sh{display:flex;justify-content:space-between;align-items:baseline;gap:18px;margin-bottom:6px}' newline ...
'.sh span{font-size:12.5px;color:#666;text-align:right}' newline ...
'.sl{font-size:11.5px;color:#999;margin-top:5px;font-variant-numeric:tabular-nums}' newline ...
'ol.steps{padding-left:0;list-style:none;counter-reset:st}' newline ...
'ol.steps>li{counter-increment:st;position:relative;padding:0 0 4px 42px;margin:20px 0}' newline ...
'ol.steps>li:before{content:counter(st);position:absolute;left:0;top:-1px;width:28px;height:28px;' newline ...
'  border-radius:50%;background:#1a1a1a;color:#fff;font-size:13px;font-weight:700;' newline ...
'  display:flex;align-items:center;justify-content:center}' newline ...
'ol.steps>li>b:first-child{display:block;margin-bottom:2px}' newline ...
'.cards2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:18px 0}' newline ...
'.box{border:1px solid #e0e0dc;border-radius:6px;padding:16px 18px}' newline ...
'.box h4{margin-top:0}' newline ...
'footer{margin-top:52px;padding-top:22px;padding-bottom:52px;border-top:2px solid #e0e0dc;' newline ...
'  color:#777;font-size:12.5px}' newline ...
'@media print{nav{break-after:page}section{break-inside:avoid-page}' newline ...
'  figure,.snip,table{break-inside:avoid}}' newline ...
'@media(max-width:820px){.grid4{grid-template-columns:repeat(2,1fr)}nav ol{columns:1}' newline ...
'  .grid2,.cards2{grid-template-columns:1fr}}' newline];
end
