function build_project_update(varargin)
%BUILD_PROJECT_UPDATE  Write docs/manual/PROJECT_UPDATE.html - the presentation.
%
%   BUILD_PROJECT_UPDATE                 write the HTML
%   BUILD_PROJECT_UPDATE('Solve', false) use the CSVs already in results/
%
%   WHAT THIS IS FOR
%   ----------------
%   One self-contained HTML file to present the project as it stands: what the
%   model is, how to run it, what every MATLAB file and every Simulink block
%   does, what the load flow found, and what is still open. It is a project
%   UPDATE, not a lab report - the audience is the group and the course teacher,
%   and the question it answers is "where are we and what is left".
%
%   WHY IT IS GENERATED AND NOT HAND-WRITTEN
%   ----------------------------------------
%   Every number in it is read from results/load_flow/*.csv, which is written by
%   run_load_flow_study. A hand-written page would start drifting from the
%   dataset the first time a parameter changed. Nothing here is retyped.
%
%   The one thing this file may NOT do is invent a number. If a CSV is missing a
%   column the page says so; it does not fill the gap.

p = inputParser;
p.addParameter('Solve', false, @islogical);
p.parse(varargin{:});
opt = p.Results;

root = ashuganj_root();
lfDir = fullfile(root, 'results', 'load_flow');
outDir = fullfile(root, 'docs', 'manual');
if ~exist(outDir, 'dir'), mkdir(outDir); end

if opt.Solve
    run_load_flow_study();
end

sumFile = fullfile(lfDir, 'system_summary.csv');
if ~exist(sumFile, 'file')
    error('build_project_update:noResults', ...
        ['results/load_flow/system_summary.csv does not exist. Run ' ...
         'run_load_flow_study first, or call this with (''Solve'', true).']);
end
SUM = readtable(sumFile);
TX  = readtable(fullfile(lfDir, 'transformer_results.csv'));
BUS = readtable(fullfile(lfDir, 'bus_results.csv'));
GEN = readtable(fullfile(lfDir, 'generator_results.csv'));
D   = ashuganj_master_data();

% ---- figures are COPIED beside the HTML, not linked across the tree --------
% docs/manual/ then survives being zipped, emailed or opened on another PC with
% no MATLAB and no project folder. A figure that has not been generated yet is
% reported as absent on the page; it is never faked or silently omitted.
srcFigs = { fullfile(root,'results','diagrams','Load_Flow_LF1_Annotated.png')
            fullfile(root,'results','diagrams','Load_Flow_LF2_Annotated.png')
            fullfile(root,'results','plots','power_balance.png')
            fullfile(root,'results','plots','bus_voltage_profile.png')
            fullfile(root,'results','plots','transformer_loading.png')
            fullfile(root,'results','plots','line_loading.png') };
for k = 1:numel(srcFigs)
    if exist(srcFigs{k}, 'file')
        [~, nm, ex] = fileparts(srcFigs{k});
        copyfile(srcFigs{k}, fullfile(outDir, [nm ex]));
    end
end

out = fullfile(outDir, 'PROJECT_UPDATE.html');
fid = fopen(out, 'w');
if fid < 0, error('build_project_update:open', 'Cannot write %s', out); end
c = onCleanup(@() fclose(fid));

w = @(varargin) fprintf(fid, varargin{:});

% ===================================================================== head
w('<!DOCTYPE html>\n<html lang="en"><head>\n');
w('<meta charset="utf-8">\n');
w('<meta name="viewport" content="width=device-width, initial-scale=1">\n');
w('<title>Ashuganj South - Load Flow Model - Project Update</title>\n');
w('<style>\n%s</style>\n', css());
w('</head>\n<body>\n');

% ===================================================================== title
w('<header>\n');
w('<div class="course">EEE 306 &middot; Power System I Laboratory &middot; January 2026 &middot; Group-03, Section C-1</div>\n');
w('<h1>Protection Coordination and Fault Analysis of the<br>Ashuganj 450 MW Combined Cycle Power Plant (South)</h1>\n');
w('<div class="sub">Project update &mdash; <b>Stage 1 of 3: balanced steady-state load flow</b></div>\n');
w('<div class="meta">Model: MATLAB R2024a &middot; Simulink 24.1 &middot; Simscape Electrical (Specialized Power Systems) &middot; 50 Hz &middot; %g MVA base</div>\n', ...
  D.base.Sbase_MVA);
w('</header>\n');

% ===================================================================== nav
w('<nav><b>Contents</b><ol>\n');
navs = { '1. Where the project stands', 's1'
         '2. What the model represents', 's2'
         '3. How to run it', 's3'
         '4. The Simulink model, block by block', 's4'
         '5. The MATLAB code, file by file', 's5'
         '6. Key code, and what each piece does', 's6'
         '7. Load flow results', 's7'
         '8. What the results mean', 's8'
         '9. Assumptions and missing data', 's9'
         '10. What remains', 's10'
         '11. Complete file map', 's11' };
for k = 1:size(navs,1)
    w('<li><a href="#%s">%s</a></li>\n', navs{k,2}, navs{k,1});
end
w('</ol></nav>\n');

% ================================================================== 1 status
w('<section id="s1"><h2>1. Where the project stands</h2>\n');
w('<p>The plant''s electrical single-line diagram has been rebuilt as a working Simulink model and a balanced load flow has been solved on it. Four operating cases converge and cross-check. Nothing about faults or protection has been attempted yet &mdash; that is the next stage, and this stage is its input.</p>\n');
w('<div class="grid4">\n');
% Counted, not typed. The block tally is the model's actual composition read off
% the dataset - three transformers, however many modelled load groups the
% register carries, the generator, the grid source and its series impedance, the
% two switching devices and powergui - so it cannot drift when the register does.
nLoads = sum([D.loads.Model_included]);
nBlocks = numel(D.tx) + nLoads + 1 + 1 + 1 + 2 + 1;
nTestFiles = numel(dir(fullfile(root, 'matlab', 'tests', 'test_*.m')));
card(fid, 'Model', sprintf('%d blocks', nBlocks), 'one-line layout matched to drawing DE-0001 Rev 03');
card(fid, 'Cases solved', sprintf('%d of %d', sum(strcmp(SUM.Checks,'OK')), height(SUM)), ...
     sprintf('all converged in %d iterations', max(SUM.Iterations)));
card(fid, 'Validation', sprintf('%d test files', nTestFiles), 'dataset consistency plus solved-network checks');
card(fid, 'Worst KCL error', sprintf('%.0e MVA', max(SUM.Worst_KCL_residual_MVA)), 'flows rebuilt outside the solver and compared');
w('</div>\n');
w(['<p class="note"><b>Stage plan.</b> (1) <b>Load flow &mdash; done, this document.</b> ' ...
   '(2) Short-circuit study: three-phase, single-line-to-ground, line-to-line, ' ...
   'double-line-to-ground. (3) Protection coordination and relay settings. ' ...
   'Stages 2 and 3 need data the load flow does not &mdash; listed in &sect;9.</p>\n']);
w('</section>\n');

% ================================================================ 2 what
w('<section id="s2"><h2>2. What the model represents</h2>\n');
w(['<p>Ashuganj South is a <b>single-shaft</b> combined cycle unit: a Siemens ' ...
   'SCC5-PAC 4000F/3000 (1S) train &mdash; one SGT5-4000F gas turbine and one ' ...
   'SST-3000 steam turbine on a common shaft, driving <b>one</b> 458 MVA ' ...
   'generator. That is why a "450 MW" plant has a single machine on the ' ...
   'diagram rather than three.</p>\n']);
w(['<p>Power leaves at 22 kV, steps up through the generator step-up ' ...
   'transformer to the 230 kV switchyard, and exports to the PGCB grid. ' ...
   'The unit''s own auxiliaries &mdash; pumps, fans, water intake &mdash; ' ...
   'are fed at 6.6 kV from the unit auxiliary transformer, with a station ' ...
   'auxiliary transformer from 230 kV as the alternative supply.</p>\n']);
w('<table><thead><tr><th>Equipment</th><th>Tag</th><th>Rating</th><th>Data status</th></tr></thead><tbody>\n');
rows = { 'Generator G1',                '10MKA10', '458 MVA, 22 kV, pf 0.85',                     'nameplate'
         'Generator step-up (GSUT)',    '10BAT10', '230/22 kV, 355/460/515 MVA, YNd1, Z 16 %',    'nameplate'
         'Unit auxiliary (UAT)',        '10BBT10', '22/6.9 kV, 19/25 MVA, Dyn11, Z 10.5 %',       'nameplate'
         'Station auxiliary (GAT)',     '10BBT20', '230/6.9 kV, 19/25 MVA, YNyn0+d11, Z 12 %',    'nameplate'
         '230 kV switchgear',           '8DN9',    'GIS, 3150 A bus-coupler/busbar module (bays 2000 A), 50 kA / 1 s+3 s, 125 kA peak equipment ratings, double busbar',     'nameplate'
         '6.6 kV auxiliary load',       '10BBA10', '14.000 MW / 8.676 MVAr at pf 0.85',           'total documented, split assumed'
         'External grid',               '&mdash;', '230 kV, Z = j2.6558 &Omega;',                 'ESTIMATED Siemens §2.4 50 kA source quantity (equipment ratings separate)' };
for k = 1:size(rows,1)
    w('<tr><td>%s</td><td class="tag">%s</td><td>%s</td><td>%s</td></tr>\n', rows{k,:});
end
w('</tbody></table>\n');
w(['<p class="note"><b>South only.</b> Ashuganj North is a different project ' ...
   '(400 kV GIS, separate interbus transformers) and is not in this model. ' ...
   'The highest voltage here is <b>230 kV</b>. Any 400 kV data in the source ' ...
   'documents belongs to North and was deliberately left out.</p>\n']);
w('</section>\n');

% ================================================================ 3 how to run
w('<section id="s3"><h2>3. How to run it</h2>\n');
w('<p>Everything is scripted. Nothing has to be dragged or wired by hand.</p>\n');
w('<h3>The short version</h3>\n');
w('<p>Open MATLAB, change to the <code>matlab</code> folder of the project, and run:</p>\n');
% Single '%' here, not '%%'. This text is an ARGUMENT to code(), which prints it
% through a %s - so it is never rescanned for format escapes, and a doubled
% percent would reach the page as a doubled percent.
code(fid, ['ashuganj_setup();          % puts every project folder on the path' newline ...
           'run_load_flow_study();     % solves all four cases, writes every table']);
w(['<p>That single call builds the model from the dataset four times, solves ' ...
   'each case, cross-checks the answers, writes the CSVs to ' ...
   '<code>results/load_flow/</code>, and saves the Simulink files. It takes ' ...
   'about a minute.</p>\n']);
w('<h3>To look at the diagram</h3>\n');
code(fid, ['open(''simulink/main/Ashuganj_South_Main.slx'')' newline newline ...
           '% To solve it interactively instead:' newline ...
           '%   double-click the powergui block (top-left)' newline ...
           '%   choose Load Flow' newline ...
           '%   press Compute']);
w('<h3>Every entry point</h3>\n');
w('<table><thead><tr><th>Command</th><th>What it does</th><th>Time</th></tr></thead><tbody>\n');
cmds = { 'ashuganj_setup()',                  'Sets the MATLAB path. Must be first, every session.', '&lt;1 s'
         'run_load_flow_study()',             'The main driver: solve all four cases, write all tables and models.', '~60 s'
         'run_all_tests()',                   'The full validation suite, 447 checks.', '~3 min'
         'run_all_tests(''data'')',           'Dataset checks only, no solver.', '~2 s'
         'run_build()',                       'Build the diagram and compile-check it, without solving.', '~20 s'
         'make_annotated_diagrams()',         'The presentation copy: the one-line with solved flows written on it.', '~90 s'
         'make_load_flow_plots()',            'The result figures, drawn from the CSVs.', '~10 s'
         'build_project_update()',            'Regenerates this document from the current results.', '~5 s' };
for k = 1:size(cmds,1)
    w('<tr><td><code>%s</code></td><td>%s</td><td>%s</td></tr>\n', cmds{k,:});
end
w('</tbody></table>\n');

w('<h3>Demonstrating it to someone else</h3>\n');
w(['<p>Order to follow if the model is being shown live, and what to say at ' ...
   'each step. Nothing here needs anything typed except step&nbsp;1.</p>\n']);
w('<table><thead><tr><th>Step</th><th>What to do</th><th>What is on screen</th></tr></thead><tbody>\n');
demo = { '1', 'In MATLAB, <code>cd</code> to the project''s <code>matlab</code> folder and run <code>ashuganj_setup()</code>.', 'A confirmation of the path and the MATLAB version. Nothing visual yet.'
         '2', 'Run <code>run_load_flow_study()</code> and let it print.', 'The four cases solving one after another, each printing its dispatch, its convergence and its cross-check verdict. This is the evidence that the study runs end to end.'
         '3', 'Open <code>simulink/main/Ashuganj_South_Main.slx</code>.', 'The one-line diagram, laid out to match the plant drawing. Put the plant drawing beside it &mdash; the columns and tiers correspond.'
         '4', 'Double-click <b>powergui</b>, choose <b>Load Flow</b>, press <b>Compute</b>.', 'The solver''s own bus table, produced by Simulink rather than by our scripts. Useful precisely because it is not our code.'
         '5', 'Open <code>simulink/studies/Load_Flow_LF1_Annotated.slx</code>.', 'The same diagram with the solved flows, voltages and loading written onto every element. This is the sheet to present.'
         '6', 'Show <code>results/load_flow/system_summary.csv</code>.', 'One row per case: generation, auxiliary demand, losses, export, iterations, cross-check verdict.'
         '7', 'Show this page.', 'The findings and what is still missing.' };
for k = 1:size(demo,1)
    w('<tr><td class="tag">%s</td><td>%s</td><td>%s</td></tr>\n', demo{k,:});
end
w('</tbody></table>\n');
w(['<p class="note"><b>If something does not run.</b> Almost every failure is ' ...
   'the path: <code>ashuganj_setup()</code> has to be run once per MATLAB ' ...
   'session, before anything else. The second most likely cause is a stale ' ...
   'model left open &mdash; <code>bdclose(''all'')</code> clears it. The study ' ...
   'closes each model itself, so no manual cleanup is normally needed.</p>\n']);
w('</section>\n');

% ================================================================ 4 simulink
w('<section id="s4"><h2>4. The Simulink model, block by block</h2>\n');
w(['<p>%d blocks in total. The layout copies drawing DE-0001 Rev 03 so the two ' ...
   'sheets can be laid side by side and checked element by element: generator ' ...
   'at the bottom of the left column, step-up transformer directly above it, ' ...
   'auxiliary transformer in its own column to the right, switchyard across ' ...
   'the top. Colour carries voltage level &mdash; red 230 kV, orange 22 kV, ' ...
   'blue 6.6 kV.</p>\n'], nBlocks);
img(fid, outDir, 'Load_Flow_LF1_Annotated.png', ...
    ['The model at case LF1, with the solved result written onto each element. ' ...
     'Generated by make_annotated_diagrams() straight from the solved network, ' ...
     'so the numbers on the sheet and the numbers in &sect;7 are the same numbers. ' ...
     'The other three cases are in results/diagrams/ as separate sheets.']);
w('<table><thead><tr><th>Block on the diagram</th><th>Simulink block used</th><th>Why that block, and what it stands for</th></tr></thead><tbody>\n');
blk = { 'G1 10MKA10',      'Three-Phase Source (PV)', ...
        ['The generator. An <b>ideal</b> source on PV control, not the synchronous machine ' ...
         'block. The machine block would additionally need x<sub>q</sub>, armature resistance, ' ...
         'inertia and four time constants, none of which is in the source documents &mdash; ' ...
         'and a balanced load flow uses none of them. A PV bus is fully specified by |V| and P.']
        'GSUT 10BAT10',    'Three-Phase Transformer (Two Windings)', ...
        ['Generator step-up, 230/22 kV YNd1. Impedance, resistance, iron loss and ' ...
         'magnetising current all come from the nameplate; the tap is on the principal ' ...
         'position 9 of 25.']
        'UAT 10BBT10',     'Three-Phase Transformer (Two Windings)', ...
        'Unit auxiliary, 22/6.9 kV Dyn11. Normal supply to the 6.6 kV auxiliary board.'
        'GAT 10BBT20',     'Three-Phase Transformer (Two Windings)', ...
        ['Station auxiliary, 230/6.9 kV. The real unit has a third 3.32 kV delta winding, ' ...
         'but only its two-winding positive-sequence impedance is documented, so it is ' ...
         'modelled with two windings and the tertiary is noted as omitted rather than ' ...
         'given invented data.']
        '10BAY12 COUPLER', 'Three-Phase Breaker', ...
        'The GIS bus coupler between 230 kV BUS 1 and BUS 2. Closed in all four cases.'
        '10BAY20 CB',      'Three-Phase Breaker', ...
        'The station auxiliary transformer''s 230 kV bay breaker. This is the switch the case matrix opens and closes.'
        'EXT GRID',        'Three-Phase Source (swing)', ...
        ['The PGCB grid, represented at the plant boundary as the swing bus &mdash; it ' ...
         'absorbs whatever the plant exports and sets the system reference angle.']
        'ZGRID',           'Three-Phase Series RLC Branch', ...
        ['The grid''s source impedance, kept as a <b>separate visible block</b> rather than ' ...
         'hidden inside the source, because it is the one estimated impedance in the model ' ...
         'and it should be visible as such.']
        'LOAD_B6_6 &times;3', 'Three-Phase Parallel RLC Load', ...
        'The three 6.6 kV auxiliary groups: main board, and two water-intake motor groups.'
        'powergui',        'Environment block', ...
        ['Not plant equipment &mdash; it is the solver, and the button you press to run the ' ...
         'load flow. Set to 50 Hz.'] };
for k = 1:size(blk,1)
    w('<tr><td class="tag">%s</td><td><code>%s</code></td><td>%s</td></tr>\n', blk{k,:});
end
w('</tbody></table>\n');
w(['<p class="note"><b>What is deliberately not a block.</b> Bay conductors, ' ...
   'disconnectors, earthing switches, current and voltage transformer burdens, ' ...
   'the generator circuit breaker and the isolated phase busbar run all appear ' ...
   'on the plant drawing but carry <b>no documented impedance</b>. They are ' ...
   'drawn as ideal connections and labelled as such. Giving them textbook ' ...
   'impedances would put invented numbers into a study whose whole purpose is ' ...
   'to be traceable.</p>\n']);
w('<h3>How the layout is held to the plant drawing</h3>\n');
w(['<p>The positions are not eyeballed. One file holds every column and every ' ...
   'tier as a named coordinate, and asserts the relationships that make the ' ...
   'sheet readable as a single-line diagram &mdash; so the layout cannot drift ' ...
   'as blocks are added.</p>\n']);
snip(fid, root, 'build/sps_geom.m', 'g.col.g1', 14, ...
     'Column coordinates, and the assertions that keep them in the drawing''s order');
w('</section>\n');

% ================================================================ 5 matlab
w('<section id="s5"><h2>5. The MATLAB code, file by file</h2>\n');
w(['<p>The code is layered so that data, model construction, solving and ' ...
   'checking never mix. Reading order is top to bottom.</p>\n']);

layer(fid, 'Dataset', ['Every plant parameter, with its source document and a status flag ' ...
    'on each number. Nothing downstream may contain a parameter value.'], ...
    { 'data/ashuganj_master_data.m', 'Assembles the whole dataset and the four case definitions. Everything else reads this.'
      'data/ashuganj_buses.m',       'The eight electrical nodes, their nominal voltages and bases.'
      'data/ashuganj_generators.m',  'Generator nameplate: 458/518 MVA, 22 kV, pf 0.85, and the reactances kept for the fault study.'
      'data/ashuganj_transformers.m','The three transformers. Also derives X from Z and R, and the magnetising branch from no-load loss and excitation current.'
      'data/ashuganj_loads.m',       'The 6.6 kV auxiliary load and its split across the three nodes.'
      'data/ashuganj_grid.m',        'The external grid equivalent, ESTIMATED Siemens §2.4 50 kA source quantity (equipment ratings separate).'
      'data/ashuganj_lines.m',       'The plant''s internal connections, and the record that their impedances are undocumented.'
      'data/assumptions/*.m',        'One file per assumption, kept apart from verified data on purpose. Five files.' });

layer(fid, 'Model builders', ['Turn the dataset into a Simulink model. These files contain ' ...
    'geometry and block wiring - no electrical values.'], ...
    { 'build/build_ashuganj_main.m',    'The driver: creates the model, calls each zone builder, wires the zones together, draws busbars, captions and the footer tables, saves.'
      'build/sps_geom.m',               'The single layout authority: every column, tier, block size and colour. The reason the diagram matches the plant drawing.'
      'build/sps_wire.m',               'Adds blocks, draws orthogonal connections, busbars, captions and zone panels.'
      'build/sps_blocks.m',            'The library paths of the Simscape blocks used, and a note on the ones deliberately not used.'
      'build/build_generator_system.m', 'The generator zone.'
      'build/build_gsut_system.m',      'The step-up transformer zone.'
      'build/build_230kv_system.m',     'The 230 kV switchyard: busbars, coupler, station-auxiliary bay.'
      'build/build_auxiliary_system.m', 'The 6.6 kV system: both auxiliary transformers and the three load groups.'
      'build/build_external_grid.m',    'The grid swing source and its series impedance.' });

layer(fid, 'Solve and analyse', 'Run the study and extract results.', ...
    { 'studies/run_load_flow_study.m',   'The main driver. Builds each case fresh, solves it, cross-checks it, writes every table.'
      'analysis/ashuganj_bus_map.m',     'Works out which solved bus is which named node - the solver numbers buses, it does not name them.'
      'analysis/ashuganj_branch_flows.m','Rebuilds every branch flow from the solved voltages and the documented impedances - an independent check, not a readout.'
      'analysis/ashuganj_bus_results.m', 'The per-bus table, and the KCL residual at every node.'
      'analysis/make_load_flow_plots.m', 'The figures, drawn from the CSVs so they cannot disagree with the tables.'
      'studies/make_annotated_diagrams.m','The presentation one-line with solved flows written onto it.'
      'utilities/convert_to_system_base.m','Per-unit base conversion.' });

layer(fid, 'Validation', ['The suite that has to pass before any result is quoted. ' ...
    'It checks the dataset for internal consistency, and the built model against ' ...
    'the dataset.'], ...
    { 'tests/run_all_tests.m',                'Runs everything and prints the summary.'
      'tests/test_bus_data.m',                'Bus register consistency (61 checks).'
      'tests/test_generator_data.m',          'Generator data and its per-unit conversions (28).'
      'tests/test_transformer_data.m',        'All three transformers, every derived quantity (85).'
      'tests/test_line_data.m',               'Connection records, and that no impedance was invented (47).'
      'tests/test_load_data.m',               'Load totals and the split (58).'
      'tests/test_base_conversion.m',         'Per-unit arithmetic (19).'
      'tests/test_topology.m',                'That the built network matches the register (52).'
      'tests/test_transformer_phase_shift.m', 'That the vector groups produce the right phase shifts in the solved model (18).'
      'tests/test_grid_sensitivity.m',        'How much the estimated grid impedance actually matters (38).'
      'tests/test_magnetising_sensitivity.m', 'How much the magnetising branch matters (41).' });
w('</section>\n');

% ================================================================ 6 key code
w('<section id="s6"><h2>6. Key code, and what each piece does</h2>\n');
w(['<p>The excerpts below carry the engineering, with what each one is for. ' ...
   'They are <b>quoted from the source files at the moment this page is ' ...
   'generated</b>, with the line numbers shown, so they cannot go out of date ' ...
   'against the code they describe. Everything else in the project is ' ...
   'bookkeeping around these.</p>\n']);

w('<h3>Where the numbers come from</h3>\n');
w(['<p>Nameplates give impedance as a magnitude and a resistance percentage. ' ...
   'The model needs reactance, split windings and a magnetising branch. That ' ...
   'conversion happens in exactly one place, from nameplate quantities only.</p>\n']);
snip(fid, root, 'data/ashuganj_transformers.m', 'Zpu = T(i).Z_pct/100;', 15, ...
     'Nameplate Z, R, no-load loss and excitation current &rarr; the block''s parameters');
w(['<p>The <code>assert</code> is not decoration: if R ever exceeded Z the ' ...
   'square root would go imaginary and produce a complex "reactance" that ' ...
   'Simulink would accept and quietly mis-solve. The magnetising resistance ' ...
   'comes from no-load loss, and the magnetising inductance from excitation ' ...
   'current with the iron-loss component removed &mdash; not from the ' ...
   'excitation current alone, which is the common shortcut.</p>\n']);

w(['<p>The grid is the one component with no PGCB nameplate. Its impedance is ' ...
   'derived from the ESTIMATED Siemens §2.4 50 kA external-grid source quantity ' ...
   '(equipment 50 kA/1 s+3 s, 125 kA peak, 50 kA making are separate ratings) ' ...
   '&mdash; so the derivation is written out in full and the value ' ...
   'is flagged as estimated everywhere it appears.</p>\n']);
snip(fid, root, 'data/ashuganj_grid.m', 'G.Ssc_MVA', 6, ...
     'The external grid equivalent, ESTIMATED Siemens §2.4 source quantity');
w(['<p>R is set to <b>zero exactly</b>, not to a textbook X/R. No grid X/R is ' ...
   'documented, and a fabricated one would look like data. The cost of that ' ...
   'choice is stated in &sect;9 rather than hidden.</p>\n']);

w('<h3>How the model gets built</h3>\n');
w(['<p>The build files contain no electrical values at all &mdash; they read ' ...
   'the dataset and write it into blocks. This is the whole of the transformer ' ...
   'parameterisation, and it is worth reading as the answer to "where did that ' ...
   'block''s numbers come from".</p>\n']);
snip(fid, root, 'build/build_auxiliary_system.m', 'function apply_tx2', 16, ...
     'Dataset struct &rarr; Three-Phase Transformer block parameters');
w(['<p>Note <code>UNITS''pu''</code> first: the order matters, because the ' ...
   'block reinterprets the numbers already in its winding fields when the unit ' ...
   'system changes. Note also that saturation is left off &mdash; a saturation ' ...
   'characteristic is not in the source documents, and a balanced load flow ' ...
   'does not use one.</p>\n']);

w(['<p>The two breakers are the only blocks whose state encodes the case ' ...
   'matrix. Their switching times are pushed far into the future so that ' ...
   'nothing ever operates: for a load flow they are static links, open or ' ...
   'closed.</p>\n']);
snip(fid, root, 'build/build_230kv_system.m', 'function set_breaker', 19, ...
     'The bay breaker and bus coupler, set once per case and never switched');

w(['<p>Two settings in the model driver matter more than they look. The solver ' ...
   'choice is what Specialized Power Systems needs for a circuit containing ' ...
   'magnetising branches; the frequency has to be written <b>twice</b>, because ' ...
   'the dialog field and the field the analysis tools actually read are ' ...
   'different parameters. Setting only the visible one leaves a 50 Hz-looking ' ...
   'model solving at 60 Hz &mdash; which is exactly the defect found in the ' ...
   'plant''s previous study.</p>\n']);
snip(fid, root, 'build/build_ashuganj_main.m', 'set_param(mdl, ...', 11, ...
     'Solver configuration for a Specialized Power Systems network');
snip(fid, root, 'build/build_ashuganj_main.m', 'fHz = D.base.f_Hz;', 10, ...
     'Setting 50 Hz where the load flow will actually read it');

w('<h3>Solving, and proving the answer</h3>\n');
w(['<p>The solve is one call. The report is requested in the <b>same</b> call ' ...
   'that returns the solution, because solving writes the answer back into the ' ...
   'blocks &mdash; a second solve would describe a slightly different ' ...
   'network.</p>\n']);
snip(fid, root, 'studies/run_load_flow_study.m', 'if isempty(rptPath)', 5, ...
     'The load flow itself');
w(['<p>Then the gate that everything downstream depends on. <code>' ...
   'power_loadflow</code> does <b>not</b> throw when it fails to converge; it ' ...
   'returns a status and strips the solution fields. Without this check a ' ...
   'failed case would surface as a confusing error deep in post-processing, or ' ...
   'worse, as a table.</p>\n']);
snip(fid, root, 'studies/run_load_flow_study.m', 'if LF.status ~= 1', 6, ...
     'Convergence is checked before a single number is post-processed');

w(['<p>The results are then rebuilt from scratch, outside the solver. This is ' ...
   'the part that makes the study defensible rather than merely produced: the ' ...
   'off-nominal turns ratio and the vector-group phase shift are applied ' ...
   'independently, the branch is solved as a T-network by hand, and the answer ' ...
   'is compared against what the solver reported.</p>\n']);
snip(fid, root, 'analysis/ashuganj_branch_flows.m', 'ratio = (x.V_HV_V / x.V_LV_V)', 11, ...
     'Off-nominal ratio and vector-group shift, applied independently of the solver');
snip(fid, root, 'analysis/ashuganj_branch_flows.m', 'VA = (VLref/Z2 + VH/Z1)', 4, ...
     'The transformer T-network solved by hand from the solved bus voltages');
w(['<p>The <code>YNd1</code> &rarr; +30&deg;, <code>Dyn11</code> &rarr; ' ...
   '&minus;30&deg; mapping is the mechanism behind Finding&nbsp;2, and the ' ...
   '<code>otherwise</code> branch refuses to guess: an unrecognised vector ' ...
   'group produces a warning attached to the result rather than a silent ' ...
   'zero.</p>\n']);

w(['<p>Before any of that is trusted, one sanity check on the solver''s own ' ...
   'units. If a future release ever reported bus injections in MW instead of ' ...
   'per unit, every number in the study would be wrong by a factor of a hundred ' ...
   'while still looking entirely plausible. The generator injection is known ' ...
   'exactly from the case definition, so it is used as the probe.</p>\n']);
snip(fid, root, 'analysis/ashuganj_bus_results.m', 'if abs(real(LF.bus(kPV).Sbus)*Sb - C.Gen_P_MW) > 1e-3', 7, ...
     'A guard against the solver''s units changing underneath the study');
w(['<p>And finally the cross-check itself: at every bus, the sum of the ' ...
   'independently computed branch flows against the injection the solver ' ...
   'reports. Agreement to a fraction of a microwatt means two separate ' ...
   'calculations agree on which network was solved.</p>\n']);
snip(fid, root, 'analysis/ashuganj_bus_results.m', 'inj = Bres(j).P_inj_MW', 9, ...
     'The KCL residual &mdash; the number quoted at the top of this page');
w('</section>\n');

% ================================================================ 7 results
w('<section id="s7"><h2>7. Load flow results</h2>\n');
w(['<p>Four cases. Two things vary independently: how hard the unit is ' ...
   'running, and whether the station auxiliary transformer''s 230 kV bay is ' ...
   'closed. Varying them separately is the point &mdash; reporting only two ' ...
   'cases would confuse the effect of dispatch with the effect of the bay.</p>\n']);
w('<table><thead><tr><th>Case</th><th>Dispatch</th><th>Station aux bay</th><th>Network</th></tr></thead><tbody>\n');
for k = 1:height(SUM)
    w('<tr><td class="tag">%s</td><td>%.2f MW (%s)</td><td>%s</td><td>%s</td></tr>\n', ...
      SUM.Case{k}, SUM.P_dispatch_MW(k), lower(SUM.Dispatch{k}), ...
      upper(SUM.GAT{k}), SUM.Topology{k});
end
w('</tbody></table>\n');

w('<h3>System summary</h3>\n');
w('<table class="num"><thead><tr><th>Case</th><th>Generation<br>MW</th><th>Reactive<br>MVAr</th>');
w('<th>Auxiliary<br>MW</th><th>Losses<br>MW</th><th>Export<br>MW</th><th>Loss<br>%%</th><th>Iter.</th></tr></thead><tbody>\n');
for k = 1:height(SUM)
    w(['<tr><td class="tag">%s</td><td>%.2f</td><td>%+.2f</td><td>%.2f</td>' ...
       '<td>%.3f</td><td>%.2f</td><td>%.3f</td><td>%d</td></tr>\n'], ...
      SUM.Case{k}, SUM.P_gen_MW(k), SUM.Q_gen_MVAr(k), SUM.P_aux_MW(k), ...
      SUM.P_loss_MW(k), SUM.P_export_MW(k), SUM.Loss_pct_of_gen(k), SUM.Iterations(k));
end
w('</tbody></table>\n');

w('<h3>Voltages</h3>\n');
w(['<p>Per-unit, on each bus''s own nominal voltage. The 22 kV bus is exactly ' ...
   '1.000 because that is where the generator holds voltage.</p>\n']);
w('<table class="num"><thead><tr><th>Case</th><th>230 kV bus</th><th>22 kV bus</th>');
w('<th>6.6 kV bus<br>(6600 V base)</th><th>6.6 kV bus<br>(6900 V base)</th></tr></thead><tbody>\n');
for k = 1:height(SUM)
    w('<tr><td class="tag">%s</td><td>%.4f</td><td>%.4f</td><td>%.4f</td><td>%.4f</td></tr>\n', ...
      SUM.Case{k}, SUM.V_230kV_pu(k), SUM.V_22kV_pu(k), ...
      SUM.V_6p6kV_pu_6600base(k), SUM.V_6p6kV_pu_6900base(k));
end
w('</tbody></table>\n');
w(['<p class="note">Two columns for the same bus, because the transformer ' ...
   'windings are rated <b>6.9 kV</b> while the board and its motors are ' ...
   '<b>6.6 kV</b>. That is a real off-nominal ratio in the plant, worth ' ...
   '4.55 %% on the reported voltage, and it is shown both ways rather than ' ...
   'quietly resolved.</p>\n']);

w('<h3>Bus detail, case %s</h3>\n', SUM.Case{1});
w(['<p>Every bus in the register gets a row. Where two rows share one solved ' ...
   'node, only the first carries the injection and the second names the node it ' ...
   'merged into &mdash; repeating the figure on both would double the reported ' ...
   'load. Injections are generation-positive.</p>\n']);
b1 = BUS(strcmp(BUS.Case, SUM.Case{1}), :);
w('<table class="num"><thead><tr><th>Bus</th><th>Label</th><th>Type</th><th>Nominal<br>kV</th>');
w('<th>V pu</th><th>kV</th><th>Angle &deg;</th><th>P inj<br>MW</th><th>Q inj<br>MVAr</th></tr></thead><tbody>\n');
for k = 1:height(b1)
    mg = '';
    if ~isempty(strtrim(b1.Merged_into{k}))
        mg = sprintf('<div class="sl">same node as %s</div>', b1.Merged_into{k});
    end
    w(['<tr><td class="tag">%s</td><td>%s%s</td><td>%s</td><td>%g</td>' ...
       '<td>%.4f</td><td>%.3f</td><td>%+.3f</td><td>%s</td><td>%s</td></tr>\n'], ...
      b1.Bus{k}, b1.Label{k}, mg, b1.Type{k}, b1.Vnom_V(k)/1000, ...
      b1.V_pu(k), b1.V_kV(k), b1.Angle_deg(k), ...
      nd(b1.P_inj_MW(k), '%+.3f'), nd(b1.Q_inj_MVAr(k), '%+.3f'));
end
w('</tbody></table>\n');
% The three rows a reader will stop on, explained from the case flags rather
% than from a hand-written list, so they stay correct if the case changes.
nMerged = sum(~cellfun(@(s) isempty(strtrim(s)), b1.Merged_into));
vgat = b1.V_pu(strcmp(b1.Bus, 'GAT_HV'));
if isempty(vgat), vgat = NaN; end
w(['<p class="note"><b>Three rows need a word of explanation.</b> ' ...
   '<b>%d of the %d rows</b> are merged members. The two water-intake nodes ' ...
   'merge into the main 6.6 kV bus because the feeders between them have no ' ...
   'documented impedance &mdash; a zero-impedance connection is not a branch to ' ...
   'a load flow, it is an identity. 230 kV BUS 2 merges into BUS 1 because the ' ...
   'coupler is closed, which also means the coupler current is not observable. ' ...
   'And <code>GAT_HV</code> is not a busbar at all: with the station auxiliary ' ...
   'bay open it is a transformer terminal back-energised from the 6.6 kV side, ' ...
   'so its %.4f pu is a turns ratio and not a system voltage.</p>\n'], ...
   nMerged, height(b1), vgat);

w('<h3>Transformer loading</h3>\n');
w(['<p>Against the <b>lowest</b> cooling stage &mdash; the rating in force ' ...
   'before fans and pumps start. This is where the two findings are.</p>\n']);
w('<table class="num"><thead><tr><th>Case</th><th>Transformer</th><th>Rating stages<br>MVA</th>');
w('<th>Flow MW</th><th>MVA</th>');
w('<th>Loading, lowest stage</th><th>Loading, highest stage</th><th>Loss MW</th></tr></thead><tbody>\n');
for k = 1:height(TX)
    lo = TX.Loading_pct_lowest_stage(k);
    cls = '';
    if lo > 100, cls = ' class="bad"'; end
    w(['<tr><td class="tag">%s</td><td>%s</td><td>%s</td><td>%.2f</td><td>%.2f</td>' ...
       '<td%s>%.1f %%</td><td>%.1f %%</td><td>%.4f</td></tr>\n'], ...
      TX.Case{k}, TX.Transformer{k}, ...
      strtrim(strrep(strrep(TX.Rating_stages_MVA{k}, '[', ''), ']', '')), ...
      abs(TX.P_HV_MW(k)), TX.S_HV_MVA(k), ...
      cls, lo, TX.Loading_pct_highest_stage(k), TX.P_loss_MW(k));
end
w('</tbody></table>\n');
w(['<p class="note">Red marks a transformer over its natural-cooling rating. ' ...
   'In the two cases where the station auxiliary bay is closed, <b>both</b> ' ...
   'auxiliary paths are loaded and the unit transformer goes over nameplate ' ...
   'while the load it supplies has not changed &mdash; see Finding 2.</p>\n']);

w('<h3>Generator</h3>\n');
w('<table class="num"><thead><tr><th>Case</th><th>MW</th><th>MVAr</th><th>MVA</th><th>pf</th>');
w('<th>Current A</th><th>%% of 458 MVA</th></tr></thead><tbody>\n');
for k = 1:height(GEN)
    w(['<tr><td class="tag">%s</td><td>%.2f</td><td>%+.2f</td><td>%.2f</td>' ...
       '<td>%.4f</td><td>%.0f</td><td>%.1f %%</td></tr>\n'], ...
      GEN.Case{k}, GEN.P_MW(k), GEN.Q_MVAr(k), GEN.S_MVA(k), ...
      GEN.PowerFactor(k), GEN.I_A(k), GEN.Loading_pct_458MVA_50C(k));
end
w('</tbody></table>\n');

w('<h3>The same results as figures</h3>\n');
w(['<p>Drawn from the CSVs above by <code>make_load_flow_plots()</code>, so a ' ...
   'figure cannot disagree with its table.</p>\n']);
w('<div class="grid2">\n');
img(fid, outDir, 'power_balance.png', 'Generation, auxiliary demand, losses and export, per case.');
img(fid, outDir, 'bus_voltage_profile.png', 'Bus voltages against nominal. The 22 kV bus is the regulated point.');
img(fid, outDir, 'transformer_loading.png', 'Transformer loading against every cooling stage &mdash; where both findings show up.');
img(fid, outDir, 'line_loading.png', 'Branch loading, including the circulating flow through the auxiliary loop.');
w('</div>\n');
w('</section>\n');

% ================================================================ 8 meaning
w('<section id="s8"><h2>8. What the results mean</h2>\n');

w('<h3>The numbers are consistent</h3>\n');
% Both cross-checks are computed here rather than quoted, and the radial and
% looped cases are separated: they differ by four orders of magnitude, and a
% single worst-case figure would hide the reason.
isRad  = strcmpi(SUM.Topology, 'radial');
kclRad = max(SUM.Worst_KCL_residual_MVA(isRad));
kclLup = max(SUM.Worst_KCL_residual_MVA(~isRad));
bal    = max(abs(SUM.P_gen_MW - SUM.P_aux_MW - SUM.P_loss_MW - SUM.P_export_MW));
w(['<p>All four cases converge in <b>%d iterations</b>, which is what a ' ...
   'well-conditioned network of this size should do. More useful than ' ...
   'convergence: every branch flow was <b>rebuilt from the solved voltages and ' ...
   'the nameplate impedances, outside the solver</b>, and compared against the ' ...
   'solver''s own bus injections at every node.</p>\n'], max(SUM.Iterations));
w(['<p>The worst mismatch is <b>%.1e MVA</b> in the two radial cases and ' ...
   '<b>%.1e MVA</b> in the two looped ones. The looped cases are worse for a ' ...
   'reason worth stating: there the circulating power is the small difference ' ...
   'between two much larger flows, so it inherits proportionally more of the ' ...
   'solver''s convergence tolerance. Even so, %.1e MVA on a %g MVA base is ' ...
   'below the tolerance the solve was asked to meet.</p>\n'], ...
   kclRad, kclLup, kclLup, D.base.Sbase_MVA);
w(['<p>Separately, generation minus auxiliary demand minus losses equals export ' ...
   'to <b>%.0e MW</b> &mdash; machine precision, in every case. The answers are ' ...
   'arithmetically sound; whether they are the right answers depends on the ' ...
   'input data, which is what &sect;9 is about.</p>\n'], bal);

% Every figure in the two findings is pulled from the tables by case and
% transformer name, so the prose cannot drift from the numbers above it. The
% GSUT stages come out of the register rather than being typed as 355 and 515.
xg = D.tx(strcmp({D.tx.Label}, 'GSUT 10BAT10'));
xu = D.tx(strcmp({D.tx.Label}, 'UAT 10BBT10'));
ig = find(strcmp(TX.Case,'LF1') & strcmp(TX.Transformer,'GSUT 10BAT10'), 1);

w('<h3>Finding 1 &mdash; the step-up transformer needs forced cooling at full output</h3>\n');
w(['<p>At rated dispatch the step-up transformer carries <b>%.1f %% of its ' ...
   '%g MVA natural-cooling rating</b>. It is comfortable on the highest ' ...
   'stage &mdash; %.1f %% of %g MVA &mdash; so nothing is over-rated, but ' ...
   'the oil pumps and fans are <b>not optional</b> at full load. This is a ' ...
   'straightforward consequence of the ratings, and it is the kind of thing ' ...
   'that is easy to miss if loading is only ever quoted against the top ' ...
   'cooling stage.</p>\n'], ...
   TX.Loading_pct_lowest_stage(ig), xg.S_MVA(1), ...
   TX.Loading_pct_highest_stage(ig), xg.S_MVA(end));

w('<h3>Finding 2 &mdash; closing the station auxiliary bay makes power circulate</h3>\n');
i2   = find(strcmp(SUM.Case,'LF2'), 1);
iu   = find(strcmp(TX.Case,'LF2') & strcmp(TX.Transformer,'UAT 10BBT10'), 1);
igat = find(strcmp(TX.Case,'LF2') & strcmp(TX.Transformer,'GAT 10BBT20'), 1);
uatMW = abs(TX.P_LV_MW(iu));
w(['<p>With the station auxiliary bay closed, the 6.6 kV board is fed from ' ...
   '<b>both ends at once</b> &mdash; through the unit transformer from 22 kV, ' ...
   'and through the station transformer from 230 kV. The two paths form a loop, ' ...
   'and the loop carries circulating power.</p>\n']);
w(['<p>The unit transformer delivers <b>%.2f MW</b> into a <b>%.2f MW</b> ' ...
   'load. The surplus &mdash; <b>%.2f MW</b> &mdash; leaves again through the ' ...
   'station transformer and back into the 230 kV system. It is not consumed by ' ...
   'anything; it simply goes round. The independent check is that the station ' ...
   'transformer reports almost exactly that figure flowing the other way ' ...
   '(%.2f MW), and the step-up transformer''s throughput drops by the same ' ...
   'amount.</p>\n'], uatMW, SUM.P_aux_MW(i2), uatMW - SUM.P_aux_MW(i2), ...
   abs(TX.P_LV_MW(igat)));
w(['<p><b>Why it is allowed to happen at all:</b> the vector groups permit ' ...
   'it. Going round the loop, the step-up transformer contributes +30&deg;, ' ...
   'the station transformer 0&deg; and the unit transformer &minus;30&deg;, ' ...
   'which sums to zero. There is no phase barrier to stop the flow.</p>\n']);
w(['<p><b>Why it matters:</b> this pushes the unit auxiliary transformer to ' ...
   '<b>%.1f %% of its %g MVA natural-cooling rating</b> &mdash; over its ' ...
   'nameplate, to supply a load well inside it. On the forced-cooling stage it ' ...
   'is %.1f %%, so the unit is not endangered, but running both supplies in ' ...
   'parallel is loading a transformer for no delivered power. Whether the ' ...
   'plant actually does this is a question for the operators; the model shows ' ...
   'what happens if it does.</p>\n'], ...
   TX.Loading_pct_lowest_stage(iu), xu.S_MVA(1), TX.Loading_pct_highest_stage(iu));
img(fid, outDir, 'Load_Flow_LF2_Annotated.png', ...
    ['Case LF2 on the sheet. Compare the unit transformer''s flow with the ' ...
     'auxiliary load beneath it: the difference is the circulating power, and ' ...
     'it reappears on the station auxiliary transformer at the far right.']);

w('<h3>Finding 3 &mdash; losses and voltages are unremarkable, which is itself the result</h3>\n');
w(['<p>Losses run %.3f&ndash;%.3f MW, %.2f&ndash;%.2f %% of generation. Every ' ...
   'bus sits within %.2f %% of nominal. There is no voltage problem and no ' ...
   'reactive problem at any of the four operating points, which is the answer ' ...
   'the load flow was asked for &mdash; and it is the baseline the fault study ' ...
   'will be measured against.</p>\n'], ...
   min(SUM.P_loss_MW), max(SUM.P_loss_MW), ...
   min(SUM.Loss_pct_of_gen), max(SUM.Loss_pct_of_gen), ...
   100*max(abs([SUM.V_230kV_pu; SUM.V_22kV_pu; SUM.V_6p6kV_pu_6600base] - 1)));
w(['<p>One caveat on the losses: they are <b>copper and iron losses in the ' ...
   'transformers only</b>. The plant''s cables, busbars and bay conductors ' ...
   'have no documented impedance, so they contribute zero. The real plant ' ...
   'loses slightly more. The figure is a floor, not an estimate.</p>\n']);

w('<h3>Dispatch makes less difference than expected</h3>\n');
w(['<p>Dropping from %.2f to %.2f MW cuts losses by %.0f %% but moves the ' ...
   '230 kV voltage by only %.4f pu. The grid is strong relative to the plant, ' ...
   'so the boundary voltage barely notices the unit''s output. This also means ' ...
   'the estimated grid impedance is not doing much damage to the answers ' ...
   '&mdash; which the sensitivity tests confirm separately.</p>\n'], ...
   SUM.P_dispatch_MW(1), SUM.P_dispatch_MW(3), ...
   100*(SUM.P_loss_MW(1)-SUM.P_loss_MW(3))/SUM.P_loss_MW(1), ...
   abs(SUM.V_230kV_pu(3)-SUM.V_230kV_pu(1)));
w('</section>\n');

% ================================================================ 9 assumptions
w('<section id="s9"><h2>9. Assumptions and missing data</h2>\n');
w(['<p>Four assumptions are live in the model. Each is in its own file under ' ...
   '<code>matlab/data/assumptions/</code>, kept out of the verified dataset so ' ...
   'the two can never be confused.</p>\n']);
w('<table><thead><tr><th>What was assumed</th><th>Value</th><th>Why</th><th>Effect on the answers</th></tr></thead><tbody>\n');
asm = { 'Grid series resistance', 'R = 0', ...
        'No grid X/R is documented anywhere in the source set.', ...
        'Grid losses read as zero. Reactive output understated by up to 17 %. This is the pessimistic choice, not a convenient one.'
        'Auxiliary load split', '9050 : 2500 : 2500 kW', ...
        'The 14 MW total is documented; the division between the three boards is not stated as such.', ...
        'None on any solved quantity - the three nodes are electrically one node, because the feeder impedances are undocumented.'
        'Bus coupler position', 'closed', ...
        'The normal operating position is not stated in any available drawing or procedure.', ...
        'This is what closes the loop in the two cases where the station auxiliary bay is also closed, so it is what produces Finding 2.'
        'Generator voltage setpoint', '1.00 pu', ...
        'No AVR setpoint, voltage schedule or measured operating voltage was found. A PV bus requires a magnitude.', ...
        'Sets the reference for every voltage in the model. All per-unit results are relative to it.' };
for k = 1:size(asm,1)
    w('<tr><td><b>%s</b></td><td class="tag">%s</td><td>%s</td><td>%s</td></tr>\n', asm{k,:});
end
w('</tbody></table>\n');
w(['<p class="warn"><b>The setpoint assumption still needs a decision.</b> ' ...
   'The other three follow approved choices. The 1.00 pu generator setpoint ' ...
   'was necessary to build the model at all and is flagged unapproved in its ' ...
   'own file. If the plant runs to a different schedule &mdash; 1.02 pu is ' ...
   'common &mdash; every per-unit voltage in &sect;7 shifts with it.</p>\n']);

w('<h3>Data still missing, and what it blocks</h3>\n');
w('<table><thead><tr><th>Missing</th><th>Blocks</th></tr></thead><tbody>\n');
miss = { 'Generator x<sub>q</sub>, x<sub>2</sub>, x<sub>0</sub>, armature resistance, inertia H, time constants', ...
         'Unbalanced fault analysis and any transient stability work. x<sub>d</sub>, x<sub>d</sub>&prime;, x<sub>d</sub>&Prime; <i>are</i> available.'
         'Cable and busbar impedances and lengths (all internal connections)', ...
         'Realistic loss figures, and fault current at anything other than a bus.'
         'Grid short-circuit MVA and X/R from PGCB', ...
         'Fault levels at the 230 kV boundary. The present grid impedance is inferred from the switchgear rating, not from a grid study.'
         'Zero-sequence data for the transformers beyond Z<sub>0</sub>, and neutral earthing resistor values', ...
         'Earth-fault current calculation, which is the main input to earth-fault protection.'
         'Relay makes, models, CT and VT ratios, and present settings', ...
         'The whole of stage 3. Nothing about coordination can start without these.'
         'Station auxiliary transformer third-winding impedances (Z<sub>PT</sub>, Z<sub>ST</sub>)', ...
         'Any fault study that involves the 3.32 kV winding.'
         'Measured operating data - a real dispatch point, real bus voltages', ...
         'Validating the model against the plant. At present both dispatch cases are ratings, not measurements.' };
for k = 1:size(miss,1)
    w('<tr><td>%s</td><td>%s</td></tr>\n', miss{k,:});
end
w('</tbody></table>\n');
w('</section>\n');

% ================================================================ 10 remaining
w('<section id="s10"><h2>10. What remains</h2>\n');
w('<h3>Stage 2 &mdash; short-circuit and fault analysis</h3>\n');
w('<ol>\n');
w('<li>Collect the zero- and negative-sequence data listed in &sect;9. Without it only three-phase faults can be done properly.</li>\n');
w('<li>Get a grid short-circuit level from PGCB, to replace the impedance currently derived from the ESTIMATED Siemens §2.4 source quantity.</li>\n');
w('<li>Compute three-phase fault current at each bus, using the load flow above as the pre-fault condition.</li>\n');
w('<li>Add the sequence networks and compute single-line-to-ground, line-to-line and double-line-to-ground faults.</li>\n');
w('<li>Check the results against the switchgear ratings already in the dataset &mdash; 50 kA at 230 kV, 31.5 kA at 6.6 kV, and the generator breaker''s 12.4 kA.</li>\n');
w('</ol>\n');
w('<h3>Stage 3 &mdash; protection coordination</h3>\n');
w('<ol>\n');
w('<li>Collect relay and instrument transformer data. This is the hard dependency.</li>\n');
w('<li>Build time-current curves for the overcurrent devices from the fault currents of stage 2.</li>\n');
w('<li>Check grading between the 6.6 kV feeders, the auxiliary transformers and the 230 kV bays.</li>\n');
w('<li>Verify differential protection zones on the generator and the three transformers.</li>\n');
w('</ol>\n');
w('<h3>Smaller items on this stage</h3>\n');
w('<ul>\n');
w('<li>Get a decision on the generator voltage setpoint, so it stops being an unapproved assumption.</li>\n');
w('<li>Settle the 6.9 kV / 6.6 kV question with the plant &mdash; it is worth 4.55 %% on the reported auxiliary bus voltage.</li>\n');
w('<li>Confirm the normal bus-coupler position and whether both auxiliary supplies really do run in parallel. Finding 2 depends on the answer.</li>\n');
w('<li>Ask whether the circulating flow in Finding 2 is a known operating condition at the plant.</li>\n');
w('</ul>\n');
w('</section>\n');

% ================================================================ 11 file map
w('<section id="s11"><h2>11. Complete file map</h2>\n');
w(['<p>Counted off the disk when this page was generated, not maintained by ' ...
   'hand &mdash; so it is complete by construction. Folder by folder, with what ' ...
   'lives there and why it is separate from everything else.</p>\n']);
w('<table><thead><tr><th>Folder</th><th>Files</th><th>What is in it</th></tr></thead><tbody>\n');
tree = { 'matlab/data',             '*.m',   'The dataset. Every plant parameter with its source and status. No code that builds or solves anything.'
         'matlab/data/assumptions', '*.m',   'One file per assumption, deliberately outside the dataset so verified data and assumed data can never be read as the same thing.'
         'matlab/build',            '*.m',   'Model construction and layout geometry. Contains no electrical values.'
         'matlab/analysis',         '*.m',   'Post-processing: bus mapping, the independent branch-flow rebuild, result tables, figures.'
         'matlab/studies',          '*.m',   'The drivers that produce deliverables - the load flow study, the annotated diagrams, this page.'
         'matlab/tests',            '*.m',   'The validation suite. Has to pass before a result is quoted.'
         'matlab/utilities',        '*.m',   'Per-unit conversion and small shared helpers.'
         'matlab/env',             '*.m',   'One-off probes that measured how the solver actually behaves. Evidence for the validation notes, not library code - deliberately kept off the MATLAB path.'
         'simulink/main',           '*.slx', 'The model itself.'
         'simulink/studies',        '*.slx', 'The annotated per-case copies used for presentation.'
         'simulink/backups',        '*.slx', 'Versioned backups, written before any rebuild. No working model is ever overwritten in place.'
         'results/load_flow',       '*.csv', 'Every solved number. The tables in this page are read from here.'
         'results/load_flow',       '*.rep', 'The solver''s own reports, one per case - independent of our post-processing.'
         'results/plots',           '*.png', 'The result figures.'
         'results/diagrams',        '*.png', 'The annotated one-line, exported as an image.'
         'docs/validation',         '*.md',  'The audit trail: source inventory, verified parameters, conflicts, missing data, assumptions, prior-model defects, solver behaviour.'
         'docs/manual',             '*.html','This document, and the figures it embeds.' };
for k = 1:size(tree,1)
    n = numel(dir(fullfile(root, strrep(tree{k,1}, '/', filesep), tree{k,2})));
    w('<tr><td class="tag">%s</td><td class="tag">%d &times; %s</td><td>%s</td></tr>\n', ...
      tree{k,1}, n, tree{k,2}, tree{k,3});
end
w('</tbody></table>\n');

% Every .m file on disk, listed by folder. A file that exists but was never
% described in section 5 shows up here regardless, which is the point: the
% inventory is generated, so it cannot quietly omit anything.
w('<h3>Every MATLAB file, by folder</h3>\n');
mdirs = {'data', 'data/assumptions', 'build', 'analysis', 'studies', 'tests', 'utilities', 'env'};
totM = 0;  totLines = 0;
w('<table class="files"><tbody>\n');
for k = 1:numel(mdirs)
    dd = dir(fullfile(root, 'matlab', strrep(mdirs{k}, '/', filesep), '*.m'));
    if isempty(dd), continue, end
    nm = sort({dd.name});
    nl = 0;
    for j = 1:numel(dd), nl = nl + numel(readlines(fullfile(dd(j).folder, dd(j).name))); end
    totM = totM + numel(dd);  totLines = totLines + nl;
    % A long folder is summarised rather than dumped. matlab/env alone holds
    % dozens of one-off probes, and listing every filename would bury the
    % library folders that a reader actually needs to find.
    if numel(nm) > 14
        shown = sprintf('%s &middot; <i>and %d more</i>', ...
            strjoin(nm(1:8), ' &middot; '), numel(nm) - 8);
    else
        shown = strjoin(nm, ' &middot; ');
    end
    w('<tr><td><code>matlab/%s/</code></td><td>%s<div class="sl">%d files, %d lines</div></td></tr>\n', ...
      mdirs{k}, shown, numel(dd), nl);
end
% Anything at the top of matlab/ that is not in a subfolder - the setup script
% and the build script - would otherwise be invisible in this table.
dd = dir(fullfile(root, 'matlab', '*.m'));
if ~isempty(dd)
    nl = 0;
    for j = 1:numel(dd), nl = nl + numel(readlines(fullfile(dd(j).folder, dd(j).name))); end
    totM = totM + numel(dd);  totLines = totLines + nl;
    w('<tr><td><code>matlab/</code></td><td>%s<div class="sl">%d files, %d lines</div></td></tr>\n', ...
      strjoin(sort({dd.name}), ' &middot; '), numel(dd), nl);
end
w('</tbody></table>\n');
w('<p class="note"><b>%d MATLAB files, %d lines</b> in total.</p>\n', totM, totLines);
w('</section>\n');

% ================================================================ foot
w('<footer>\n');
w('<p>Generated by <code>matlab/studies/build_project_update.m</code> from <code>results/load_flow/*.csv</code>. ');
w('Every figure on this page is read from those tables; none is retyped.</p>\n');
w(['<p>Companion documents: <a href="LAB_REPORT.html">LAB_REPORT.html</a> ' ...
   '&mdash; the same study in the EEE 306 labsheet form, with the calculations ' ...
   'worked through and the report questions answered; ' ...
   '<a href="USER_MANUAL.html">USER_MANUAL.html</a> &mdash; how to run and ' ...
   'demonstrate it.</p>\n']);
w('<p>Dept. of EEE, BUET &middot; EEE 306 Power System I Laboratory &middot; Group-03, Section C-1</p>\n');
w('</footer>\n</body></html>\n');

clear c
fprintf('  written: %s\n', out);
d = dir(out);
fprintf('  size   : %.0f kB\n', d.bytes/1024);
end

% =====================================================================
function card(fid, label, value, note)
fprintf(fid, '<div class="card"><div class="cl">%s</div><div class="cv">%s</div><div class="cn">%s</div></div>\n', ...
    label, value, note);
end

% =====================================================================
function code(fid, txt)
fprintf(fid, '<pre class="code">%s</pre>\n', esc(txt));
end

% =====================================================================
function snip(fid, root, rel, anchor, nlines, why)
%SNIP  Quote a real excerpt from a source file, with its line numbers.
%
%   Anchored on a LINE OF CODE, never on a line number, so ordinary edits above
%   the excerpt cannot silently shift the quote onto the wrong lines. If the
%   anchor is gone, the page says so and quotes nothing: a confidently wrong
%   excerpt is worse than a missing one, and the same rule applies to code as to
%   parameter values.
f = fullfile(root, 'matlab', rel);
fprintf(fid, '<div class="snip"><div class="sh"><code>%s</code><span>%s</span></div>\n', ...
    rel, why);
if ~exist(f, 'file')
    fprintf(fid, ['<p class="warn"><code>%s</code> is not on disk, so nothing ' ...
        'was quoted from it.</p></div>\n'], rel);
    return
end
L = readlines(f);
i = find(startsWith(strtrim(L), anchor), 1);
if isempty(i)
    fprintf(fid, ['<p class="warn">The anchor line is no longer present in ' ...
        '<code>%s</code>, so no excerpt was quoted rather than the wrong lines ' ...
        'being quoted. Re-point the anchor in ' ...
        '<code>build_project_update.m</code>.</p></div>\n'], rel);
    return
end
j = min(i + nlines - 1, numel(L));
seg = L(i:j);

% Dedent by the smallest indent present, so an excerpt taken from inside a loop
% does not arrive with a stray four spaces on every line.
pad = inf;
for k = 1:numel(seg)
    s = char(seg(k));
    if isempty(strtrim(s)), continue, end
    pad = min(pad, numel(s) - strlength(strip(string(s), 'left')));
end
if ~isfinite(pad), pad = 0; end

txt = '';
for k = 1:numel(seg)
    s = char(seg(k));
    if numel(s) > pad, s = s(pad+1:end); else, s = strtrim(s); end
    txt = [txt esc(s) newline];                                   %#ok<AGROW>
end
fprintf(fid, '<pre class="code">%s</pre>\n', txt);
fprintf(fid, '<div class="sl">%s, lines %d&ndash;%d</div></div>\n', rel, i, j);
end

% =====================================================================
function img(fid, outDir, name, caption)
%IMG  Embed a figure that was copied beside the HTML, or say it is absent.
if exist(fullfile(outDir, name), 'file')
    fprintf(fid, ['<figure><img src="%s" alt="%s">' ...
        '<figcaption>%s</figcaption></figure>\n'], name, name, caption);
else
    fprintf(fid, ['<p class="warn">Figure <code>%s</code> has not been ' ...
        'generated yet. Run <code>make_load_flow_plots()</code> and ' ...
        '<code>make_annotated_diagrams()</code>, then regenerate this ' ...
        'page.</p>\n'], name);
end
end

% =====================================================================
function s = nd(v, fmt)
%ND  Format a number, or an em dash if the solver could not attribute one.
%   A merged bus has no injection of its own - not an unknown value, a question
%   with no answer in that network. It is shown as a dash, never as 0.
if isnan(v), s = '&mdash;'; else, s = sprintf(fmt, v); end
end

% =====================================================================
function s = esc(s)
%ESC  HTML-escape source text. Ampersand first, or the escapes escape each other.
s = strrep(s, '&', '&amp;');
s = strrep(s, '<', '&lt;');
s = strrep(s, '>', '&gt;');
end

% =====================================================================
function layer(fid, name, why, files)
fprintf(fid, '<h3>%s</h3>\n<p class="why">%s</p>\n', name, why);
fprintf(fid, '<table class="files"><tbody>\n');
for k = 1:size(files,1)
    fprintf(fid, '<tr><td><code>%s</code></td><td>%s</td></tr>\n', files{k,1}, files{k,2});
end
fprintf(fid, '</tbody></table>\n');
end

% =====================================================================
function s = css()
%CSS  The shared project stylesheet, so this page and the user manual match.
s = ashuganj_html_css();
end
