function D = phase6_dc_parameters(P)
%PHASE6_DC_PARAMETERS Numeric canonical station DC assumptions, no upstream edits.
% Source keys and values are retained exactly. Codes: 1=canonical records,
% 2=caller records, 3=added Phase6 academic interface/implementation assumption.
if nargin<1, P=struct(); end
setup_phase6_workspace();
source=1;
if isfield(P,'assumptions') && ~isempty(P.assumptions)
    A=P.assumptions; source=2;
else
    A=engineering_assumptions();
end
canonical=engineering_assumptions();
keys=fieldnames(canonical); D=struct();
for k=1:numel(keys)
    key=keys{k};
    if ~(startsWith(key,'dc_') || startsWith(key,'charger_') || startsWith(key,'load_'))
        continue
    end
    assert(isfield(A,key),'phase6:dcParameter','Missing canonical DC assumption %s.',key);
    record=A.(key);
    assert(isstruct(record) && isfield(record,'value') && isfield(record,'selected_value') ...
        && isequal(record.value,record.selected_value),'phase6:dcRecord', ...
        'DC assumption %s requires matching value and selected_value.',key);
    value=record.value;
    assert(isnumeric(value) && isreal(value) && all(isfinite(value(:))) ...
        && isequal(size(value),size(canonical.(key).value)), ...
        'phase6:dcValue','DC assumption %s has invalid shape or values.',key);
    D.(key)=double(value);
end
D.continuousLoad_W=1000*(D.load_relay_kW+D.load_control_kW ...
    +D.load_instrumentation_kW+D.load_communications_kW ...
    +D.load_emergency_control_kW+D.load_excitation_electronics_kW);
D.acPickup_pu=.8;
D.serviceTolerance_W=1e-6; % Numerical power-balance tolerance, not a plant setting.
D.provenance=struct('canonicalValues',source,'continuousLoad',source, ...
    'acPickup',3,'brownoutLoadEquivalent',3,'idealBatteryCurrentLimiter',3, ...
    'serviceTolerance',3);
D.assumptions=struct('chargerACPickup_pu',.8,'brownoutResistiveLoad',1, ...
    'fullSOCChargeBlocking',1,'idealBatteryCurrentLimiting',1, ...
    'proportionalUnservedLoadAllocation',1,'settledInitialCharger',1);
assert(D.dc_capacity_Ah>0 && D.dc_internal_resistance_ohm>0 ...
    && D.dc_soc_min>=0 && D.dc_soc_min<D.dc_soc_max ...
    && D.dc_soc_initial>=D.dc_soc_min && D.dc_soc_initial<=D.dc_soc_max ...
    && D.dc_max_charge_A>0 && D.dc_max_discharge_A>0 ...
    && D.dc_charge_efficiency>0 && D.dc_charge_efficiency<=1 ...
    && isequal(D.dc_ocv_soc,[0 1]) && all(diff(D.dc_ocv_V)>0) ...
    && D.charger_float_voltage_V>max(D.dc_ocv_V) ...
    && D.charger_response_s>0 && D.charger_max_current_A>0 ...
    && D.charger_rated_power_kW>0 && D.charger_efficiency>0 ...
    && D.charger_efficiency<=1 && D.charger_voltage_gain_A_per_V>0 ...
    && D.charger_active_units==1 && D.charger_unit_count==2 ...
    && D.continuousLoad_W>0, 'phase6:dcConfiguration','Inconsistent DC study configuration.');
end
