function phase6_assert_complete_run(out,S)
%PHASE6_ASSERT_COMPLETE_RUN Do not present interrupted/error output as complete.
assert(isa(out,'Simulink.SimulationOutput'),'Phase6:ProductionDataRequired', ...
    'A completed Simulink.SimulationOutput is required.');
assert(isempty(out.ErrorMessage),'Phase6:SimulationError', ...
    'Simulation reported an error: %s',out.ErrorMessage);
t=out.get('tout');
assert(isnumeric(t)&&isreal(t)&&isvector(t)&&~isempty(t) ...
    &&all(isfinite(t(:)))&&all(diff(t(:))>=0), ...
    'Phase6:IncompleteRun','The simulation has no valid complete time record.');
stop=S.stopTime_s;
assert(isnumeric(stop)&&isreal(stop)&&isscalar(stop)&&isfinite(stop)&&stop>0, ...
    'Phase6:ResultMetadata','Requested stop time must be a positive finite scalar.');
tolerance=max(1e-9,64*eps(max(1,stop)));
assert(abs(t(end)-stop)<=tolerance,'Phase6:IncompleteRun', ...
    ['Simulation ended at %.12g s; requested stop is %.12g s. ' ...
    'Interrupted or shortened output cannot be saved as a completed run.'],t(end),stop);
end
