function ctx = lr_part_disc2(fid, ctx)
%LR_PART_DISC2  Section 9 continued: losses, the residual check, and the angles.

w  = @(varargin) fprintf(fid, varargin{:});
D  = ctx.D;
c1 = ctx.SUM.Case{1};
S1 = ctx.SUM(strcmp(ctx.SUM.Case, c1), :);

% ------------------------------------------------------------ 9.5 losses
w('<h3>9.5 The losses, and what the loss figure does not include</h3>\n');
w(['<p>The plant''s electrical losses come out between %.4f and %.4f&nbsp;MW ' ...
   'across the %d cases, which is %.3f to %.3f&nbsp;%% of generation. Losses in ' ...
   'a series impedance go as the square of the current, so the loss should scale ' ...
   'roughly as the square of dispatch. It nearly does, and the departure is ' ...
   'informative:</p>\n'], min(ctx.SUM.P_loss_MW), max(ctx.SUM.P_loss_MW), ...
   height(ctx.SUM), min(ctx.SUM.Loss_pct_of_gen), max(ctx.SUM.Loss_pct_of_gen));
txt = sprintf('%-6s %10s %10s %12s %10s\n%s\n', 'case', 'P disp MW', ...
              'loss MW', 'predicted*', 'diff MW', repmat('-', 1, 52));
for k = 1:height(ctx.SUM)
    pred = S1.P_loss_MW * (ctx.SUM.P_dispatch_MW(k)/S1.P_dispatch_MW)^2;
    txt = [txt sprintf('%-6s %10.2f %10.4f %12.4f %10.4f\n', ...
           ctx.SUM.Case{k}, ctx.SUM.P_dispatch_MW(k), ctx.SUM.P_loss_MW(k), ...
           pred, ctx.SUM.P_loss_MW(k)-pred)];                             %#ok<AGROW>
end
txt = [txt sprintf(['\n* pure quadratic scaling from case %s, i.e. what the loss\n' ...
                    '  would be if every watt of it were load-dependent.'], c1)];
um_code(fid, txt);
w(['<p>The measured loss falls off less steeply than the square, because part of ' ...
   'it does not depend on the dispatch at all: the transformers'' no-load loss is ' ...
   'fixed, and the auxiliary load flowing through the unit transformer is the ' ...
   'same in every case. Only the step-up transformer''s copper loss follows the ' ...
   'dispatch, and it does so quadratically. That the residual column is small and ' ...
   'of one sign is a check that the model contains the loss mechanisms it is ' ...
   'supposed to contain and no others.</p>\n']);
w(['<p class="warn"><b>The figure is a floor.</b> It is the copper and iron loss ' ...
   'of three transformers. The generator busduct, the switchgear, and every ' ...
   '6.6&nbsp;kV feeder are modelled at zero impedance because no impedance for ' ...
   'them exists anywhere in the source documents, so they contribute exactly ' ...
   'nothing to this number and no voltage drop either. The real plant loses ' ...
   'more. How much more cannot be estimated from the data available, and putting ' ...
   'a per-metre figure from a handbook into the model would produce a larger ' ...
   'number that was no more true.</p>\n']);
um_img(fid, ctx.outDir, 'line_loading.png', ...
    'Branch loading across the four cases, from the solved branch flows.');

% ------------------------------------------------------------ 9.6 residuals
w('<h3>9.6 The residual check &mdash; why convergence is not the evidence</h3>\n');
w(['<p>A Newton-Raphson solve reports convergence when <i>its own</i> mismatch ' ...
   'falls below <i>its own</i> tolerance. That is a statement about the solver, ' ...
   'not about the network: a model with a component connected to the wrong bus ' ...
   'converges perfectly well, and answers a different question. So the solution ' ...
   'was checked from outside. At every bus, the injection the solver reports was ' ...
   'compared against the branch flows rebuilt independently from the solved ' ...
   'voltages. Table&nbsp;%d is the result.</p>\n'], ctx.t_res);
rad = []; lup = [];
ids = {D.cases.ID};
for k = 1:height(ctx.SUM)
    R = ctx.RES(strcmp(ctx.RES.Case, ctx.SUM.Case{k}), :);
    if isempty(R), continue, end
    m  = max(R.Residual_MVA);
    ic = find(strcmp(ids, ctx.SUM.Case{k}), 1);   % match by ID, never by row order
    if ~isempty(ic) && D.cases(ic).GAT_in
        lup(end+1) = m;                                                   %#ok<AGROW>
    else
        rad(end+1) = m;                                                   %#ok<AGROW>
    end
end
if isempty(rad) || isempty(lup)
    w(['<p class="warn">The residual tables could not be separated into radial ' ...
       'and looped cases, so the comparison below was not made. The per-bus ' ...
       'detail is in <code>results/load_flow/residuals.csv</code>.</p>\n']);
else
w(['<p>The worst disagreement anywhere in the radial cases is %.1e&nbsp;MVA, ' ...
   'which against a %.0f&nbsp;MVA plant is arithmetic noise &mdash; the two ' ...
   'calculations agree to about %.0f significant figures. In the looped cases it ' ...
   'is larger, %.1e&nbsp;MVA, and that difference has a cause worth ' ...
   'stating.</p>\n'], max(rad), S1.S_GSUT_MVA, ...
   floor(log10(S1.S_GSUT_MVA/max(rad))), max(lup));
w(['<p>The bus coupler and the switchgear bays are modelled as ideal connections ' ...
   'with no impedance. An independent rebuild works from voltages, and the flow ' ...
   'through a zero-impedance element cannot be recovered from the voltages at its ' ...
   'ends &mdash; they are equal by construction. In a radial network that costs ' ...
   'nothing, because there is only one path and its flow follows from the load. ' ...
   'In a looped network the division between two paths is exactly what a ' ...
   'zero-impedance element hides, so the rebuild at those buses is slightly ' ...
   'incomplete and the residual records it. It is a limitation of the check, not ' ...
   'a defect in the solve, and at %.0e&nbsp;MVA it does not affect any figure ' ...
   'reported to the precision used here.</p>\n'], max(lup));
end
nNode = sum(cellfun(@(s) isempty(strtrim(s)), ...
            ctx.BUS.Merged_into(strcmp(ctx.BUS.Case, c1))));
w(['<p class="note">All %d cases converge in %d iterations. For a %d-node ' ...
   'network with quadratic convergence that is what a well-posed problem looks ' ...
   'like. A solve of this size that needed twenty iterations, or that needed the ' ...
   'tolerance relaxed, would be a symptom to investigate rather than a result to ' ...
   'report &mdash; and no tolerance was relaxed and no parameter was adjusted to ' ...
   'obtain convergence in any case in this study.</p>\n'], ...
   height(ctx.SUM), max(ctx.SUM.Iterations), nNode);

% ------------------------------------------------------------ 9.7 angles
w('<h3>9.7 The bus angles, and the vector-group check hidden in them</h3>\n');
B1 = ctx.BUS(strcmp(ctx.BUS.Case, c1), :);
a230 = B1.Angle_deg(strcmp(B1.Bus, 'B230_1'));
a22  = B1.Angle_deg(strcmp(B1.Bus, 'B22'));
a66  = B1.Angle_deg(strcmp(B1.Bus, 'B6_6'));
w(['<p>The angle column of Table&nbsp;%d looks alarming at first reading: the ' ...
   '22&nbsp;kV generator bus sits %.1f&deg; from the 230&nbsp;kV bus. A power ' ...
   'transfer angle of that size across a single transformer would be extreme. ' ...
   'Almost all of it is not a transfer angle at all &mdash; it is the fixed phase ' ...
   'shift of the winding connection, and separating the two turns the angle ' ...
   'column into a validation of the nameplate data:</p>\n'], ...
   ctx.t_bus, a22(1)-a230(1));
gsd = D.tx(strcmp({D.tx.Name}, 'GSUT'));
uad = D.tx(strcmp({D.tx.Name}, 'UAT'));
d1 = (a22(1)-a230(1)) + 30;      % YNd1  : LV lags HV by 30 deg
d2 = (a66(1)-a22(1)) - 30;       % Dyn11 : LV leads HV by 30 deg
um_code(fid, sprintf([ ...
    'GSUT  %-8s  vector group %-8s  ->  nameplate shift 30 deg\n' ...
    '  solved  angle(22 kV) - angle(230 kV)  = %8.4f deg\n' ...
    '  remove the group shift               = %8.4f deg   <- power transfer\n' ...
    '  sign: LV leads HV, so power flows LV -> HV  (generator exporting)\n\n' ...
    'UAT   %-8s  vector group %-8s  ->  nameplate shift 30 deg\n' ...
    '  solved  angle(6.6 kV) - angle(22 kV) = %8.4f deg\n' ...
    '  remove the group shift               = %8.4f deg   <- power transfer\n' ...
    '  sign: LV lags HV, so power flows HV -> LV  (board being fed)'], ...
    gsd.KKS, gsd.VectorGroup, a22(1)-a230(1), d1, ...
    uad.KKS, uad.VectorGroup, a66(1)-a22(1), d2));
w(['<p>Both residues come out at a few degrees, in the direction the power is ' ...
   'known to be flowing. That is the check: had a vector group been entered ' ...
   'wrongly &mdash; a group index off by one, or a star-delta the wrong way round ' ...
   '&mdash; the residue would not be a few degrees but tens of degrees, and it ' ...
   'would appear here rather than quietly distorting the loop division in the ' ...
   'cases where the bay is closed. In a radial network a wrong group is harmless ' ...
   'bookkeeping; in the looped cases it would manufacture circulating power that ' ...
   'was pure artefact, which is why it is worth checking explicitly before ' ...
   'believing section&nbsp;9.4.</p>\n']);
w(['<p class="sl">The 230&nbsp;kV grid source is the angle reference for the whole ' ...
   'network, so its angle is zero by definition and every other angle in the ' ...
   'table is relative to it. Only differences carry meaning.</p>\n']);
w('</section>\n');

ctx = lr_part_quest(fid, ctx);
end
