function ctx = lr_part_data(fid, ctx)
%LR_PART_DATA  Sections 7-8: the numbered data tables, and one worked calculation.

w = @(varargin) fprintf(fid, varargin{:});
D = ctx.D;

% ================================================================ 7 tables
w('<section id="r7"><h2>7. Data tables</h2>\n');

% ---- 7.1 equipment parameters -----------------------------------------------
w('<h3>7.1 Equipment parameters entered into the model</h3>\n');
w(['<p>These are inputs, not results. Every one of them is on a nameplate or a ' ...
   'data sheet in the document set, except where the status column says ' ...
   'otherwise.</p>\n']);

ctx = lr_cap(fid, ctx, 'Generator G1 (Siemens SGen5-2000H) as entered');
g = D.gen(1);
w('<table class="num"><thead><tr><th>Quantity</th><th>Symbol</th><th>Value</th><th>Unit</th></tr></thead><tbody>\n');
gr = { 'Nominal terminal voltage',        'V_n',      g.Vnom_V/1000,  'kV'
       'Apparent power, 50 &deg;C H2',    'S_n',      g.Snom_MVA,     'MVA'
       'Apparent power, 30 &deg;C H2',    'S_max',    g.Smax_MVA,     'MVA'
       'Rated power factor',              'cos phi',  g.pf,           '&mdash;'
       'Rated stator current',            'I_n',      g.Inom_A,       'A'
       'Synchronous reactance',           'x_d',      g.xd_pct,       '%'
       'Transient reactance',             'x_d''',    g.xdp_pct,      '%'
       'Subtransient reactance',          'x_d"',     g.xdpp_pct,     '%' };
for k = 1:size(gr,1)
    w('<tr><td>%s</td><td class="tag">%s</td><td>%g</td><td>%s</td></tr>\n', gr{k,:});
end
w('</tbody></table>\n');
w(['<p class="sl">The three reactances are entered into the dataset for the ' ...
   'later short-circuit stage. A balanced load flow uses none of them: the ' ...
   'machine appears to the solve as a specified real power at a specified ' ...
   'terminal voltage.</p>\n']);

ctx = lr_cap(fid, ctx, 'The three transformers as entered');
w(['<table class="num"><thead><tr><th>Transformer</th><th>KKS</th>' ...
   '<th>HV / LV<br>kV</th><th>Vector<br>group</th><th>Cooling stages<br>MVA</th>' ...
   '<th>z<br>%%</th><th>on<br>MVA</th><th>R<br>%%</th><th>X<br>%%</th>' ...
   '<th>X/R</th></tr></thead><tbody>\n']);
for i = 1:numel(D.tx)
    t = D.tx(i);
    st = strjoin(arrayfun(@(x) sprintf('%g', x), t.S_MVA, 'UniformOutput', false), ' / ');
    w(['<tr><td><b>%s</b></td><td class="tag">%s</td><td>%g / %g</td>' ...
       '<td class="tag">%s</td><td>%s</td><td>%.4g</td><td>%g</td>' ...
       '<td>%.4g</td><td>%.4f</td><td>%.1f</td></tr>\n'], ...
       t.Name, t.KKS, t.V_HV_V/1000, t.V_LV_V/1000, um_esc(t.VectorGroup), ...
       st, t.Z_pct, t.S_rating_MVA, t.R_pct, t.X_pct, t.XR_ratio);
end
w('</tbody></table>\n');
w(['<p class="sl">The reactance column is derived, not read: X = sqrt(z&sup2; ' ...
   '&minus; R&sup2;) from the nameplate impedance and the nameplate resistance. ' ...
   'The resistance was independently cross-checked against the measured load ' ...
   'loss divided by the rating, which is a different route to the same ' ...
   'number.</p>\n']);

ctx = lr_cap(fid, ctx, 'External grid equivalent as entered');
gd = D.grid;
w('<table class="num"><thead><tr><th>Quantity</th><th>Value</th><th>Unit</th><th>Status</th></tr></thead><tbody>\n');
grd = { 'Nominal voltage',                gd.Vnom_V/1000, 'kV',  'verified from the drawings'
        'Short-circuit current used',      gd.Isc_kA,      'kA',  '<b>estimated</b> Siemens §2.4 source quantity (equipment ratings separate)'
        'Implied short-circuit level',     gd.Ssc_MVA,     'MVA', 'derived from the line above, and no stronger than it'
        'Series resistance',               gd.R_ohm,       '&Omega;', 'assumed zero &mdash; X/R is undocumented' };
for k = 1:size(grd,1)
    w('<tr><td>%s</td><td>%.4g</td><td>%s</td><td>%s</td></tr>\n', grd{k,:});
end
w('</tbody></table>\n');

ctx = lr_cap(fid, ctx, 'Auxiliary load as entered, and how it is allocated');
w(['<table class="num"><thead><tr><th>Load</th><th>Bus</th><th>P<br>MW</th>' ...
   '<th>Q<br>MVAr</th><th>In the model</th></tr></thead><tbody>\n']);
for i = 1:numel(D.loads)
    L = D.loads(i);
    if L.Model_included, inc = 'yes'; else, inc = '<b>no</b> &mdash; rating not documented'; end
    if isnan(L.P_MW), ps = '&mdash;'; qs = '&mdash;';
    else, ps = sprintf('%.3f', L.P_MW); qs = sprintf('%.3f', L.Q_MVAr); end
    w('<tr><td>%s</td><td class="tag">%s</td><td>%s</td><td>%s</td><td>%s</td></tr>\n', ...
      um_esc(L.Label), um_esc(L.Bus), ps, qs, inc);
end
w('</tbody></table>\n');
w(['<p class="warn"><b>The split between the three boards is an assumption, ' ...
   'and it is labelled one.</b> The total auxiliary demand and its power factor ' ...
   'are documented; the division of that total between the individual 6.6&nbsp;' ...
   'kV boards is not stated in the source set in a form that could be entered ' ...
   'directly. Because the three boards are solved as one node &mdash; the ' ...
   'feeder impedances between them are not documented either &mdash; the split ' ...
   'has no effect whatever on any result in this report. It is recorded in ' ...
   '<code>matlab/data/assumptions/</code> so that it becomes a real question ' ...
   'the moment feeder impedances are obtained.</p>\n']);

% ---- 7.2 the cases ----------------------------------------------------------
w('<h3>7.2 The operating cases solved</h3>\n');
w(['<p>Two things could not be settled from the documents: how much the unit is ' ...
   'dispatching, and whether the station auxiliary transformer bay is closed ' ...
   'while the unit runs. Rather than choose, both were kept. Two independent ' ...
   'choices give four cases, and reporting only two would confound the dispatch ' ...
   'effect with the transformer effect so that neither could be ' ...
   'attributed.</p>\n']);
ctx = lr_cap(fid, ctx, 'The case matrix');
w(['<table><thead><tr><th>Case</th><th>Dispatch</th><th>Station aux ' ...
   'transformer</th><th>Network</th><th>What it isolates</th>' ...
   '</tr></thead><tbody>\n']);
iso = { 'Base case &mdash; maximum export and maximum step-up loading'
        'The effect of the station transformer, versus LF1'
        'The effect of dispatch alone, versus LF1'
        'Completes the matrix so the two effects can be separated' };
for i = 1:numel(D.cases)
    C = D.cases(i);
    if C.GAT_in, gat = 'in service'; else, gat = 'out of service'; end
    if i <= numel(iso), what = iso{i}; else, what = '&mdash;'; end
    w(['<tr><td><b>%s</b></td><td>%s, %.2f MW</td><td>%s</td><td>%s</td>' ...
       '<td>%s</td></tr>\n'], C.ID, C.Gen_scenario, C.Gen_P_MW, gat, ...
       C.Topology, what);
end
w('</tbody></table>\n');

% ---- 7.3 results ------------------------------------------------------------
w('<h3>7.3 Solved results</h3>\n');

ctx = lr_cap(fid, ctx, 'System summary &mdash; the power balance of the whole plant');
ctx.t_sum = ctx.tno;
w(['<table class="num"><thead><tr><th>Case</th><th>P gen<br>MW</th>' ...
   '<th>Q gen<br>MVAr</th><th>P aux<br>MW</th><th>P loss<br>MW</th>' ...
   '<th>P export<br>MW</th><th>Q export<br>MVAr</th><th>Loss<br>%% of gen</th>' ...
   '<th>Iter</th></tr></thead><tbody>\n']);
for k = 1:height(ctx.SUM)
    r = ctx.SUM(k,:);
    w(['<tr><td><b>%s</b></td><td>%.3f</td><td>%.3f</td><td>%.3f</td>' ...
       '<td>%.4f</td><td>%.3f</td><td>%.3f</td><td>%.4f</td><td>%d</td></tr>\n'], ...
       r.Case{1}, r.P_gen_MW, r.Q_gen_MVAr, r.P_aux_MW, r.P_loss_MW, ...
       r.P_export_MW, r.Q_export_MVAr, r.Loss_pct_of_gen, r.Iterations);
end
w('</tbody></table>\n');
w(['<p class="sl">A negative reactive export means the plant is <i>absorbing</i> ' ...
   'reactive power from the grid at the point of connection.</p>\n']);

ctx = lr_cap(fid, ctx, 'Bus voltages and angles, every bus in every case');
ctx.t_bus = ctx.tno;
w(['<table class="num"><thead><tr><th>Case</th><th>Bus</th><th>Base<br>kV</th>' ...
   '<th>V<br>pu</th><th>V<br>kV</th><th>Angle<br>deg</th><th>P inj<br>MW</th>' ...
   '<th>Q inj<br>MVAr</th></tr></thead><tbody>\n']);
for k = 1:height(ctx.BUS)
    r = ctx.BUS(k,:);
    if isnan(r.P_inj_MW), ps = '&mdash;'; qs = '&mdash;';
    else, ps = sprintf('%.3f', r.P_inj_MW); qs = sprintf('%.3f', r.Q_inj_MVAr); end
    nm = um_esc(r.Bus{1});
    if ~isempty(strtrim(r.Merged_into{1}))
        nm = sprintf('%s <span class="sl">(node of %s)</span>', nm, ...
                     um_esc(strtrim(r.Merged_into{1})));
    end
    w(['<tr><td>%s</td><td>%s</td><td>%g</td><td>%.6f</td><td>%.4f</td>' ...
       '<td>%.4f</td><td>%s</td><td>%s</td></tr>\n'], ...
       r.Case{1}, nm, r.Vbase_V/1000, r.V_pu, r.V_kV, r.Angle_deg, ps, qs);
end
w('</tbody></table>\n');
w(['<p class="warn"><b>The 6.6&nbsp;kV bus voltage is reported on two bases, ' ...
   'because the documents disagree about which base is correct.</b> The system ' ...
   'is nominally 6.6&nbsp;kV; the transformer windings that feed it are rated ' ...
   '6.9&nbsp;kV. The table above uses the 6.6&nbsp;kV system nominal. Against ' ...
   'the 6.9&nbsp;kV winding rating the same solved voltage reads about 4.5&nbsp;' ...
   '%% lower. Both figures are in ' ...
   '<code>results/load_flow/bus_results.csv</code>, in the ' ...
   '<code>V_pu</code> and <code>V_pu_alt_base</code> columns, and neither is ' ...
   'presented as the answer.</p>\n']);
um_img(fid, ctx.outDir, 'bus_voltage_profile.png', ...
    'Bus voltage profile, all four cases.');

ctx = lr_cap(fid, ctx, 'Generator operating point');
ctx.t_gen = ctx.tno;
w(['<table class="num"><thead><tr><th>Case</th><th>P<br>MW</th>' ...
   '<th>Q<br>MVAr</th><th>S<br>MVA</th><th>pf</th><th>I<br>A</th>' ...
   '<th>%% of 458 MVA</th><th>%% of 518 MVA</th></tr></thead><tbody>\n']);
for k = 1:height(ctx.GEN)
    r = ctx.GEN(k,:);
    w(['<tr><td>%s</td><td>%.3f</td><td>%.3f</td><td>%.3f</td><td>%.4f</td>' ...
       '<td>%.1f</td><td>%.2f</td><td>%.2f</td></tr>\n'], ...
       r.Case{1}, r.P_MW, r.Q_MVAr, r.S_MVA, r.PowerFactor, r.I_A, ...
       r.Loading_pct_458MVA_50C, r.Loading_pct_518MVA_30C);
end
w('</tbody></table>\n');
w(['<p class="note"><b>The reactive output is a result, and it is unconstrained.</b> ' ...
   'The machine''s capability curve is not in the document set, so no reactive ' ...
   'limit was imposed on the solve. The solved reactive output must therefore be ' ...
   'checked against the capability curve when that curve is obtained &mdash; the ' ...
   'model will not refuse an operating point the machine could not actually ' ...
   'hold.</p>\n']);

ctx = lr_cap(fid, ctx, 'Transformer flows, losses and loading against each cooling stage');
ctx.t_tx = ctx.tno;
w(['<table class="num"><thead><tr><th>Case</th><th>Transformer</th>' ...
   '<th>S LV<br>MVA</th><th>S HV<br>MVA</th><th>P loss<br>MW</th>' ...
   '<th>Q loss<br>MVAr</th><th>I HV<br>A</th><th>Lowest stage<br>%%</th>' ...
   '<th>Highest stage<br>%%</th></tr></thead><tbody>\n']);
for k = 1:height(ctx.TX)
    r = ctx.TX(k,:);
    cls = ''; if r.Loading_pct_lowest_stage > 100, cls = ' class="bad"'; end
    w(['<tr><td>%s</td><td>%s</td><td>%.3f</td><td>%.3f</td><td>%.4f</td>' ...
       '<td>%.4f</td><td>%.2f</td><td%s>%.2f</td><td>%.2f</td></tr>\n'], ...
       r.Case{1}, um_esc(r.Transformer{1}), r.S_LV_MVA, r.S_HV_MVA, ...
       r.P_loss_MW, r.Q_loss_MVAr, r.I_HV_A, cls, ...
       r.Loading_pct_lowest_stage, r.Loading_pct_highest_stage);
end
w('</tbody></table>\n');
w(['<p>Figures shown in red exceed the nameplate rating of the lowest cooling ' ...
   'stage. What that does and does not mean is section&nbsp;9.</p>\n']);
um_img(fid, ctx.outDir, 'transformer_loading.png', ...
    'Transformer loading against every cooling stage, all four cases.');

ctx = lr_cap(fid, ctx, 'Independent check &mdash; worst power-balance residual per case');
ctx.t_res = ctx.tno;
w(['<table class="num"><thead><tr><th>Case</th><th>Worst bus</th>' ...
   '<th>Residual<br>MVA</th><th>As a fraction of the plant output</th>' ...
   '</tr></thead><tbody>\n']);
for k = 1:height(ctx.SUM)
    cs = ctx.SUM.Case{k};
    R  = ctx.RES(strcmp(ctx.RES.Case, cs), :);
    [mx, im] = max(R.Residual_MVA);
    w('<tr><td><b>%s</b></td><td class="tag">%s</td><td>%.3g</td><td>%.2g</td></tr>\n', ...
      cs, um_esc(R.Bus{im}), mx, mx/ctx.SUM.P_gen_MW(k));
end
w('</tbody></table>\n');
w(['<p>At every bus, in every case, the injection the solver reports was ' ...
   'compared against the sum of the branch flows rebuilt from the solved ' ...
   'voltages outside the solver. This is the table that licenses the rest: the ' ...
   'largest disagreement anywhere is negligible against the quantities being ' ...
   'reported. The per-bus detail is ' ...
   '<code>results/load_flow/residuals.csv</code>.</p>\n']);
um_img(fid, ctx.outDir, 'power_balance.png', ...
    'Power balance of the plant, all four cases.');
w('</section>\n');

% ================================================================ 8 sample calc
ctx = lr_part_calc(fid, ctx);
end
