function ctx = lr_part_calc(fid, ctx)
%LR_PART_CALC  Section 8: calculations worked by hand against the solver.
%
%   Every figure below is computed here, in this file, from the dataset and from
%   the solved CSVs - and then compared against what the study reports. That is
%   the point: a sample calculation that is typed in from a previous run proves
%   nothing, because it cannot fail. These can fail, and if one ever does the
%   difference column will say so on the page instead of in silence.

w = @(varargin) fprintf(fid, varargin{:});
D = ctx.D;

c1 = ctx.SUM.Case{1};
S1 = ctx.SUM(strcmp(ctx.SUM.Case, c1), :);
TXg = ctx.TX(strcmp(ctx.TX.Case, c1) & contains(ctx.TX.Transformer, 'GSUT'), :);
gsut = D.tx(strcmp({D.tx.Name}, 'GSUT'));

w('<section id="r8"><h2>8. Sample calculation</h2>\n');
w(['<p>Worked on the generator step-up transformer in case <b>%s</b>, because ' ...
   'it carries the whole plant output and is the component whose loading turns ' ...
   'out to matter. Each step ends with the figure the study reports, so the ' ...
   'arithmetic is checked rather than illustrated.</p>\n'], c1);

% ---------------------------------------------------------------- 8.1 base
w('<h3>8.1 Converting the transformer impedance to the study base</h3>\n');
w(['<p>The nameplate quotes the impedance on the transformer''s own rating. The ' ...
   'study reports on a common base, so it must be converted.</p>\n']);
Zown = gsut.Z_pct/100;
Zstd = Zown * (D.base.Sbase_MVA/gsut.S_rating_MVA) * 1;   % same voltage base
Zb230 = (gsut.V_HV_V/1000)^2 / D.base.Sbase_MVA;
um_code(fid, sprintf([ ...
    'nameplate      z = %.4g %%  on  %g MVA  (the highest cooling stage)\n' ...
    'study base       S_base = %g MVA,  V_base = %g kV (unchanged)\n\n' ...
    '   Z_pu(study) = Z_pu(own) . (S_base / S_own) . (V_own / V_base)^2\n' ...
    '               = %.6f . (%g / %g) . 1\n' ...
    '               = %.6f pu\n\n' ...
    'and in ohms, referred to the 230 kV side:\n\n' ...
    '   Z_base = V_base^2 / S_base = %g^2 / %g = %.4f ohm\n' ...
    '   Z      = %.6f . %.4f = %.4f ohm'], ...
    gsut.Z_pct, gsut.S_rating_MVA, D.base.Sbase_MVA, gsut.V_HV_V/1000, ...
    Zown, D.base.Sbase_MVA, gsut.S_rating_MVA, Zstd, ...
    gsut.V_HV_V/1000, D.base.Sbase_MVA, Zb230, Zstd, Zb230, Zstd*Zb230));
w(['<p>The impedance entered into the block is in per-unit on the ' ...
   'transformer''s own rating, which is what the block expects; the conversion ' ...
   'above is what makes the number comparable with the rest of the study. ' ...
   'Getting this backwards &mdash; entering %.4g&nbsp;pu where %.4g&nbsp;pu was ' ...
   'meant &mdash; would understate the transformer''s impedance by a factor of ' ...
   'about %.1f and is the single easiest mistake to make in a load flow.</p>\n'], ...
   Zstd, Zown, gsut.S_rating_MVA/D.base.Sbase_MVA);

% ---------------------------------------------------------------- 8.2 current
w('<h3>8.2 High-voltage current from the solved flow</h3>\n');
Bhv = ctx.BUS(strcmp(ctx.BUS.Case, c1) & strcmp(ctx.BUS.Bus, TXg.To_bus{1}), :);
if isempty(Bhv)
    w(['<p class="warn">The high-voltage bus of the step-up transformer could ' ...
       'not be located in <code>bus_results.csv</code>, so this step was not ' ...
       'worked.</p>\n']);
else
    Vhv_kV = Bhv.V_kV(1);
    Icalc  = TXg.S_HV_MVA(1)*1e6 / (sqrt(3)*Vhv_kV*1000);
    Inom   = TXg.S_HV_MVA(1)*1e6 / (sqrt(3)*gsut.V_HV_V);
    um_code(fid, sprintf([ ...
        'solved flow at the HV winding      S = %.4f MVA\n' ...
        'solved voltage at that bus         V = %.6f pu . %g kV = %.4f kV\n\n' ...
        '   I = S / ( sqrt(3) . V )\n' ...
        '     = %.4f e6 / ( 1.732051 . %.4f e3 )\n' ...
        '     = %.2f A\n\n' ...
        'reported in transformer_results.csv    %.2f A\n' ...
        'difference                             %.4f A\n\n' ...
        'Using the NOMINAL 230 kV instead of the solved %.4f kV would give\n' ...
        '%.2f A - low by %.2f A. The current follows the voltage the network\n' ...
        'actually settles at, not the voltage on the nameplate.'], ...
        TXg.S_HV_MVA(1), Bhv.V_pu(1), Bhv.Vbase_V(1)/1000, Vhv_kV, ...
        TXg.S_HV_MVA(1), Vhv_kV, Icalc, TXg.I_HV_A(1), ...
        Icalc - TXg.I_HV_A(1), Vhv_kV, Inom, Icalc - Inom));
    w(['<p>Against the 3150&nbsp;A bus-coupler/busbar module rating (bays are 2000 A modules; ' ...
       'conductor ampacity MISSING) this is ' ...
       'about %.0f&nbsp;%%. The 230&nbsp;kV switchgear is not the constraint ' ...
       'anywhere in this study.</p>\n'], 100*Icalc/3150);
end

% ---------------------------------------------------------------- 8.3 loading
w('<h3>8.3 Loading against each cooling stage</h3>\n');
w(['<p>This is the step that changes the conclusion, and it is the reason the ' ...
   'study reports loading against every stage rather than only the top ' ...
   'one.</p>\n']);
stg  = gsut.S_MVA;
Sin  = max(TXg.S_LV_MVA(1), TXg.S_HV_MVA(1));   % input winding: the larger flow
Sout = min(TXg.S_LV_MVA(1), TXg.S_HV_MVA(1));
if TXg.S_LV_MVA(1) >= TXg.S_HV_MVA(1)
    side = sprintf('%g kV, generator side', gsut.V_LV_V/1000);
else
    side = sprintf('%g kV, grid side', gsut.V_HV_V/1000);
end
txt = sprintf('winding apparent power (input winding, %s)   S = %.4f MVA\n\n', ...
              side, Sin);
for k = 1:numel(stg)
    txt = [txt sprintf('   %-5s %4g MVA :  %.4f / %g = %6.2f %%\n', ...
           gsut.Cooling{k}, stg(k), Sin, stg(k), 100*Sin/stg(k))];           %#ok<AGROW>
end
txt = [txt sprintf(['\nreported, lowest stage   %.2f %%\n' ...
                    'reported, highest stage  %.2f %%'], ...
        TXg.Loading_pct_lowest_stage(1), TXg.Loading_pct_highest_stage(1))];
um_code(fid, txt);
w(['<p class="sl">The apparent power used is the one on whichever of the two ' ...
   'windings carries more, which is always the <i>input</i> winding, because the ' ...
   'transformer''s own losses have not yet been subtracted from it. In this ' ...
   'transformer power flows upward, so that is the %g&nbsp;kV generator-side ' ...
   'winding; in the two auxiliary transformers power flows downward into the ' ...
   'board and it is the high-voltage winding instead. Taking the output winding ' ...
   'would understate the loading of the lowest stage by about %.2f percentage ' ...
   'points.</p>\n'], gsut.V_LV_V/1000, 100*(Sin-Sout)/stg(1));

% ---------------------------------------------------------------- 8.4 balance
w('<h3>8.4 The plant power balance</h3>\n');
w(['<p>Nothing in a load flow is more worth checking than this, because it is ' ...
   'the one identity that must hold exactly and does not depend on any ' ...
   'parameter being right.</p>\n']);
um_code(fid, sprintf([ ...
    'generated                     %+10.4f MW\n' ...
    'exported to the grid          %-10.4f MW\n' ...
    '                              -----------\n' ...
    'retained in the plant         %+10.4f MW\n\n' ...
    'auxiliary load                %+10.4f MW\n' ...
    'transformer losses            %+10.4f MW\n' ...
    '                              -----------\n' ...
    'accounted for                 %+10.4f MW\n\n' ...
    'closure error                 %+10.2e MW'], ...
    S1.P_gen_MW, S1.P_export_MW, S1.P_gen_MW - S1.P_export_MW, ...
    S1.P_aux_MW, S1.P_loss_MW, S1.P_aux_MW + S1.P_loss_MW, ...
    (S1.P_gen_MW - S1.P_export_MW) - (S1.P_aux_MW + S1.P_loss_MW)));
w(['<p>This is also the answer to the question the powergui summary block ' ...
   'provokes on screen. That block nets <i>all</i> generation, and the slack bus ' ...
   'is generation too &mdash; a negative one, because it absorbs the export ' ...
   '&mdash; so it reports a total generation of about %.2f&nbsp;MW for a plant ' ...
   'dispatching %.2f&nbsp;MW. The small number is the auxiliary load plus the ' ...
   'losses, and it is exactly the figure above.</p>\n'], ...
   S1.P_gen_MW - S1.P_export_MW, S1.P_gen_MW);

% ---------------------------------------------------------------- 8.5 losses
w('<h3>8.5 Where the losses arise</h3>\n');
T1 = ctx.TX(strcmp(ctx.TX.Case, c1), :);
txt = '';
for k = 1:height(T1)
    txt = [txt sprintf('%-22s %9.4f MW\n', T1.Transformer{k}, T1.P_loss_MW(k))]; %#ok<AGROW>
end
txt = [txt sprintf(['%-22s ---------\n%-22s %9.4f MW\n\n' ...
                    'reported system loss   %9.4f MW\n' ...
                    'difference             %9.2e MW'], ...
        '', 'sum', sum(T1.P_loss_MW), S1.P_loss_MW, ...
        sum(T1.P_loss_MW) - S1.P_loss_MW)];
um_code(fid, txt);
w(['<p class="warn"><b>That total is a floor, not an estimate of the plant''s ' ...
   'losses.</b> It is the copper and iron loss of the transformers and nothing ' ...
   'else. The busducts, the switchgear and the 6.6&nbsp;kV feeders were modelled ' ...
   'at zero impedance because no impedance data for them exists in the source ' ...
   'set, so they contribute exactly nothing. The real plant loses somewhat ' ...
   'more, and a figure for how much more cannot be produced from the data ' ...
   'available.</p>\n']);

% ---------------------------------------------------------------- 8.6 grid
w('<h3>8.6 The grid equivalent, and why it is flagged</h3>\n');
gd = D.grid;
Sk = sqrt(3)*(gd.Vnom_V/1000)*gd.Isc_kA/1000;      % MVA, from kV and kA
Zth = (gd.Vnom_V/1000)^2 / Sk;
um_code(fid, sprintf([ ...
    'estimated source current        I_k" = %g kA      <-- Siemens §2.4\n' ...
    '                                                     ESTIMATED source quantity\n\n' ...
    '   S_k" = sqrt(3) . V . I_k" = 1.732051 . %g . %g = %.1f MVA\n' ...
    '   Z_th = V^2 / S_k"         = %g^2 / %.1f       = %.4f ohm\n\n' ...
    'entered into the model                             %.4f ohm\n' ...
    'assumed series resistance                          %g ohm\n\n' ...
    'For scale: the whole plant exports about %.0f MVA, so this equivalent\n' ...
    'says the grid is roughly %.0f times stiffer than the plant is large.'], ...
    gd.Isc_kA, gd.Vnom_V/1000, gd.Isc_kA, Sk, gd.Vnom_V/1000, Sk, Zth, ...
    gd.Z_ohm, gd.R_ohm, S1.S_GSUT_MVA, Sk/S1.S_GSUT_MVA));
w(['<p class="warn"><b>The arithmetic is exact and the input is not.</b> The ' ...
   '50 kA is the ESTIMATED Siemens §2.4 external-grid source quantity, not a PGCB ' ...
   'fault level; equipment 50 kA/1 s+3 s, 125 kA peak, 50 kA making are separate ' ...
   'EQUIPMENT RATINGS, and no ' ...
   'utility-issued short-circuit level for this busbar exists in the document ' ...
   'set. Every number in this report that depends on grid stiffness therefore ' ...
   'rests on that estimate. It was measured rather than waved away: the ' ...
   'grid impedance was varied deliberately in a sensitivity test ' ...
   '(<code>matlab/tests/test_grid_sensitivity.m</code>) and the plant-side ' ...
   'answers barely move &mdash; which is why the estimate is tolerable, and ' ...
   'is not a reason to believe the number.</p>\n']);
w('</section>\n');
end
