function um_part_read(fid, ctx)
%UM_PART_READ  Sections 5-7: reading the tool's screen, the cases, the outputs.

w = @(varargin) fprintf(fid, varargin{:});
S1 = ctx.SUM(1,:);
c1 = S1.Case{1};

% ================================================================ 5 screen
w('<section id="m5"><h2>5. Reading the tool''s own screen</h2>\n');
w(['<p>Three things in the Load Flow Analyzer window look like mistakes and are ' ...
   'not. Say each of them before somebody in the audience spots it.</p>\n']);

% ---- the node mapping, derived from the report the tool itself wrote --------
repFile = fullfile(ctx.lfDir, sprintf('%s_powergui_report.rep', c1));
[N, RS, rIter] = um_rep(repFile);

w('<h3>The buses are called <code>*1*</code> to <code>*5*</code></h3>\n');
if isempty(N)
    w(['<p class="warn">No report was found at <code>results/load_flow/%s</code>, ' ...
       'so the node mapping below could not be derived. Run ' ...
       '<code>RUN_ME solve</code> and regenerate this page.</p>\n'], ...
       sprintf('%s_powergui_report.rep', c1));
else
    M = um_map_nodes(N, ctx.BUS, c1);
    w(['<p>The tool numbers the nodes itself and does not know the plant''s ' ...
       'names. The mapping below was <b>derived</b> from the report the tool ' ...
       'wrote for case %s, matched against <code>bus_results.csv</code> on ' ...
       'three things the tool prints for itself: base voltage, bus type, and ' ...
       'solved voltage. It is re-derived every time this page is generated, ' ...
       'because the numbering is the solver''s and it changes if the network ' ...
       'does.</p>\n'], c1);
    w(['<table class="num"><thead><tr><th>Tool ID</th><th>It is</th>' ...
       '<th>Base</th><th>Type</th><th>V on screen</th><th>V in the tables</th>' ...
       '</tr></thead><tbody>\n']);
    nAmb = 0;
    for k = 1:numel(M)
        if strcmp(M(k).Status, 'matched')
            if isempty(strtrim(M(k).Label)) || strcmp(strtrim(M(k).Label), M(k).Name)
                ident = sprintf('<b>%s</b>', M(k).Name);
            else
                ident = sprintf('<b>%s</b> &mdash; %s', M(k).Name, M(k).Label);
            end
            vcsv  = sprintf('%.6f', M(k).V_pu_csv);
        else
            nAmb = nAmb + 1;
            ident = sprintf('<span class="bad">not identifiable from the report alone</span><div class="sl">%s</div>', M(k).Why);
            vcsv  = '&mdash;';
        end
        if M(k).swing
            ty = 'swing';
        elseif ~isnan(M(k).Pgen_MW) && abs(M(k).Pgen_MW) > 0.005
            ty = 'PV';
        else
            ty = 'PQ';
        end
        w('<tr><td class="tag">%s</td><td>%s</td><td>%g kV</td><td>%s</td><td>%.3f pu</td><td>%s</td></tr>\n', ...
          M(k).id, ident, M(k).base_kV, ty, M(k).V_pu_rep, vcsv);
    end
    w('</tbody></table>\n');
    w(['<p><b>The rule to use on stage, not the table:</b> there is exactly one ' ...
       '<i>swing</i> bus and that is the grid, and exactly one <i>PV</i> bus and ' ...
       'that is the generator. Find those two and the rest follow from the base ' ...
       'voltage. Never identify a bus by its index &mdash; the index is the ' ...
       'solver''s and is not stable.</p>\n']);
    if nAmb > 0
        w(['<p class="note">%d node in that case could not be pinned down from ' ...
           'the report alone, and the table says so rather than guessing. That ' ...
           'happens with the station auxiliary bay closed: the transformer''s HV ' ...
           'terminal then sits a fraction of a volt from the busbar, and at the ' ...
           'three decimals the report prints they are the same number.</p>\n'], nAmb);
    end
end

nBusRows = sum(strcmp(ctx.BUS.Case, c1));
nMerged  = sum(strcmp(ctx.BUS.Case, c1) & ~cellfun(@(s) isempty(strtrim(s)), ctx.BUS.Merged_into));
w(['<p><b>Why %d buses become %d nodes.</b> A closed breaker and a zero-impedance ' ...
   'connection are not branches to a load flow &mdash; they are identities. The ' ...
   'three 6.6 kV load nodes are one node because the feeder impedances between ' ...
   'them are not in the document set, and the two 230 kV busbars are one node ' ...
   'because the coupler is closed. The CSV keeps all %d rows so nothing looks ' ...
   'overlooked, but only the first bus of each group carries the solver''s ' ...
   'injection; the other %d name the bus they merged into and report no ' ...
   'injection of their own. Otherwise a reader could add the column up and find ' ...
   'three times the auxiliary load the plant has.</p>\n'], ...
   nBusRows, nBusRows - nMerged, nBusRows, nMerged);

% ---- trap: the 60 ------------------------------------------------------------
w('<h3>There is a <code>60</code> in the powergui dialog</h3>\n');
w(['<p>It is the FFT scope''s default frequency, not the system frequency. The ' ...
   'mask''s own label for that field reads <code>Fundamental ' ...
   '(PSBFFTSCOPE)</code> &mdash; it names the scope in its own prompt. The ' ...
   'system frequency is the <code>Frequency</code> field, and it is ' ...
   '<b>%g Hz</b>; the solved frequency is written into every results table as ' ...
   '<code>f_Hz = %g</code>.</p>\n'], ctx.D.base.f_Hz, S1.f_Hz);
w(['<p class="note">Mention this <i>before</i> anybody asks. A previous study of ' ...
   'this same plant, in CYME PSAF, was actually built at 60 Hz &mdash; that is ' ...
   'logged as one of its defects. An examiner who spots a stray 60 on your ' ...
   'screen will reasonably suspect the same mistake, and the answer is one ' ...
   'sentence long if you get there first.</p>\n']);

% ---- trap: total generation --------------------------------------------------
w('<h3>The summary says total generation is a small number</h3>\n');
if isfield(RS, 'generation')
    w(['<p>The tool''s own summary block for case %s reads <b>%.2f MW</b> of ' ...
       'total generation on a plant dispatching <b>%.2f MW</b>. It is right. The ' ...
       'summary nets <i>all</i> generation, and the grid is a generator too ' ...
       '&mdash; a negative one, because it is absorbing the export:</p>\n'], ...
       c1, RS.generation(1), S1.P_gen_MW);
    um_code(fid, sprintf(['G1                %+9.2f MW\n' ...
                          'swing bus (grid)  %+9.2f MW   the grid absorbs the export\n' ...
                          '                  ----------\n' ...
                          'total             %+9.2f MW = %.3f MW auxiliary load' ...
                          ' + %.3f MW losses\n'], ...
        S1.P_gen_MW, -S1.P_export_MW, S1.P_gen_MW - S1.P_export_MW, ...
        S1.P_aux_MW, S1.P_loss_MW));
    w(['<p>%.4f &minus; %.4f = %.4f MW, and %.3f + %.4f = %.4f MW. It is an ' ...
       'exact identity, and it is a good moment in a presentation: the ' ...
       'wrong-looking number is the auxiliary load plus the losses, and it ' ...
       'proves the balance closes.</p>\n'], ...
       S1.P_gen_MW, S1.P_export_MW, S1.P_gen_MW - S1.P_export_MW, ...
       S1.P_aux_MW, S1.P_loss_MW, S1.P_aux_MW + S1.P_loss_MW);
    if isfield(RS, 'losses') && isfield(RS, 'Zshunt_load')
        w(['<p><b>And quote the total loss, not the tool''s loss line.</b> The ' ...
           'same block reports <code>Total losses %.2f MW</code> and ' ...
           '<code>Total Zshunt load %.2f MW</code> separately: the first is the ' ...
           'series copper loss, the second is the iron and magnetising loss. ' ...
           'Together they are %.2f MW, which is the %.4f MW that ' ...
           '<code>system_summary.csv</code> reports as the loss for this ' ...
           'case.</p>\n'], RS.losses(1), RS.Zshunt_load(1), ...
           RS.losses(1) + RS.Zshunt_load(1), S1.P_loss_MW);
    end
    if ~isnan(rIter)
        w(['<p class="sl">Report read from <code>%s_powergui_report.rep</code>, ' ...
           'which records convergence in %d iterations.</p>\n'], c1, rIter);
    end
else
    w(['<p class="warn">The summary block of ' ...
       '<code>%s_powergui_report.rep</code> could not be read, so the identity ' ...
       'above was not checked against the tool''s own figures.</p>\n'], c1);
end
w('</section>\n');

% ================================================================ 6 cases
w('<section id="m6"><h2>6. The four cases</h2>\n');
w(['<p>Two questions had no single answer in the source documents, so both were ' ...
   'kept: how much the unit is dispatching, and whether the station auxiliary ' ...
   'transformer bay is closed. Two choices each gives four cases, and all four ' ...
   'are solved and reported rather than one being picked.</p>\n']);
w(['<table class="num"><thead><tr><th>Case</th><th>What it is</th>' ...
   '<th>Generated<br>MW</th><th>Exported<br>MW</th><th>Losses<br>MW</th>' ...
   '<th>230 kV<br>pu</th><th>Iter</th></tr></thead><tbody>\n']);
for k = 1:height(ctx.SUM)
    r = ctx.SUM(k,:);
    w(['<tr><td><b>%s</b></td><td>%s</td><td>%.2f</td><td>%.2f</td>' ...
       '<td>%.3f</td><td>%.5f</td><td>%d</td></tr>\n'], ...
       r.Case{1}, um_esc(r.Description{1}), r.P_gen_MW, r.P_export_MW, ...
       r.P_loss_MW, r.V_230kV_pu, r.Iterations);
end
w('</tbody></table>\n');
w(['<p>Every case carries the same auxiliary demand, %.3f MW at %.3f MVAr, and ' ...
   'the same %g MVA reporting base.</p>\n'], S1.P_aux_MW, S1.Q_aux_MVAr, S1.Sbase_MVA);

w('<h3>Transformer loading, which is where the interesting answer is</h3>\n');
w(['<p>Loading is reported against <b>every</b> cooling stage, lowest and ' ...
   'highest, not just the top one. A transformer quoted only against its ' ...
   'forced-cooling rating can look comfortable while being over its natural-' ...
   'cooling nameplate, and that is exactly what happens here.</p>\n']);
w(['<table class="num"><thead><tr><th>Case</th><th>Transformer</th>' ...
   '<th>Lowest stage %%</th><th>Highest stage %%</th></tr></thead><tbody>\n']);
for k = 1:height(ctx.TX)
    r = ctx.TX(k,:);
    cls = '';
    if r.Loading_pct_lowest_stage > 100, cls = ' class="bad"'; end
    w('<tr><td>%s</td><td>%s</td><td%s>%.2f</td><td>%.2f</td></tr>\n', ...
      r.Case{1}, r.Transformer{1}, cls, r.Loading_pct_lowest_stage, ...
      r.Loading_pct_highest_stage);
end
w('</tbody></table>\n');
w(['<p>The figures in red are above the nameplate of the lowest cooling stage. ' ...
   'What they mean, and why the unit auxiliary transformer is worst in the ' ...
   'closed-bay cases while delivering no extra power, is &sect;8 of ' ...
   '<a href="PROJECT_UPDATE.html">PROJECT_UPDATE.html</a>.</p>\n']);
um_img(fid, ctx.outDir, 'transformer_loading.png', ...
    'Transformer loading, all four cases, against each cooling stage.');
w('</section>\n');

% ================================================================ 7 outputs
w('<section id="m7"><h2>7. Where the answers are</h2>\n');
w(['<p>Everything a run produces goes under <code>results/</code> and ' ...
   '<code>docs/manual/</code>. Nothing else is written.</p>\n']);
w('<table><thead><tr><th>File</th><th>What is in it</th></tr></thead><tbody>\n');
outs = { 'results/load_flow/system_summary.csv', 'One row per case: dispatch, export, losses, the voltage at each level, the flow through each transformer, iterations, and the worst cross-check error. Start here.'
         'results/load_flow/bus_results.csv',    'Every bus: type, nominal and base voltage, solved voltage in pu and kV, angle, and the injection the solver reports. Merged buses are marked and carry no injection of their own.'
         'results/load_flow/transformer_results.csv', 'Each transformer: vector group, impedance and the rating it is quoted on, flow at both windings, losses, HV current, tap used, and loading against every cooling stage.'
         'results/load_flow/line_results.csv',   'Each branch, including the ones that carry no observable flow &mdash; those are reported as blank rather than zero, because a blank is the truth and a zero is a measurement.'
         'results/load_flow/residuals.csv',      'The cross-check. At each bus, the solver''s injection against the sum of the branch flows rebuilt outside the solver. This is the column that says whether to believe the rest.'
         'results/load_flow/*.rep',              'The powergui report for each case, as the tool wrote it. This is what the audience sees on screen.'
         'results/plots/*.png',                  'Voltage profile, power balance, transformer loading, line loading &mdash; all four cases per figure.'
         'results/diagrams/*.png',               'The single-line diagram with the solved numbers written onto it, one sheet per case.'
         'docs/manual/PROJECT_UPDATE.html',      'What the study found and what remains. The document to present.'
         'docs/manual/LAB_REPORT.html',          'The same study in the EEE 306 labsheet form: theory, the calculations worked through by hand, the result tables, discussion, report questions, and what to perform next. The document to submit.'
         'docs/manual/USER_MANUAL.html',         'This page.' };
for k = 1:size(outs,1)
    w('<tr><td><code>%s</code></td><td>%s</td></tr>\n', outs{k,1}, outs{k,2});
end
w('</tbody></table>\n');

w('<h3>One convention to know before you read a flow</h3>\n');
w(['<p>Each branch''s flow is measured <b>at its own From bus</b>, and for the ' ...
   'two auxiliary transformers the From bus is the 6.6 kV side. Flow leaving ' ...
   'that bus into the branch counts as positive, so a unit auxiliary ' ...
   'transformer that is feeding the board &mdash; delivering power ' ...
   '<i>into</i> the bus &mdash; reports a <b>negative</b> number. The sign is ' ...
   'not an error and it is not a fault direction: read the ' ...
   '<code>From_bus</code> column before reading any sign as physical.</p>\n']);
um_img(fid, ctx.outDir, 'bus_voltage_profile.png', ...
    'Bus voltages, all four cases. Every bus is within about 2 per cent of nominal.');
w('</section>\n');
end
