function um_part_run(fid, ctx)
%UM_PART_RUN  Sections 1-4 of the user manual: setting up, running, presenting.

w = @(varargin) fprintf(fid, varargin{:});
root = ctx.root;

% ================================================================ 1 before
w('<section id="m1"><h2>1. Before you begin</h2>\n');
w(['<p>The model is a Simulink / Simscape Electrical model solved by the ' ...
   'Specialized Power Systems load flow engine. It is entirely offline: no ' ...
   'internet, no licence server beyond MATLAB itself, no extra toolboxes, no ' ...
   'data files to download.</p>\n']);

w('<table><thead><tr><th>What you need</th><th>Status on the machine that generated this page</th></tr></thead><tbody>\n');
w('<tr><td>MATLAB</td><td><code>%s</code></td></tr>\n', version);
w('<tr><td>Platform</td><td><code>%s</code></td></tr>\n', computer);
chk = { 'Simulink',                                     'sim'
        'Simscape Electrical (Specialized Power Systems)', 'powergui'
        'The load flow engine',                          'power_loadflow' };
for k = 1:size(chk,1)
    if isempty(which(chk{k,2}))
        w(['<tr><td>%s</td><td class="bad">NOT FOUND &mdash; <code>%s</code> ' ...
           'does not resolve. The model cannot be solved on this machine.</td></tr>\n'], ...
           chk{k,1}, chk{k,2});
    else
        w('<tr><td>%s</td><td>present (<code>%s</code> resolves)</td></tr>\n', ...
          chk{k,1}, chk{k,2});
    end
end
w('</tbody></table>\n');

w('<h3>Where the project is</h3>\n');
um_code(fid, root);
w(['<p>If that path contains a space &mdash; this one does &mdash; it must be ' ...
   'quoted when you type it at a Windows or Git-Bash prompt. Inside MATLAB, ' ...
   'quote it as a string and it is fine. Nothing in the project stores this ' ...
   'path: every script finds the root from its own location, so the folder can ' ...
   'be moved or copied anywhere. See &sect;10.</p>\n']);

w(['<p class="note"><b>One rule.</b> The project folders are not on the MATLAB ' ...
   'path when MATLAB starts. Something has to put them there, once per session. ' ...
   'Every route in this manual does it for you &mdash; that is the reason the ' ...
   'entry points exist. If you ever see <i>Unrecognized function or ' ...
   'variable</i>, that step was skipped.</p>\n']);
w('</section>\n');

% ================================================================ 2 one command
w('<section id="m2"><h2>2. The one command</h2>\n');
w(['<p><code>RUN_ME.m</code> sits in the project root, next to the folders, ' ...
   'where somebody who has never seen the project will find it. Make the ' ...
   'project root the current folder in MATLAB and type:</p>\n']);
um_code(fid, 'RUN_ME');
w(['<p>That solves all four operating cases from the dataset, redraws every ' ...
   'figure, and regenerates this manual and the project update. It takes a few ' ...
   'minutes. It overwrites the contents of <code>results/</code> and ' ...
   '<code>docs/manual/</code> and nothing else &mdash; the dataset and the ' ...
   'source models are inputs and are never rewritten by a run.</p>\n']);

w('<table><thead><tr><th>Command</th><th>What it does</th></tr></thead><tbody>\n');
acts = { 'RUN_ME',         'solve the four cases, redraw the figures, regenerate all three documents'
         'RUN_ME check',   'report MATLAB version, toolboxes, what is already on disk, and whether <code>results/</code> can be written. Changes nothing &mdash; run this first on a new PC'
         'RUN_ME open',    'open <code>simulink/main/Ashuganj_South_Main.slx</code> ready to present'
         'RUN_ME solve',   'solve the four cases only'
         'RUN_ME figures', 'redraw the plots and the annotated diagrams only'
         'RUN_ME docs',    'regenerate this manual, the project update and the lab report from the results already on disk'
         'RUN_ME tests',   'run the validation suite'
         'RUN_ME setup',   'put the project folders on the MATLAB path and stop' };
for k = 1:size(acts,1)
    w('<tr><td><code>%s</code></td><td>%s</td></tr>\n', acts{k,1}, acts{k,2});
end
w('</tbody></table>\n');
w(['<p>Inside MATLAB, once the path is set, <code>ashuganj</code> is the same ' ...
   'command with the same arguments &mdash; <code>RUN_ME</code> is a wrapper ' ...
   'around it that also fixes the path first. Use whichever you remember.</p>\n']);
w('</section>\n');

% ================================================================ 3 rebuild
w('<section id="m3"><h2>3. The full rebuild, step by step</h2>\n');
w(['<p>Use this route when you want to see each stage separately, or when one ' ...
   'stage failed and you want to repeat only that stage. It is exactly what ' ...
   '<code>RUN_ME</code> does, typed out.</p>\n']);
um_code(fid, ['cd ''' root '''' newline ...
              'addpath(''matlab''); ashuganj_setup;' newline newline ...
              'run_load_flow_study      % solve the four cases' newline ...
              'make_load_flow_plots     % four PNGs' newline ...
              'make_annotated_diagrams  % four annotated single-line sheets' newline ...
              'build_project_update     % PROJECT_UPDATE.html' newline ...
              'build_user_manual        % USER_MANUAL.html (this page)']);

nCsv = numel(dir(fullfile(root,'results','load_flow','*.csv')));
nRep = numel(dir(fullfile(root,'results','load_flow','*.rep')));
nPng = numel(dir(fullfile(root,'results','plots','*.png')));
nDia = numel(dir(fullfile(root,'results','diagrams','*.png')));
nSlx = numel(dir(fullfile(root,'simulink','studies','*.slx')));
nTest = numel(dir(fullfile(root,'matlab','tests','test_*.m')));

w('<table><thead><tr><th>Step</th><th>What it does</th><th>What it leaves behind</th></tr></thead><tbody>\n');
steps = { 'ashuganj_setup', ...
          'Puts every project folder on the MATLAB path and creates any output folder that is missing. Must run once per MATLAB session, before anything else.', ...
          'nothing on disk except the empty output folders it creates'
          'run_load_flow_study', ...
          'Builds a fresh Simulink model for each of the four cases from the dataset, solves each one, rebuilds every branch flow independently of the solver, and cross-checks the two against each other at every bus.', ...
          sprintf('%d CSV tables and %d powergui reports in <code>results/load_flow/</code>, %d models in <code>simulink/studies/</code>', nCsv, nRep, nSlx)
          'make_load_flow_plots', ...
          'Draws the voltage profile, the power balance, and the transformer and line loading, for all four cases on one axis each.', ...
          sprintf('%d PNGs in <code>results/plots/</code>', nPng)
          'make_annotated_diagrams', ...
          'Writes the solved numbers onto a copy of the single-line diagram, one sheet per case, so a reader sees the flows on the drawing instead of in a table.', ...
          sprintf('%d PNGs in <code>results/diagrams/</code> and the matching annotated models', nDia)
          'build_project_update', ...
          'Writes the presentation document: what the model is, what was found, what is assumed, what remains.', ...
          '<code>docs/manual/PROJECT_UPDATE.html</code>'
          'build_user_manual', ...
          'Writes this page.', ...
          '<code>docs/manual/USER_MANUAL.html</code> and <code>index.html</code>' };
for k = 1:size(steps,1)
    w('<tr><td><code>%s</code></td><td>%s</td><td>%s</td></tr>\n', steps{k,:});
end
w('</tbody></table>\n');

w('<h3>The validation suite</h3>\n');
w(['<p>Optional, and the slowest step. It checks the dataset against itself and ' ...
   'the solved network against the dataset &mdash; that impedances convert ' ...
   'correctly between bases, that the transformer phase shifts have the right ' ...
   'sign, that no bus is left floating, and that the answers do not move when ' ...
   'the two weakest inputs are perturbed.</p>\n']);
um_code(fid, 'run_all_tests');
w(['<p>There are <b>%d</b> test files in <code>matlab/tests/</code>. Run this ' ...
   'after changing any parameter, and before quoting a number to anybody.</p>\n'], nTest);
w('</section>\n');

% ================================================================ 4 demo
w('<section id="m4"><h2>4. The live demonstration</h2>\n');
w(['<p>The diagram in <code>simulink/main/Ashuganj_South_Main.slx</code> is laid ' ...
   'out to be read, and it <b>solves on its own</b> &mdash; it is case LF1. So ' ...
   'the live demonstration runs on the readable drawing, not on a generated ' ...
   'study model. Its solution was compared against the generated LF1 model and ' ...
   'agrees on every node.</p>\n']);

w('<ol class="steps">\n');
w(['<li><b>Open MATLAB and wait for the prompt.</b> Make the project root the ' ...
   'current folder.</li>\n']);
w('<li><b>Open the diagram.</b> One command, which also fixes the path:\n');
um_code(fid, 'RUN_ME open');
w(['<p>Or from the Current Folder browser: <code>simulink</code> &rarr; ' ...
   '<code>main</code> &rarr; double-click <code>Ashuganj_South_Main.slx</code>. ' ...
   'The path is not set up if you do it that way, which is fine for showing the ' ...
   'diagram but not for running any script.</p></li>\n']);
w(['<li><b>Let the audience read it before you touch anything.</b> Left to ' ...
   'right is generation to grid; the auxiliary branch hangs below. Name the ' ...
   'blocks out loud: <code>G1</code>, <code>22 kV GEN BUS</code>, ' ...
   '<code>GSUT 10BAT10</code>, <code>230 kV BUS 1</code> and <code>BUS 2</code>, ' ...
   '<code>UAT 10BBT10</code>, <code>6.6 kV MV BUS</code>, ' ...
   '<code>GAT 10BBT20</code>, <code>EXT GRID</code>.</li>\n']);
w(['<li><b>Double-click <code>powergui</code></b>, top left. Show the two ' ...
   'fields that matter: <code>Simulation type</code> is <b>Continuous</b> (a ' ...
   'phasor solution, not a discretised one) and <code>Frequency</code> is ' ...
   '<b>%g Hz</b>. Show the frequency deliberately &mdash; see &sect;5.</li>\n'], ...
   ctx.D.base.f_Hz);
w('<li><b>Open the Load Flow tool.</b> Either the <i>Load Flow</i> entry in the powergui dialog, or one command, which is the reliable route on a projector:\n');
um_code(fid, ['powerLoadFlow   % takes no arguments - it reads the open model itself']);
w(['<p>Passing the model name throws <code>MATLAB:TooManyInputs</code>. Type it ' ...
   'bare.</p></li>\n']);
w(['<li><b>Press <code>Compute</code>, then <code>Report</code>.</b> It solves ' ...
   'in <b>%d iterations</b>. The report that appears is the same content as ' ...
   '<code>results/load_flow/LF1_powergui_report.rep</code>, which is already on ' ...
   'disk if the projector lets you down.</li>\n'], max(ctx.SUM.Iterations));
w(['<li><b>Read the numbers off the screen using &sect;5</b>, which explains ' ...
   'the three things in that window that look wrong and are not.</li>\n']);
w(['<li><b>Do not press <code>Add bus blocks</code>.</b> It inserts unwired ' ...
   'placeholder blocks, and the next solve then fails with <i>"is not properly ' ...
   'connected to the network"</i>. If you press it by accident: undo, and close ' ...
   'the model without saving.</li>\n']);
w('</ol>\n');

w('<h3>Showing a different case</h3>\n');
w(['<p>The main diagram is the rated case with the station auxiliary bay open. ' ...
   'For the other three, open the matching study model instead &mdash; ' ...
   'everything above applies unchanged.</p>\n']);
um_code(fid, ['open(''simulink/studies/Load_Flow_LF2.slx'')   % rated, station bay CLOSED' newline ...
              'open(''simulink/studies/Load_Flow_LF3.slx'')   % derated, bay open' newline ...
              'open(''simulink/studies/Load_Flow_LF4.slx'')   % derated, bay closed']);

w('<h3>If you would rather not run anything live</h3>\n');
w(['<p>The annotated sheets carry the solved numbers on the drawing itself. ' ...
   'They are PNGs: they open on any machine, with or without MATLAB, and they ' ...
   'are the safest thing to put on a projector.</p>\n']);
um_img(fid, ctx.outDir, 'Load_Flow_LF1_Annotated.png', ...
    ['Case LF1 &mdash; rated dispatch, station auxiliary bay open. The same ' ...
     'sheet exists for all four cases in <code>results/diagrams/</code>.']);
w('</section>\n');
end
