function um_part_care(fid, ctx)
%UM_PART_CARE  Sections 8-11: changing things, failures, portability, limits.

w = @(varargin) fprintf(fid, varargin{:});
root = ctx.root;

% ================================================================ 8 changing
w('<section id="m8"><h2>8. Changing something safely</h2>\n');
w(['<p><b>Never edit the Simulink file to change a number.</b> The models are ' ...
   'generated from the dataset, so the next run overwrites anything typed into ' ...
   'a block dialog, and in the meantime the diagram and the tables disagree ' ...
   'without saying so. Change the dataset and rebuild.</p>\n']);

w('<h3>Where the numbers live</h3>\n');
dfiles = dir(fullfile(root, 'matlab', 'data', '*.m'));
w('<table class="files"><tbody>\n');
for k = 1:numel(dfiles)
    w('<tr><td><code>matlab/data/%s</code></td><td>%s</td></tr>\n', ...
      dfiles(k).name, first_help_line(fullfile(dfiles(k).folder, dfiles(k).name)));
end
w('</tbody></table>\n');
w(['<p>Every value in those files carries where it came from: the document, the ' ...
   'page or sheet, and a status &mdash; verified from the plant, verified from ' ...
   'an engineering document, derived, assumed, estimated, missing or ' ...
   'conflicting. Keep that column truthful when you add anything. A number ' ...
   'without a source is worse than a gap, because a gap gets filled and a wrong ' ...
   'source gets trusted.</p>\n']);

w('<h3>Assumptions are kept somewhere else on purpose</h3>\n');
afiles = dir(fullfile(root, 'matlab', 'data', 'assumptions', '*.m'));
w(['<p>There are <b>%d</b> of them, in <code>matlab/data/assumptions/</code>, ' ...
   'never mixed into the verified dataset. Each one records what was assumed, ' ...
   'why, and what it affects.</p>\n'], numel(afiles));
w('<table class="files"><tbody>\n');
for k = 1:numel(afiles)
    w('<tr><td><code>%s</code></td><td>%s</td></tr>\n', ...
      erase(afiles(k).name, '.m'), ...
      first_help_line(fullfile(afiles(k).folder, afiles(k).name)));
end
w('</tbody></table>\n');
w(['<p>If you need a value that is not in the documents, add it here as an ' ...
   'assumption with its reason &mdash; do not put it in the dataset and do not ' ...
   'take a textbook figure quietly. &sect;9 of ' ...
   '<a href="PROJECT_UPDATE.html">PROJECT_UPDATE.html</a> lists what each ' ...
   'assumption is worth in the answers.</p>\n']);

w('<h3>The sequence, and the backup rule</h3>\n');
nBak = numel(dir(fullfile(root, 'simulink', 'backups', '*.slx')));
w('<ol>\n');
w(['<li><b>Back up the model first.</b> <code>simulink/backups/</code> holds ' ...
   '<b>%d</b> numbered copies. Copy <code>Ashuganj_South_Main.slx</code> to the ' ...
   'next free <code>_vNNN.slx</code> before anything else. A working model is ' ...
   'not something to lose to a bad afternoon.</li>\n'], nBak);
w('<li>Change the dataset file, keeping the source and status columns honest.</li>\n');
w('<li><code>run_all_tests</code> &mdash; the dataset checks catch a value that contradicts another one.</li>\n');
w('<li><code>run_load_flow_study</code> &mdash; solve all four cases again, not just the one you care about.</li>\n');
w(['<li>Open <code>results/load_flow/residuals.csv</code> and look at the worst ' ...
   'residual. If it grew, the change broke the agreement between the solver and ' ...
   'the independent flow calculation, and the new numbers are not to be quoted ' ...
   'yet.</li>\n']);
w('<li><code>RUN_ME docs</code> &mdash; regenerate all three documents so they match the new numbers.</li>\n');
w('</ol>\n');
w(['<p class="note"><b>Why all four cases.</b> The four differ in dispatch and ' ...
   'in whether the station auxiliary bay is closed. A parameter change that ' ...
   'looks harmless in the radial cases can move the circulating power in the ' ...
   'looped ones by much more, because there the flow is a small difference ' ...
   'between two large ones.</p>\n']);
w('</section>\n');

% ================================================================ 9 failures
w('<section id="m9"><h2>9. When it goes wrong</h2>\n');
w('<table><thead><tr><th>What you see</th><th>Why</th><th>What to do</th></tr></thead><tbody>\n');
tr = { '<code>Unrecognized function or variable</code> for any project function', ...
       'The project folders are not on the MATLAB path. This is the single most common failure and it is not a broken installation.', ...
       '<code>RUN_ME setup</code>, or <code>ashuganj setup</code> if the path is already partly there.'
       'A model opens with unsaved changes, or a build complains that a model is already open', ...
       'A previous run left a model in memory, and the builder will not overwrite an open model.', ...
       '<code>bdclose(''all'')</code>, then run again.'
       '<code>The Load Flow Bus block ... is not properly connected to the network</code>', ...
       '<code>Add bus blocks</code> was pressed in the Load Flow Analyzer. It inserts unwired placeholder blocks and the solve then refuses.', ...
       'Undo, or close the model without saving. Nothing on disk is harmed.'
       '<code>MATLAB:TooManyInputs</code> from <code>powerLoadFlow</code>', ...
       'It takes no arguments &mdash; it reads whichever model is open.', ...
       'Type <code>powerLoadFlow</code> bare.'
       'The load flow does not converge after you changed a parameter', ...
       'Usually a value in the wrong unit or on the wrong base &mdash; a per-unit impedance entered as a percentage, or an impedance left on the transformer rating instead of the study base.', ...
       'Check the value you changed and its base. Do not raise the iteration limit to force convergence: a solve that only converges when pushed is telling you the network is wrong.'
       'Numbers in a solved model do not match the CSVs', ...
       'Solving writes the solution back into the blocks, so a model that has been solved by hand is no longer in its as-built state.', ...
       'Ignore the model''s stored values and re-run <code>run_load_flow_study</code>, which rebuilds every case from the dataset before solving it.'
       'A figure or a document is missing or out of date', ...
       'The plot and document scripts read the CSVs; they do not solve anything themselves.', ...
       '<code>RUN_ME</code> for everything, or <code>RUN_ME figures</code> then <code>RUN_ME docs</code>.'
       'Nothing can be written to <code>results/</code>', ...
       'The project is being run from inside a ZIP, or from a folder marked read-only after a copy.', ...
       'Extract or copy it somewhere writable and run <code>RUN_ME check</code>, which reports writability before anything else.' };
for k = 1:size(tr,1)
    w('<tr><td>%s</td><td>%s</td><td>%s</td></tr>\n', tr{k,:});
end
w('</tbody></table>\n');
w('</section>\n');

% ================================================================ 10 portable
w('<section id="m10"><h2>10. Moving it to another PC</h2>\n');

% ---- live check: does any code line hold an absolute path? -------------------
% Two groups, kept apart on purpose. The first is what a run touches - if any of
% those held a hard-coded path the project would break the moment it was copied.
% The second is the one-off scripts that measured the solver's behaviour while
% the study was being built: they are kept as evidence, they are not on the
% MATLAB path, and nothing calls them. Several do hard-code the machine they were
% run on, which is fine for a record of a measurement and would not be fine in a
% script that has to run again elsewhere. Reporting one number for both groups
% would be the convenient answer rather than the true one.
%
% matlab/gui/ is in neither group. The interactive interface there is being built
% separately and is not part of the load flow pipeline, so this page neither
% vouches for it nor counts it against the project.
[shipN, shipTot, shipHits] = absolute_path_scan(pipeline_files(root));
[scrN,  scrTot]            = absolute_path_scan(scratch_files(root));

allf = dir(fullfile(root, '**', '*'));
allf = allf(~[allf.isdir]);

w(['<p>Copy the project folder. That is the whole procedure &mdash; any drive, ' ...
   'any directory, any machine. Nothing has to be edited afterwards, because no ' ...
   'file stores where the project lives: each script finds the root from its ' ...
   'own location.</p>\n']);
if shipN == 0
    w(['<p class="note"><b>Checked when this page was generated.</b> All %d ' ...
       'MATLAB files that a run touches &mdash; the dataset, the builders, the ' ...
       'analysis, the studies and the tests &mdash; were scanned, and ' ...
       '<b>none</b> contains an absolute path on a code line.</p>\n'], shipTot);
else
    w(['<p class="warn"><b>Checked when this page was generated:</b> %d of the ' ...
       '%d MATLAB files that a run touches contain an absolute path on a code ' ...
       'line, so the project is <b>not</b> portable until they are fixed: ' ...
       '%s</p>\n'], shipN, shipTot, strjoin(shipHits, ', '));
end
w(['<p class="sl">Comments are excluded from that scan: a few of them quote ' ...
   'where MATLAB itself is installed, which is documentation and not a ' ...
   'dependency. Separately, <code>matlab/env/</code> holds %d one-off probe ' ...
   'scripts that measured the solver''s behaviour while the study was being ' ...
   'built; %d of them name the machine they were run on. They are deliberately ' ...
   'kept off the MATLAB path, nothing calls them, and a run does not touch ' ...
   'them.</p>\n'], scrTot, scrN);

w('<h3>What to copy, and what can be thrown away</h3>\n');
w('<table><thead><tr><th>Folder</th><th>Keep it?</th></tr></thead><tbody>\n');
pt = { 'matlab/',          'Yes &mdash; the dataset and every script. This is the project. Plain text.'
       'simulink/main/',   'Yes &mdash; the diagram you present. Regenerable, but it is the readable layout.'
       'simulink/studies/','Regenerable by <code>RUN_ME solve</code>.'
       'simulink/backups/','Yes, if you value the history. Nothing reads them.'
       'data/',            'Yes &mdash; the parameter registry the dataset was built from.'
       'docs/',            'Yes &mdash; the manuals, the validation notes, and the list of data still to collect.'
       'results/',         'Regenerable by <code>RUN_ME</code>. Keep it if the recipient has no MATLAB.'
       'Labsheets/, PDFs', 'Yes &mdash; the source documents. Every parameter traces back to one of them.' };
for k = 1:size(pt,1)
    w('<tr><td><code>%s</code></td><td>%s</td></tr>\n', pt{k,1}, pt{k,2});
end
w('</tbody></table>\n');
w(['<p class="sl">The project is currently %d files, about %.0f MB in total, ' ...
   'most of it the source PDFs and the Simulink files.</p>\n'], ...
   numel(allf), sum([allf.bytes])/1e6);

w('<h3>On the new machine, in this order</h3>\n');
w('<ol>\n');
w(['<li>Install or open MATLAB with <b>Simulink</b> and <b>Simscape ' ...
   'Electrical</b>. Nothing else is needed, and no internet connection is ' ...
   'needed.</li>\n']);
w('<li>Make the project root the current folder in MATLAB.</li>\n');
w('<li>Run the environment check, which changes nothing:\n');
um_code(fid, 'RUN_ME check');
w(['<p>It reports the MATLAB version, whether the toolboxes resolve, what is ' ...
   'already on disk with its date, and whether <code>results/</code> can be ' ...
   'written.</p></li>\n']);
w('<li>Run the study:\n');
um_code(fid, 'RUN_ME');
w('</li>\n');
w('<li>Open <code>docs/manual/index.html</code>.</li>\n');
w('</ol>\n');

w('<h3>Two things worth knowing before you hand it over</h3>\n');
w(['<p><b>The <code>.slx</code> files were written by MATLAB %s.</b> Simulink ' ...
   'models are binary and are not readable by older releases. This does not ' ...
   'block anybody: the models are generated from the dataset, which is plain ' ...
   'text, so <code>RUN_ME solve</code> rebuilds them on any release that has ' ...
   'Simscape Electrical. If a block name has changed between releases the ' ...
   'builder will say so rather than silently substituting one.</p>\n'], version);
w(['<p><b><code>docs/manual/</code> stands on its own.</b> The three HTML pages ' ...
   'and their figures are in that one folder with no external references, so it ' ...
   'can be zipped, emailed or put on a phone and it still reads &mdash; no ' ...
   'MATLAB, no project folder, no internet.</p>\n']);
w('</section>\n');

% ================================================================ 11 limits
w('<section id="m11"><h2>11. What this study does not do</h2>\n');
w(['<p>Say this before anybody asks, because every item below is deliberate and ' ...
   'each one has a reason.</p>\n']);
w('<ul>\n');
lim = { ['<b>No faults, and no protection settings.</b> This is the load flow ' ...
         'stage. Short-circuit currents, three-phase and unbalanced faults, ' ...
         'relay grading and coordination are the next stages, and they need data ' ...
         'this stage did not &mdash; sequence impedances, relay models, CT and VT ' ...
         'ratios, and the tripping curves.']
        ['<b>Balanced, positive-sequence, steady state only.</b> One phasor per ' ...
         'bus. No unbalance, no harmonics, no switching transients, no machine ' ...
         'dynamics, no stability.']
        ['<b>The losses are a floor, not an estimate.</b> They are the copper and ' ...
         'iron losses of the three transformers. The cables, busbars and bay ' ...
         'conductors have no documented impedance, so they contribute nothing. ' ...
         'The real plant loses slightly more.']
        ['<b>The grid is an equivalent, and it is the weakest number in the ' ...
         'model.</b> Its impedance was derived from the ESTIMATED Siemens §2.4 50 kA ' ...
         'source quantity because no PGCB short-circuit level for this bus was issued. ' ...
         'Equipment ratings (50 kA/1 s+3 s, 125 kA peak) are separate. ' ...
         'The sensitivity tests show the answers barely move with it, which is ' ...
         'the reason it is tolerable rather than a reason it is right.']
        ['<b>The generator''s reactive limits are not enforced.</b> The ' ...
         'capability curve was not in the document set, so the solve is not ' ...
         'bounded by one. The solved reactive output must be checked against the ' ...
         'curve when it arrives.']
        ['<b>The 400 V boards carry no demand.</b> Their loading is not in the ' ...
         'document set, so they are represented but not loaded. Whatever they ' ...
         'draw is missing from the 6.6 kV total.']
        ['<b>The voltage reference is an assumption.</b> The generator is held at ' ...
         'its nominal voltage because no operating set-point was found. Every ' ...
         'voltage in every table is relative to that choice.'] };
for k = 1:numel(lim)
    w('<li>%s</li>\n', lim{k});
end
w('</ul>\n');
w(['<p>The complete list of what is assumed, what is missing, what conflicts ' ...
   'between documents, and what has to be collected next is &sect;9 and ' ...
   '&sect;10 of <a href="PROJECT_UPDATE.html">PROJECT_UPDATE.html</a>, with the ' ...
   'long form in <code>docs/validation/</code> and ' ...
   '<code>docs/DATA_TO_COLLECT.md</code>.</p>\n']);
w('</section>\n');
end

% =====================================================================
function s = first_help_line(f)
%FIRST_HELP_LINE  The one-line summary from a function's own help text.
%   Read from the file, so a file that is renamed or rewritten cannot end up
%   described here by a stale sentence.
s = '<i>no summary line in the file</i>';
L = readlines(f);
[~, base] = fileparts(f);
for i = 1:min(8, numel(L))
    t = strtrim(char(L(i)));
    if ~startsWith(t, '%'), continue, end
    t = strtrim(t(2:end));
    if isempty(t), continue, end
    [tok, rest] = strtok(t);
    if strcmpi(tok, base), t = strtrim(rest); end
    if ~isempty(t), s = um_esc(t); return, end
end
end

% =====================================================================
function f = pipeline_files(root)
%PIPELINE_FILES  Every MATLAB file a run actually executes.
%   The entry point, the dataset, the builders, the analysis, the studies and
%   the tests. These are the files that have to be portable.
f = dir(fullfile(root, '*.m'));
sub = { 'ashuganj.m', 'ashuganj_setup.m' };
for k = 1:numel(sub)
    f = [f; dir(fullfile(root, 'matlab', sub{k}))];                   %#ok<AGROW>
end
sub = { 'data', 'utilities', 'build', 'analysis', 'studies', 'tests' };
for k = 1:numel(sub)
    f = [f; dir(fullfile(root, 'matlab', sub{k}, '**', '*.m'))];      %#ok<AGROW>
end
end

% =====================================================================
function f = scratch_files(root)
%SCRATCH_FILES  The one-off probes kept as a record of what was measured.
%   Not on the MATLAB path, not called by anything, and not executed by a run.
%   matlab/gui/ is deliberately NOT included: the interactive interface there is
%   live work, not a scratch script, and it is not this study's to report on.
f = dir(fullfile(root, 'matlab', 'env', '*.m'));
end

% =====================================================================
function [nAbs, nScan, hits] = absolute_path_scan(f)
%ABSOLUTE_PATH_SCAN  Count files holding an absolute path on an executable line.
%   Comment lines are skipped: several legitimately quote where MATLAB itself is
%   installed, which is documentation and not a dependency. Only a drive letter
%   on a line that runs makes a file unportable.
%
%   The pattern requires the drive letter to open a quoted string - 'F:\...' or
%   "C:/..." - which is how a hard-coded path is actually written. Matching a
%   bare letter-colon-separator instead flags every format string that ends
%   ':\n', and a check that cries wolf gets ignored, which is worse than not
%   having one.
pat = '[''"][A-Za-z]:[\\/]';
nAbs = 0; nScan = numel(f); hits = {};
for k = 1:numel(f)
    L = readlines(fullfile(f(k).folder, f(k).name));
    bad = false;
    for i = 1:numel(L)
        t = strtrim(char(L(i)));
        if isempty(t) || startsWith(t, '%'), continue, end
        if ~isempty(regexp(t, pat, 'once')), bad = true; break, end
    end
    if bad
        nAbs = nAbs + 1;
        hits{end+1} = ['<code>' f(k).name '</code>'];                 %#ok<AGROW>
    end
end
end
