function [np, nf] = test_phase5_writer()
%TEST_PHASE5_WRITER  Unit checks for phase5_writer (Phase-5 Task 17, TDD).
%   Schema + provenance-guard checks only; hermetic (synthetic 1-2 row
%   tables into a temp dir, no production data, no production run).
%   Guards asserted:
%     - 9 CSVs + manifest.json + run_log.txt + sha256.txt written;
%     - row counts round-trip; manifest tag echoes meta.tag;
%     - sha256.txt covers 11 files (9 CSVs + manifest + run_log);
%     - empty provenance cell errors phase5_writer:provenance;
%     - empty scope cell errors phase5_writer:provenance;
%     - missing scope column errors phase5_writer:schema.
%   All errors are 'phase5'-prefixed.
T = t_case('test_phase5_writer');
[tables, meta] = tiny_tables('production');
tmpOut = fullfile(tempdir(), 'phase5_writer_test');
if exist(tmpOut, 'dir') == 7
    rmdir(tmpOut, 's');
end
W = phase5_writer(tmpOut, tables, meta);
T = T.chk(isstruct(W) && isfield(W, 'files'), 'writer returns W struct with files');
expCsv = {'phase5_device_registry.csv', 'phase5_relay_settings.csv', ...
    'phase5_fault_inputs.csv', 'phase5_relay_currents.csv', ...
    'phase5_coordination_matrix.csv', 'phase5_coordination_margins.csv', ...
    'phase5_breaker_duty.csv', 'phase5_sensitivity.csv', ...
    'phase5_validation.csv'};
for k = 1:numel(expCsv)
    T = T.chk(exist(fullfile(tmpOut, expCsv{k}), 'file') == 2, ...
        sprintf('CSV written: %s', expCsv{k}));
end
T = T.chk(exist(fullfile(tmpOut, 'manifest.json'), 'file') == 2, 'manifest.json written');
T = T.chk(exist(fullfile(tmpOut, 'run_log.txt'), 'file') == 2, 'run_log.txt written');
T = T.chk(exist(fullfile(tmpOut, 'sha256.txt'), 'file') == 2, 'sha256.txt written');
% Row-count round trip on two representative tables.
R2 = readtable(fullfile(tmpOut, 'phase5_fault_inputs.csv'));
T = T.chk(height(R2) == height(tables.faultInputs), 'fault_inputs row count round-trips');
D2 = readtable(fullfile(tmpOut, 'phase5_breaker_duty.csv'));
T = T.chk(height(D2) == height(tables.duty), 'breaker_duty row count round-trips');
% Manifest tag echo.
M = jsondecode(fileread(fullfile(tmpOut, 'manifest.json')));
T = T.chk(strcmp(M.tag, 'production'), 'manifest tag echoes meta.tag');
% sha256.txt covers 11 files.
sh = strsplit(strtrim(fileread(fullfile(tmpOut, 'sha256.txt'))), '\n');
T = T.chk(numel(sh) == 11, 'sha256.txt covers 9 CSVs + manifest + run_log (11 lines)');
% Provenance guard: empty provenance cell.
bad = tables;
bad.faultInputs.provenance{1} = '';
try
    phase5_writer(fullfile(tempdir(), 'phase5_writer_bad1'), bad, meta);
    T = T.chk(false, 'empty provenance errors');
catch ME
    T = T.chk(strcmp(ME.identifier, 'phase5_writer:provenance'), 'empty provenance errors phase5_writer:provenance');
end
% Provenance guard: empty scope cell.
bad2 = tables;
bad2.duty.scope{2} = '   ';
try
    phase5_writer(fullfile(tempdir(), 'phase5_writer_bad2'), bad2, meta);
    T = T.chk(false, 'empty scope errors');
catch ME
    T = T.chk(strcmp(ME.identifier, 'phase5_writer:provenance'), 'empty scope errors phase5_writer:provenance');
end
% Schema guard: missing scope column.
bad3 = tables;
bad3.validation = removevars(bad3.validation, 'scope');
try
    phase5_writer(fullfile(tempdir(), 'phase5_writer_bad3'), bad3, meta);
    T = T.chk(false, 'missing scope column errors');
catch ME
    T = T.chk(strcmp(ME.identifier, 'phase5_writer:schema'), 'missing scope column errors phase5_writer:schema');
end
if exist(tmpOut, 'dir') == 7
    rmdir(tmpOut, 's');
end
[np, nf] = T.done();
end

function [tables, meta] = tiny_tables(tag)
%TINY_TABLES  Minimal 1-2 row tables carrying every required writer column.
P = {'SOURCE-BACKED:unit-test'; 'SOURCE-BACKED:unit-test'};
S = {'PRIMARY'; 'PRIMARY'};
P1 = {'SOURCE-BACKED:unit-test'};
S1 = {'PRIMARY'};
reg = table({'GEN-51'; 'GIS-Q0-51'}, {'oc'; 'oc'}, {'B22-generator-bus'; '230kV-GIS'}, ...
    {'51'; '51'}, {'generator'; 'grid'}, [15000; 2000], ...
    {'SOURCE-BACKED'; 'ENGINEERING_ASSUMPTION'}, [12019; 2000], [22; 230], ...
    {'Phase-4-production-import'; 'Phase-4-production-import'}, [NaN; NaN], [NaN; NaN], ...
    {''; ''}, [NaN; NaN], [NaN; NaN], {''; ''}, {'GSUT-HV-51'; 'REMOTE-GRID-boundary'}, ...
    {''; 'GSUT-HV-51'}, {'SOURCE-BACKED:x'; 'ENGINEERING_ASSUMPTION:y'}, ...
    {'ACTIVE-STUDY'; 'ACTIVE-STUDY'}, {'PRIMARY'; 'PRIMARY'}, S, ...
    'VariableNames', {'device_id', 'device_type', 'equipment', 'ansi', 'zone', ...
    'ct_ratio', 'ct_source', 'rated_A', 'vnom_kV', 'fault_source', 'pickup_A', ...
    'tms', 'curve', 'ef_pickup_A', 'ef_tms', 'breaker_ref', 'upstream', ...
    'downstream', 'provenance', 'status', 'assumption_class', 'scope'});
set = table({'GEN-51'; 'GIS-Q0-51'}, [15023.75; 1043.95], {'A-primary'; 'A-primary'}, ...
    {'basis-a'; 'basis-b'}, {'DERIVED-study-setting'; 'DERIVED-study-setting'}, ...
    {'validation-a'; 'validation-b'}, [15000; 2000], [0.1; 0.3], {'SI'; 'SI'}, P, S, ...
    'VariableNames', {'device_id', 'setting_A_primary', 'unit', 'basis', ...
    'source', 'validation', 'ct_ratio', 'tms', 'curve', 'provenance', 'scope'});
fin = table({'F3'; 'F1'}, {'LLL'; 'LG'}, {'LF360_GAT_OUT'; 'LF360_GAT_OUT'}, ...
    [0.5; 0.5], {'Ikpp'; 'Ikpp'}, [50.5308851865359; 0.00727200442799167], ...
    [50530.8851865359; 7.27200442799167], P, S, ...
    'VariableNames', {'fault_location', 'fault_type', 'caseID', 'm', 'stage', ...
    'I_primary_kA', 'I_primary_A', 'provenance', 'scope'});
rc = table({'F3'; 'F1'}, {'LLL'; 'LG'}, {'LF360_GAT_OUT'; 'LF360_GAT_OUT'}, ...
    {'GEN-51'; 'GEN-51N'}, {'downstream'; 'downstream'}, ...
    [50530.8851865359; 7.27200442799167], [50.5308851865359; 0.00727200442799167], ...
    [15000; 15000], [3.3687257; 0.0004848], [0; 2.42400147599722], ...
    {'N/A-phase-type'; 'Iseq0-SOURCE-BACKED'}, P, S, ...
    'VariableNames', {'fault_location', 'fault_type', 'caseID', 'device_id', ...
    'side', 'I_primary_A', 'I_primary_kA', 'CT_ratio', 'I_secondary_A', ...
    'I0_A', 'I0_source', 'provenance', 'scope'});
mx = table({'GEN-51'; 'GEN-51'}, {'GSUT-HV-51'; 'GSUT-HV-51'}, {'F1'; 'F1'}, ...
    {'LLL'; 'LG'}, {'LF360_GAT_OUT'; 'LF360_GAT_OUT'}, [126.21414119005; 0.00727200442799167], ...
    [1; 2], [3; 4], [0.5; 0.6], [0.9; 0.7], [15000; 15000], [2000; 2000], ...
    [0.4; 0.1], {'PASS'; 'FAIL'}, {'reason-a'; 'reason-b'}, P, S, ...
    'VariableNames', {'downstream', 'upstream', 'fault_location', 'fault_type', ...
    'caseID', 'I_fault_kA', 'I_down_A', 'I_up_A', 't_down_s', 't_up_s', ...
    'ct_down', 'ct_up', 'margin_s', 'verdict', 'reason', 'provenance', 'scope'});
mg = table({'GEN-51>GSUT-HV-51'; 'GEN-51>GSUT-HV-51'}, {'F1'; 'F1'}, {'LLL'; 'LG'}, ...
    {'LF360_GAT_OUT'; 'LF360_GAT_OUT'}, [0.4; 0.1], {'PASS'; 'FAIL'}, ...
    {'reason-a'; 'reason-b'}, P, S, ...
    'VariableNames', {'pair', 'fault_location', 'fault_type', 'caseID', ...
    'margin_s', 'verdict', 'reason', 'provenance', 'scope'});
du = table({'F3'; 'F1'}, {'Q0'; 'Q0'}, {'LLL'; 'LG'}, ...
    {'LF360_GAT_OUT'; 'LF360_GAT_OUT'}, [3.2184; 8.0155], [100; 0.02], ...
    [NaN; NaN], {'MISSING:basis-a'; 'MISSING:basis-b'}, ...
    {'NOT DETERMINABLE FROM AVAILABLE DATA'; 'NOT DETERMINABLE FROM AVAILABLE DATA'}, ...
    {'note-a'; 'note-b'}, P, S, ...
    'VariableNames', {'location', 'breaker_ref', 'fault_type', 'caseID', ...
    'I_sym_kA', 'I_peak_kA', 'rating_kA', 'basis', 'verdict', 'note', ...
    'provenance', 'scope'});
se = tables_sens_row(P1, S1);
va = table({'R0'; 'V1'}, [1; 1], [0; 1e-7], {'note-r0'; 'note-v1'}, P, S, ...
    'VariableNames', {'leg', 'pass', 'residual', 'note', 'provenance', 'scope'});
tables = struct('registry', reg, 'settings', set, 'faultInputs', fin, ...
    'relayCurrents', rc, 'coordMatrix', mx, 'coordMargins', mg, ...
    'duty', du, 'sensitivity', se, 'validation', va);
meta = struct('tag', tag, ...
    'inputManifestSha', 'unit-test-input-sha', ...
    'inputShaLines', {{'unit-test-sha-line'}}, ...
    'validation', struct('pass', 2, 'total', 2, 'note', 'unit-test 2/2'), ...
    'testCounts', struct('NP', 1, 'NF', 0), ...
    'settingsLines', {{'unit-test settings line'}}, ...
    'extraNotes', {{'unit-test note'}});
end

function se = tables_sens_row(P1, S1)
%TABLES_SENS_ROW  One-row sensitivity table with the 28 locked columns.
se = table({'F1'}, {'LLL'}, {'LF360_GAT_OUT'}, {'GEN-51'}, {55049.0}, {55.049}, ...
    {'GEN_Q-branch-leg_GEN_kA-SOURCE-BACKED'}, {3.6699333}, {3.4405625}, ...
    15000, 16000, {'LEGACY-16000/1'}, {15023.75}, {0.1}, {'SI'}, ...
    {0.5}, {0.6}, {0.1}, {'slower'}, {0.4}, {0.3}, {-0.1}, {'tighter'}, ...
    {'PASS'}, {'FAIL'}, S1, P1, {'reason-sens'}, ...
    'VariableNames', {'fault_location', 'fault_type', 'caseID', 'device_id', ...
    'I_primary_A', 'I_primary_kA', 'relay_path', 'I_sec_primary_A', ...
    'I_sec_sens_A', 'ct_primary', 'ct_legacy', 'ct_tag', 'pickup_primary_A', ...
    'tms', 'curve', 't_primary_s', 't_sens_s', 'dt_s', 'direction', ...
    'margin_primary_s', 'margin_sens_s', 'dmargin_s', 'margin_direction', ...
    'verdict_primary', 'verdict_sens', 'scope', 'provenance', 'reason'});
end
