function [np,nf] = test_phase3_line_model()
T = t_case('Phase 3 locked 0.7 km line model');
L = ashuganj_lines();
T = T.eq(numel(L),8,'register holds 8 entries (7 Phase-2 + L_LINE)');
inc = find([L.Model_included]);
T = T.eq(numel(inc),2,'two modelled branches (ZGRID + L_LINE)');
k = find(strcmp({L.Name},'L_LINE'),1);
T = T.chk(~isempty(k),'L_LINE present');
T = T.eq(L(k).Bus_from,'B230_1','L_LINE from plant bus');
T = T.eq(L(k).Bus_to,'B230_REMOTE','L_LINE to remote bus');
T = T.eq(L(k).Vnom_V,230000,'230 kV');
T = T.eq(L(k).Length_km,0.7,'locked 0.7 km');
T = T.eq(L(k).Length_Status,'ENGINEERING_ASSUMPTION','0.7 km is EA not verified');
T = T.eq(L(k).Physical_circuit_count,2,'two physical circuits');
T = T.eq(L(k).Model_representation,'LUMPED_DUAL_CIRCUIT_PI','lumped dual-circuit PI');
T = T.eq(L(k).Conductor_reference,'MALLARD_795_MCM','Mallard reference');
T = T.near(L(k).R_ohm,0.0277725,1e-9,'R_eq 0.0277725 ohm');
T = T.near(L(k).X_ohm,0.1425655,1e-9,'X_eq 0.1425655 ohm');
T = T.near(L(k).C_F,3.937996e-6/(2*pi*50),1e-15,'C from B_eq 3.937996 uS');
T = T.eq(L(k).R0_Status,'MISSING','R0 missing not invented');
T = T.eq(L(k).X0_Status,'MISSING','X0 missing not invented');
T = T.eq(L(k).C0_Status,'MISSING','C0 missing not invented');
Gr = ashuganj_grid();
T = T.near(Gr.X_ohm,2.65581123827228,1e-9,'grid |Z| 2.6558 ohm preserved');
T = T.eq(Gr.R_ohm,0,'grid R still 0');
T = T.eq(Gr.Isc_Status,'ESTIMATED','grid stays ESTIMATED');
[np,nf] = T.done();
end
